### ISSUE TITLE
bs_theme: bad rendering of tabsetPanel type="pills", wrong theme colors

### ISSUE THREAD

**Issue by kd-chicago** [rstudio/bslib#1033]
Created application with bslib 0.4.1 under Windows 10
Use bs_theme 'superhero'
Recently updated all packages and found that theme primary color is rendered as orange (instead of blue) and tabset Panel of type 'pill' is not rendered in RStudio viewer. In firefox browser it renders correctly.
Tried different versions of bslib: version 0.5.1 works correctly, version 0.6.0 (and 0.7.0 as well) shows the above issue.

**ReprEx**

```r
library(shiny)
ui <- fluidPage(
  theme = bslib::bs_theme(version=5, bootswatch = "superhero"),
    width = 12,
    tabsetPanel(type="pills",
                header="",
                id="headerTabset",
                tabPanel(h5("Pill1"),value="pill1"),
                tabPanel(h5("Pill2"),value="pill2"),
                tabPanel(h5("Pill3"),value="pill3"),
                tabPanel(h5("Pill4"),value="pill4")
  )
) 

server <- function(input, output,session) {

 }
             
shinyApp(ui = ui, server = server)
```

### Session Info

<details>
<pre><code>
 devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/Chicago
 date     2024-03-30
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   NA

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 bslib         0.5.0   2023-06-09 [1] CRAN (R 4.2.1)
 cachem        1.0.8   2023-05-01 [1] CRAN (R 4.2.3)
 callr         3.7.1   2022-07-13 [1] CRAN (R 4.2.1)
 cli           3.6.2   2023-12-11 [1] CRAN (R 4.2.3)
 crayon        1.5.2   2022-09-29 [1] CRAN (R 4.2.3)
 devtools      2.4.4   2022-07-20 [1] CRAN (R 4.2.1)
 digest        0.6.35  2024-03-11 [1] CRAN (R 4.2.3)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.1)
 fansi         1.0.6   2023-12-08 [1] CRAN (R 4.2.3)
 fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.2.3)
 fs            1.6.3   2023-07-20 [1] CRAN (R 4.2.3)
 glue          1.7.0   2024-01-09 [1] CRAN (R 4.2.3)
 htmltools     0.5.8   2024-03-25 [1] CRAN (R 4.2.3)
 htmlwidgets   1.5.4   2022-07-23 [1] Github (ramnathv/htmlwidgets@400cf1a)
 httpuv        1.6.15  2024-03-26 [1] CRAN (R 4.2.3)
 jquerylib     0.1.4   2021-04-26 [1] CRAN (R 4.2.1)
 jsonlite      1.8.8   2023-12-04 [1] CRAN (R 4.2.3)
 later         1.3.2   2023-12-06 [1] CRAN (R 4.2.3)
 lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.2.3)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.1)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.2.1)
 mime          0.12    2021-09-28 [1] CRAN (R 4.2.0)
 miniUI        0.1.1.1 2018-05-18 [1] CRAN (R 4.2.1)
 pillar        1.9.0   2023-03-22 [1] CRAN (R 4.2.3)
 pkgbuild      1.3.1   2021-12-20 [1] CRAN (R 4.2.1)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.1)
 pkgload       1.3.0   2022-06-27 [1] CRAN (R 4.2.1)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.2.1)
 processx      3.7.0   2022-07-07 [1] CRAN (R 4.2.1)
 profvis       0.3.7   2020-11-02 [1] CRAN (R 4.2.1)
 promises      1.2.1   2023-08-10 [1] CRAN (R 4.2.3)
 ps            1.7.1   2022-06-18 [1] CRAN (R 4.2.1)
 purrr         1.0.2   2023-08-10 [1] CRAN (R 4.2.3)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.1)
 Rcpp          1.0.12  2024-01-09 [1] CRAN (R 4.2.3)
 remotes       2.4.2.1 2023-07-18 [1] CRAN (R 4.2.3)
 rlang         1.1.3   2024-01-10 [1] CRAN (R 4.2.3)
 rsconnect     0.8.28  2022-10-24 [1] CRAN (R 4.2.1)
 rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.2)
 sass          0.4.9   2024-03-15 [1] CRAN (R 4.2.3)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.1)
 shiny       * 1.8.1   2024-03-26 [1] CRAN (R 4.2.3)
 shinythemes * 1.2.0   2021-01-25 [1] CRAN (R 4.2.3)
 stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
 stringr       1.4.0   2019-02-10 [1] CRAN (R 4.2.1)
 tibble        3.2.1   2023-03-20 [1] CRAN (R 4.2.3)
 urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.2.1)
 usethis       2.1.6   2022-05-25 [1] CRAN (R 4.2.1)
 utf8          1.2.4   2023-10-22 [1] CRAN (R 4.2.3)
 vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.2.3)
 withr         3.0.0   2024-01-16 [1] CRAN (R 4.2.3)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.2.1)

</code></pre>
</details>

![BSLIB_051_RStudioViewer](https://github.com/rstudio/bslib/assets/79772089/6a45f469-4ed2-494d-8a73-55d39fa978d4)
![BSLIB_060_RStudioViewer](https://github.com/rstudio/bslib/assets/79772089/8b8bd470-07f9-4d99-ab3b-324ba1ba9035)
![BSLIB_060_FireFox](https://github.com/rstudio/bslib/assets/79772089/abec53dc-5909-4757-89fd-b7d339837a7c)

**Comment by gadenbuie** [comment]
In bslib 0.6.0 we upgraded to Bootstrap (and Bootswatch) v5.3.1, which was a big change from bslib 0.4.1 (which had Bootstrap v5.1.3, I believe). It's very possible that the blue → orange change in the nav pills came from that upgrade, either in Bootswatch or Bootstrap. It's hard to tell, though, because it appears that orange has always been the primary color for [the Superhero theme](https://bootswatch.com/superhero/).

Interestingly, I don't see a color in the Superhero theme that matches the blue in your first screenshot. That said, you can use an extra CSS rule like the below to get a blue pill background:

```r
ui <- fluidPage(
  theme = bslib::bs_theme(version=5, bootswatch = "superhero") |>
    bslib::bs_add_rules(".nav-pills { --bs-nav-pills-link-active-bg: var(--bs-info) }"),
  ...
)
```

As for the unstyled content in RStudio, that might be a cache-related problem (old styles held on to by the browser in RStudio). I tried your reprex in a newer version of RStudio and it worked as expected. I'm going to close it for now because I don't think there's anything for us to do. But if you're still having the problem, feel free to comment on this issue!
