### ISSUE TITLE
css not loaded properly on chrome in deployed shiny + bslib app

### ISSUE THREAD

**Issue by wvictor14** [rstudio/bslib#1060]
## Describe the problem

Hi, I have used bslib to develop a shiny app which I have deployed as a docker container hosted on digital ocean. The issue I am facing is that the deployed app is unable to load css only on chrome - other browsers work fine. I am not seeing any errors in the log and unable to reproduce locally (i.e. runs fine in chrome when launched from rstudio console). I see there are errors in the devtools console but not sure how to interpret as I have limited css/html knowledge. Would appreciate any ideas or comments.

offending web app: https://www.victoryuan.com/rbiotechsalary
Screenshot of chrome [css not loaded]:
![image](https://github.com/rstudio/bslib/assets/22013187/3d9db3c4-5614-4034-9a30-9fa72fdd80ff)

### devtools console errors
<details>
<pre><code>
GET https://www.victoryuan.com/shiny-sass-1.8.1.1/shiny-sass.css net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:7 
        
        
       GET https://www.victoryuan.com/jquery-3.6.0/jquery.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:12 
        
        
       GET https://www.victoryuan.com/bootstrap-5.3.1/bootstrap.bundle.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:13 
        
        
       GET https://www.victoryuan.com/bs3compat-0.7.0/transition.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:9 
        
        
       GET https://www.victoryuan.com/shiny-javascript-1.8.1.1/shiny.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:17 
        
        
       GET https://www.victoryuan.com/bslib-component-js-0.7.0/web-components.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:16 
        
        
       GET https://www.victoryuan.com/bslib-component-js-0.7.0/components.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:11 
        
        
       GET https://www.victoryuan.com/bootstrap-5.3.1/bootstrap.min.css net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:19 
        
        
       GET https://www.victoryuan.com/font-awesome-6.4.2/css/all.min.css net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:22 
        
        
       GET https://www.victoryuan.com/htmlwidgets-1.6.4/htmlwidgets.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:24 
        
        
       GET https://www.victoryuan.com/bslib-tag-require-0.7.0/tag-require.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:18 
        
        
       GET https://www.victoryuan.com/bslib-component-css-0.7.0/bslib-component-css.min.css net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:25 
        
        
       GET https://www.victoryuan.com/core-js-2.5.3/shim.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:20 
        
        
       GET https://www.victoryuan.com/font-awesome-6.4.2/css/v4-shims.min.css net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:26 
        
        
       GET https://www.victoryuan.com/react-18.2.0/react.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:21 
        
        
       GET https://www.victoryuan.com/htmltools-fill-0.5.8.1/fill.css net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:14 
        
        
       GET https://www.victoryuan.com/bs3compat-0.7.0/tabs.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:29 
        
        
       GET https://www.victoryuan.com/reactable-0.4.4.9000/reactable.css net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:28 
        
        
       GET https://www.victoryuan.com/reactwidget-1.0.0/react-tools.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:33 
        
        
       GET https://www.victoryuan.com/selectize-0.15.2/selectize-plugin-a11y.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:27 
        
        
       GET https://www.victoryuan.com/react-18.2.0/react-dom.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:31 
        
        
       GET https://www.victoryuan.com/selectize-0.15.2/selectize.css net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:23 
        
        
       GET https://www.victoryuan.com/plotly-binding-4.10.4/plotly.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:30 
        
        
       GET https://www.victoryuan.com/reactable-binding-0.4.4.9000/reactable.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:15 
        
        
       GET https://www.victoryuan.com/bs3compat-0.7.0/bs3compat.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:32 
        
        
       GET https://www.victoryuan.com/selectize-0.15.2/selectize.min.js net::ERR_ABORTED 404 (Not Found)
rbiotechsalary:137 Uncaught ReferenceError: bslib is not defined
    at rbiotechsalary:137:56
(anonymous) @ rbiotechsalary:137
rbiotechsalary:157 Uncaught ReferenceError: bslib is not defined
    at rbiotechsalary:157:56
(anonymous) @ rbiotechsalary:157
rbiotechsalary:177 Uncaught ReferenceError: bslib is not defined
    at rbiotechsalary:177:56
(anonymous) @ rbiotechsalary:177
rbiotechsalary:185 Uncaught ReferenceError: bslib is not defined
    at rbiotechsalary:185:48
(anonymous) @ rbiotechsalary:185
rbiotechsalary:198 Uncaught ReferenceError: bslib is not defined
    at rbiotechsalary:198:48
(anonymous) @ rbiotechsalary:198
rbiotechsalary:212 Uncaught ReferenceError: bslib is not defined
    at rbiotechsalary:212:46
(anonymous) @ rbiotechsalary:212
rbiotechsalary:382 Uncaught ReferenceError: bslib is not defined
    at rbiotechsalary:382:41
</code></pre>
</details>

Screenshot of edge [css loaded]:
![image](https://github.com/rstudio/bslib/assets/22013187/4ad8ece5-0d1c-4fb8-99b4-1ed7d05d7c77)

Dockerfile + github repo of web app: https://github.com/wvictor14/rbiotechsalary/blob/main/dockerfile

app files:
https://github.com/wvictor14/rbiotechsalary/tree/main/inst/app

docker image on docker hub for deployed app https://hub.docker.com/layers/victor2wy/rbiotechsalary/latest/images/sha256-48afa2a431ddd67ac715a9ff990fe9f3d128e49f0065963e479431a2aedbe509?context=repo

### Session Info

<details>
<pre><code>
> devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.0 (2024-04-24)
 os       Ubuntu 22.04.4 LTS
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2024-05-30
 pandoc   3.2 @ /usr/bin/pandoc

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 package        * version    date (UTC) lib source
 base64enc        0.1-3      2015-07-28 [1] RSPM (R 4.4.0)
 bit              4.0.5      2022-11-15 [1] RSPM (R 4.4.0)
 bit64            4.0.5      2020-08-30 [1] RSPM (R 4.4.0)
 bsicons          0.1.2      2023-11-04 [1] RSPM (R 4.4.0)
 bslib          * 0.7.0      2024-03-29 [1] RSPM (R 4.4.0)
 cachem           1.1.0      2024-05-16 [1] RSPM (R 4.4.0)
 cli              3.6.2      2023-12-11 [1] RSPM (R 4.4.0)
 crayon           1.5.2      2022-09-29 [1] RSPM (R 4.4.0)
 devtools         2.4.5      2022-10-11 [1] RSPM (R 4.4.0)
 digest           0.6.35     2024-03-11 [1] RSPM (R 4.4.0)
 dplyr          * 1.1.4      2023-11-17 [1] RSPM (R 4.4.0)
 ellipsis         0.3.2      2021-04-29 [1] RSPM (R 4.4.0)
 fansi            1.0.6      2023-12-08 [1] RSPM (R 4.4.0)
 fastmap          1.2.0      2024-05-15 [1] RSPM (R 4.4.0)
 fontawesome      0.5.2      2023-08-19 [1] RSPM (R 4.4.0)
 forcats          1.0.0      2023-01-29 [1] RSPM (R 4.4.0)
 fs               1.6.4      2024-04-25 [1] RSPM (R 4.4.0)
 generics         0.1.3      2022-07-05 [1] RSPM (R 4.4.0)
 glue             1.7.0      2024-01-09 [1] RSPM (R 4.4.0)
 hms              1.1.3      2023-03-21 [1] RSPM (R 4.4.0)
 htmltools        0.5.8.1    2024-04-04 [1] RSPM (R 4.4.0)
 htmlwidgets      1.6.4      2023-12-06 [1] RSPM (R 4.4.0)
 httpuv           1.6.15     2024-03-26 [1] RSPM (R 4.4.0)
 jquerylib        0.1.4      2021-04-26 [1] RSPM (R 4.4.0)
 jsonlite         1.8.8      2023-12-04 [1] RSPM (R 4.4.0)
 knitr            1.46       2024-04-06 [1] RSPM (R 4.4.0)
 later            1.3.2      2023-12-06 [1] RSPM (R 4.4.0)
 lifecycle        1.0.4      2023-11-07 [1] RSPM (R 4.4.0)
 magrittr         2.0.3      2022-03-30 [1] RSPM (R 4.4.0)
 memoise          2.0.1      2021-11-26 [1] RSPM (R 4.4.0)
 mime             0.12       2021-09-28 [1] RSPM (R 4.4.0)
 miniUI           0.1.1.1    2018-05-18 [1] RSPM (R 4.4.0)
 pillar           1.9.0      2023-03-22 [1] RSPM (R 4.4.0)
 pkgbuild         1.4.4      2024-03-17 [1] RSPM (R 4.4.0)
 pkgconfig        2.0.3      2019-09-22 [1] RSPM (R 4.4.0)
 pkgload          1.3.4      2024-01-16 [1] RSPM (R 4.4.0)
 profvis          0.3.8      2023-05-02 [1] RSPM (R 4.4.0)
 promises         1.3.0      2024-04-05 [1] RSPM (R 4.4.0)
 purrr            1.0.2      2023-08-10 [1] RSPM (R 4.4.0)
 R6               2.5.1      2021-08-19 [1] RSPM (R 4.4.0)
 rbiotechsalary * 0.3.2      2024-05-28 [1] local
 Rcpp             1.0.12     2024-01-09 [1] RSPM (R 4.4.0)
 reactable        0.4.4.9000 2024-05-28 [1] Github (glin/reactable@22ccffc)
 readr            2.1.5      2024-01-10 [1] RSPM (R 4.4.0)
 remotes          2.5.0      2024-03-17 [1] RSPM (R 4.4.0)
 repr             1.1.7      2024-03-22 [1] RSPM (R 4.4.0)
 rlang            1.1.3      2024-01-10 [1] RSPM (R 4.4.0)
 sass             0.4.9      2024-03-15 [1] RSPM (R 4.4.0)
 sessioninfo      1.2.2      2021-12-06 [1] RSPM (R 4.4.0)
 shiny          * 1.8.1.1    2024-04-02 [1] RSPM (R 4.4.0)
 skimr            2.1.5      2022-12-23 [1] RSPM (R 4.4.0)
 stringi          1.8.4      2024-05-06 [1] RSPM (R 4.4.0)
 stringr          1.5.1      2023-11-14 [1] RSPM (R 4.4.0)
 tibble           3.2.1      2023-03-20 [1] RSPM (R 4.4.0)
 tidyr            1.3.1      2024-01-24 [1] RSPM (R 4.4.0)
 tidyselect       1.2.1      2024-03-11 [1] RSPM (R 4.4.0)
 tzdb             0.4.0      2023-05-12 [1] RSPM (R 4.4.0)
 urlchecker       1.0.1      2021-11-30 [1] RSPM (R 4.4.0)
 usethis          2.2.3      2024-02-19 [1] RSPM (R 4.4.0)
 utf8             1.2.4      2023-10-22 [1] RSPM (R 4.4.0)
 vctrs            0.6.5      2023-12-01 [1] RSPM (R 4.4.0)
 vroom            1.6.5      2023-12-05 [1] RSPM (R 4.4.0)
 withr            3.0.0      2024-01-16 [1] RSPM (R 4.4.0)
 xfun             0.44       2024-05-15 [1] RSPM (R 4.4.0)
 xtable           1.8-4      2019-04-21 [1] RSPM (R 4.4.0)

 [1] /usr/local/lib/R/site-library
 [2] /usr/local/lib/R/library

</code></pre>
</details>

**Comment by wvictor14** [comment]
Some progress, I have found that under networking tabs I can see that the requested url is different in chrome (incorrect) and edge browsers:


In the browser edge, I can see that the css/js is being successfully obtained from the url:
200: https://www.victoryuan.com/rbiotechsalary/font-awesome-6.4.2/css/v4-shims.min.css

But I see in chrome it is trying to request from the base, it is missing the subdir "/rbiotechsalary":
404: https://www.victoryuan.com/font-awesome-6.4.2/css/all.min.css

Based on this, I am not sure if this is a bslib issue, but actually a networking/routing issue. It is confusing that it seems to work in some browsers but not chrome. I am currently investigating with my deployment service provider to see if I can fix it from that end (I'm using app platform on digital ocean).

**Comment by gadenbuie** [comment]
I wonder if the trailing slash is the difference? Can you try opening `https://www.victoryuan.com/rbiotechsalary` and `https://www.victoryuan.com/rbiotechsalary/` in the browsers to see if there's a difference?

**Comment by wvictor14** [comment]
Alright a little embarrassing but I figured out it was simply an older broken version was cached. And apparently the hard refresh I was doing wasn't clearing it so ended deleting the cache completely and now the page loads fine. Thanks for attention anyways!
