### ISSUE TITLE
{bsicons} should be imported rather than suggested

### ISSUE THREAD

**Issue by daattali** [rstudio/bslib#1063]
I just tried running `bs_theme_preview()` and got an error because {bsicons} wasn't installed. I then did a search through {bslib}'s codebase and I see that there are other uses of {bsicons} so it would probably be a good idea to make it an import

**Comment by gadenbuie** [comment]
Thanks @daattali, it'd be reasonable for bslib to depend directly on bsicons, but we have to balance bslib's dependencies with the fact that bslib is in turn a direct dependency of shiny.

I looked through the codebase and `bs_theme_preview()` is the only place where we directly call bsicons, in all other places we're careful to use bsicons as a progressive enhancement. I think it's reasonable that bsicons remain a suggested dependency for now.
