### ISSUE TITLE
Should `theme` argument in `page_*()` functions accept a string?

### ISSUE THREAD

**Issue by daattali** [rstudio/bslib#1067]
In shiny's page functions, the `theme` argument can accept either a `bs_theme()` object or a path to a CSS file.

In bslib's page functions, the documentation says that the only acceptable value is a `bs_theme()` object. However, it seems that providing a string path to a CSS file also works. Should this be accepted or no? If yes, it should be documented. If no, an error should get thrown.

**Comment by cpsievert** [comment]
I think the ship has probably sailed at this point for accepting a string. We also do throw an informative error:

```r
> bslib::page("bar", theme = "foo")
Error in assert_bs_theme(theme) : `theme` must be a `bs_theme()` object
```

**Comment by daattali** [comment]
Strange, I tested on both the CRAN version and the latest github version of {bslib}, and `ui <- page(theme = "style.css", "test")` does work for me. No error message, and it applies the stylesheet.

**Comment by cpsievert** [comment]
Ahh, right, that error only gets thrown when rendered statically. Otherwise, it gets passed to `shiny::bootstrapPage()`, which doesn't error. Maybe we should do more to throw earlier on.

**Comment by gadenbuie** [comment]
The other side of this would be to allow a string value for `theme`, in which case `theme` should point to a static CSS file, i.e. a pre-compiled Bootstrap theme. This would be in line with how the `theme` argument works in Shiny for Python page functions. But it would require more thinking (and also probably improved utilities for saving a `bs_theme()` to a set of static files, which of course brings additional issues with Shiny's built-in components that do use `bs_dependency()`).

Clearly throwing an error would be easier, but I think we should contemplate alternatives before implementing.

**Comment by daattali** [comment]
What is meant by "static rendering"? What is the dynamic rendering version of the code I gave above `ui <- page(theme = "style.css", "test")`?

**Comment by gadenbuie** [comment]
> What is meant by "static rendering"?

I think Carson means printing `ui` or otherwise rendering it to html, where dynamic rendering would be using `ui` in a Shiny app.
