### ISSUE TITLE
UI page functions don't know how to deal with extra commas like {shiny} does

### ISSUE THREAD

**Issue by daattali** [rstudio/bslib#1097]
In the olden days, shiny apps would break if there was any extra comma in the UI. This was fixed a few years ago and now the following app works: 

```{r}
library(shiny)

ui <- fluidPage(
  "foo",
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

But when I try the same using {bslib}, I get an error:

```{r}
library(shiny)

ui <- bslib::page_fluid(
    "foo",
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

```
Error in `dots_list()`:
! Argument 3 can't be empty.
```

**Comment by daattali** [comment]
AFAICT this ws described but not fixed in https://github.com/rstudio/bslib/issues/956

**Comment by gadenbuie** [comment]
I just fixed this in https://github.com/rstudio/bslib/pull/1095. It made it into the 0.8.0 release that landed on CRAN this week. Let us know if you're still seeing the issue after updating.

**Comment by daattali** [comment]
Fixed indeed!
