### ISSUE TITLE
page_fillable leaves a gap on the bottom on Windows

### ISSUE THREAD

**Issue by daattali** [rstudio/bslib#1100]
The following code:

```r
library(shiny)

ui <- bslib::page_fillable(
    padding = 0,
    bslib::card("test")
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

results in whitespace below the card, which only gets fixed if I add `gap=0`. This is happening with {bslib} 0.6, 0.7 and 0.8. I'm on Windows. I updated to the latest {shiny} and {htmltools} and it still happens.

When I run the same code on https://shinylive.io/r , it does not happen

**Comment by gadenbuie** [comment]
Thanks, which browser (and version) are you using?

**Comment by daattali** [comment]
Chrome Version 126.0.6478.182

**Comment by gadenbuie** [comment]
Does it reproduce for you in Chrome 127?

Chrome doesn't make it easy to find older versions, but I had Edge with Chrome 125 installed in my Windows 11 VM. I can't reproduce the issue with Chrome 125 (in Edge) or Chrome 127.

Are there any hints when you inspect the DOM?

We do have an `<svg>` element that will be a sibling of the card element, but it should have both `positon: absolute` (moving it out of the document flow) and `aria-hidden="true"` (removing it from the accessibility tree, too). It'd be strange if that were causing the problem, but worth taking a look at it.

**Comment by daattali** [comment]
Ah, the [loom](https://loom.com) extension adds an element... 
![image](https://github.com/user-attachments/assets/d38e730a-ea06-4186-8291-8596b5a9b5d6)
