### ISSUE TITLE
[Feature Request] Support for AdminLTE template

### ISSUE THREAD

**Issue by dsen6644** [rstudio/bslib#1103]
Based on #585 and #976 there seems to be a desire for bslib to support the AdminLTE template, is this on the bslib roadmap?

**Comment by gadenbuie** [comment]
We plan to add support for sidebar navigation (#585) but don't have plans to wrap the AdminLTE template in bslib, sorry. We'd welcome an adminlte package in the ecosystem! But it's enough work maintaining bslib and its use of Bootstrap and Bootswatch themes.
