### ISSUE TITLE
Add $code-bg to BS4

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#181]
BS3 has it, and it's probably better to keep it so that by default code styling is similar, but folks would still have abaility to turn it off with `$code-bg: null`

**Comment by hadley** [comment]
The `<code>` border color also needs fixing I think.

**Comment by cpsievert** [comment]
Would you expect the border color to be the same as the one set on `<pre>`?

**Comment by cpsievert** [comment]
Oh actually BS3 didn't set a border on inline code (and I think I slightly prefer no border), so I don't think we'll need it?

**Comment by hadley** [comment]
Oh maybe it was the foreground colour?

**Comment by cpsievert** [comment]
Yea I kinda remember you mentioning this. I don't think `$code-bg: $pink !default` looks great either, but at least it's consistent with BS3? I imagine you'd prefer something like `$code-bg: $link-color !default`  for consistency with `downlit` projects? I'm not sure I'm board with that since code and links would look visually the same (I guess we could add underlines to links, but that's a pretty big deviation from vanilla Bootstrap and not ideal for mobile)

**Comment by hadley** [comment]
If you don't change it by default, I think it needs to be a prominent option, because the default looks pretty terrible when you mix in a bunch of code in your text. But I think you should seriously consider changing the default, even if it's not the same as BS3.

**Comment by cpsievert** [comment]
Do you like the way GitHub does it (i.e., they don't change the fg `color`)?
