### ISSUE TITLE
Bootswatch Sketchy theme: Checkboxes and Radio buttons placement looks off

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/bslib#192]
1. Navigate to https://testing-apps.shinyapps.io/shinyapps-themer-demo-Dec-16/
2. Go to wellpanel section
3. From the themer box, select "Sketchy" theme
4. Notice the Check boxes and Radio buttons

<img width="1671" alt="themer-demo-well_panel_sketchy-theme_checkboxes_radio_buttons" src="https://user-images.githubusercontent.com/5369655/102397005-2b599b80-3f92-11eb-919c-8564c128464f.png">

Note: This issue is seen on all the platforms

**Comment by cpsievert** [comment]
Thanks! Here's a more minimal repex:

```r
library(shiny)

ui <- fluidPage(
  theme = bs_theme(bootswatch = "sketchy"),
  checkboxGroupInput("x", "Choices", c("a", "b")),
  radioButtons("y", "Choices", c("c", "d"))
)

server <- function(input, output, session) {
  observe({
    print(input$x)
    print(input$y)
  })
}

shinyApp(ui, server)
```

**Comment by MadhulikaTanuboddi** [comment]
@cpsievert : I noticed on Windows - Edge browser, checkboxes and radio buttons are not shown. This could be due to the Edge browser version I am using with parallels VM.

<img width="1456" alt="Edge_sketchy_theme_checkboxes_radio_buttons" src="https://user-images.githubusercontent.com/5369655/103670505-80a02180-4f2e-11eb-9561-c559e60ea4eb.png">

**Comment by cpsievert** [comment]
Appears this isn't an issue with modern versions of Edge, so let's not worry about it
