### ISSUE TITLE
Real time themer: Switching back to Default theme shows incorrect theme

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/bslib#196]
1. Navigate to https://testing-apps.shinyapps.io/madhu-dec11-themer-demo/
2. Notice the "Default" theme styles and colors
3. Select a different theme for ex: Cosmo
4. Now, switch back to "Default" theme

Expected: Should show the respective styles and colors for Default theme
Actual: bg and fg colors are not reset back to Default. Notice the following snapshots

Before:
<img width="1677" alt="Default_theme_before_switch" src="https://user-images.githubusercontent.com/5369655/102419663-19d5bb00-3fb5-11eb-86ce-399f332ae92d.png">

After:
<img width="1677" alt="Default_theme_after_switching back_from_a different_theme" src="https://user-images.githubusercontent.com/5369655/102419689-29550400-3fb5-11eb-9109-d69eeb32ecfb.png">

Note: This is mostly an issue only on hosted platforms (shinyapps.io and connect). Carson is also able to repro this on https://testing-apps.shinyapps.io/themer-demo/. However, we could not repro this again with the more recent deploy to shinyapps.io/connect. for ex: https://testing-apps.shinyapps.io/shinyapps-themer-demo-Dec-16/ and https://beta.rstudioconnect.com/content/15287/ work as expected with the above scenario.

**Comment by cpsievert** [comment]
Thanks for writing this up. I just redeployed https://testing-apps.shinyapps.io/themer-demo/ with the latest `{shiny}`+`{bslib}` and this appears to no longer be an issue, so let's look the other way for now, but this'll be a good test case to keep in mind if and when we make changes to the themer in the future
