### ISSUE TITLE
Tab highlight issue in navlistPanel

### ISSUE THREAD

**Issue by DivadNojnarg** [rstudio/bslib#21]
First case without boostraplib:

```r
library(shiny)
ui <- fluidPage(
  navlistPanel(
    tabPanel("One", "One"),
    tabPanel("Two", icon = icon("download"), "Two"),
    navbarMenu("A submenu",
               tabPanel("Three", "Three"),
               "---",
               tabPanel("Four", "Four"),
               tabPanel("Five", "Five")
    )
  )
)


server <- function(input, output) {}
shinyApp(ui, server)
```

I clicked first on the second tabPanel. When I click on the navbaMenu, the second tabPanel is still highlighted. I would need to click on any nested tabPanel to make the navbarMenu highlighted. 

<img width="463" alt="Screenshot 2019-12-12 at 21 34 41" src="https://user-images.githubusercontent.com/18291543/70747124-99d49f80-1d27-11ea-9fcc-3607ae581787.png">

When I switch to boostraplib:

```r
library(shiny)
library(bootstraplib)
shinyOptions(bootstraplib = TRUE)
# customize the primary Bootstrap color, 
# which influences the color of navigation links
bs_theme_accent_colors(primary = "salmon")

ui <- fluidPage(
  navlistPanel(
    tabPanel("One", "One"),
    tabPanel("Two", icon = icon("download"), "Two"),
    navbarMenu("A submenu",
               tabPanel("Three", "Three"),
               "---",
               tabPanel("Four", "Four"),
               tabPanel("Five", "Five")
    )
  )
)


server <- function(input, output) {}
shinyApp(ui, server)
```

<img width="463" alt="Screenshot 2019-12-12 at 21 35 25" src="https://user-images.githubusercontent.com/18291543/70747316-0485db00-1d28-11ea-9537-9ed6c0db97e0.png">

If I select the first tabPanel and click on the navbarMenu, both are highlighted at the same time.

I would expect the same behaviour as in vanilla shiny.

**Comment by cpsievert** [comment]
I'm pretty sure this is "expected" BS4 behavior? If you click on the dropdown here, you get the same behavior https://getbootstrap.com/docs/4.4/components/navs/#pills-with-dropdowns
