### ISSUE TITLE
bootstrap 3: Dotted border lines shown around html components (navs, tables, panels etc)

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/bslib#232]
Check the snapshots below

When testing the themer-demo app with bootstrap version3, I noticed some border lines(dotted) around some of the html components especially when using all the bootswatch themes (listed in the real time themer). In order to see the these dotted borders, make sure to have the focus on the page (In other words, click somewhere on the page). Also, note that this does not happen with bootstrap version4

@cpsievert mentioned that this could be expected to support accessibility for navigation. Just adding this issue for tracking and probably more details needed on how we want to work regarding the same with bootstrap version 4 or future versions.

<img width="1666" alt="bs3_borderline-containers" src="https://user-images.githubusercontent.com/5369655/105090743-a875a600-5a53-11eb-914d-d4dda8276547.png">

<img width="1680" alt="Screen Shot 2021-01-12 at 12 25 17 PM" src="https://user-images.githubusercontent.com/5369655/105090799-bdead000-5a53-11eb-8bb4-0c87dc172d54.png">

<img width="1680" alt="Screen Shot 2021-01-12 at 12 06 25 PM" src="https://user-images.githubusercontent.com/5369655/105090829-c8a56500-5a53-11eb-8a0d-9bf051c11530.png">

Additional context:
Initially, this issue was noticed on Jan 12. I am testing this fix (https://github.com/rstudio/bslib/pull/224) today using `remotes::install_github("rstudio/bslib@rc-v0.2.4")` and its not resolved yet.

**Comment by cpsievert** [comment]
Ah, crap, this was the point of #224, but I didn't roll that into rc-v0.2.4 correctly 🤦

**Comment by cpsievert** [comment]
@MadhulikaTanuboddi I was able to get the fix for this into the CRAN version of bslib. Feel free to verify with

```
install.packages("bslib")
```
