### ISSUE TITLE
[README enhancement] Provide example of an appropriate bslib compatible theme arg in YAML header

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/bslib#258]
https://github.com/rstudio/bslib/blob/f8c136e2e1e562931283fdb806082a5e1debf9e5/README.Rmd#L189

The above section of the readme indicates that it is possible to use bslib theming in documents such as flexdashboard so long as it is following the appropriate convention in the `theme:` section of the YAML header. That isn't necessarily clear to me as what that format would be. It would be nice to include a very brief example immediately following that statement. 

:)

**Comment by cpsievert** [comment]
Ok, good point, here's an example of opting-into bootstrap 4

```r
output:
  flexdashboard::flex_dashboard
    theme: 
      version: 4
```

Just FYI, I should hopefully have a PR up by the end of the week to flexdashboard to make it work better with bslib

**Comment by JosiahParry** [comment]
Awesome! Thanks Carson :)
