### ISSUE TITLE
DT with lux theme covers the whole page. 

### ISSUE THREAD

**Issue by shalutiwari** [rstudio/bslib#264]
Install remotes::install_github("rstudio/DT") and then run below app. Then change the theme to Lux. It covered the whole page.

```

library(shiny)
library(DT)

ui <- fluidPage(
  theme = bslib::bs_theme(),
  dataTableOutput("x")
)

server <- function(input, output, session) {
   bslib::bs_themer()
  output$x <- renderDataTable({
    datatable(mtcars)
  })
}

shinyApp(ui, server)

```

<img width="1436" alt="lux-new" src="https://user-images.githubusercontent.com/32690638/107705034-c8c80780-6c83-11eb-8690-6b788c736218.png">

**Comment by cpsievert** [comment]
@shalutiwari I'm having difficulty replicating this -- can you consistently repro with this code cross-browser? `bs_theme_preview(bs_theme(bootswatch = "lux"))`

**Comment by MadhulikaTanuboddi** [comment]
Side note/ux issue: Notice the arrows for column sorting. They look little off. @cpsievert : Shall I file a separate issue?

**Comment by cpsievert** [comment]
@MadhulikaTanuboddi I'm OK with ignoring the arrows (we've got much bigger fish to fry)

Closing this as I can't seem to replicate this behavior (please reopen if you can)

**Comment by dc27** [comment]
"lux" theme extends beyond the defined `column` width. Other versions reduced table size to fit the space (I tried "mint", "morph", "cyborg", and "sandstone".)

hopefully reproducible: 
```
library(shiny)
library(DT)

ui <- fluidPage(
  theme = bslib::bs_theme(version = 5, bootswatch = "lux"),
  sidebarLayout(
    sidebarPanel(
      sliderInput(
        "cyls",
        "Cylinders",
        min = min(mtcars$cyl),
        max = max(mtcars$cyl),
        value = median(mtcars$cyl)
      )
    ),
    mainPanel(
      fluidRow(
        column(
          12,
          dataTableOutput("cars_table")
        )
      )
    )
  )
)

server <- function(input, output, session) {
  output$cars_table <- renderDataTable({
    dplyr::filter(mtcars, cyl == input$cyls)
  })
}

shinyApp(ui, server)
```

session info:
```
other attached packages:
bslib_0.3.1
DT_0.18    
shiny_1.7.1
```
