### ISSUE TITLE
DT: "Darkly", "Cyborg" and "Slate" themes: Column filter's "min" and "max" values not displayed.

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/bslib#267]
1. Run the following example: (uses "darkly" theme, could be replaced with "cyborg" and "slate" themes)

```
library(shiny)
library(DT)

ui <- fluidPage(
  theme = bslib::bs_theme(
    bootswatch = "darkly"
  ),
  dataTableOutput("x")
)

server <- function(input, output, session) {
  output$x <- renderDataTable({
    datatable(iris, filter = 'top', options = list(
      pageLength = 100, scrollX = TRUE, scrollY = "600px", autoWidth = TRUE
    ))
  })
}

shinyApp(ui, server)
```
2. Click on the filters under each column ("All" textbox)
3. Notice on the slider bar to filter, "min" and "max" values are not shown 

**Few sample snapshots**
DARKLY:
![Screen Shot 2021-02-12 at 5 41 33 PM](https://user-images.githubusercontent.com/5369655/107838214-9e487e00-6d59-11eb-8f8f-2ee035bd6dbe.png)

CYBORG:
![DT_cran_cyborg_theme_range_selection_lin_max_values_not_visible](https://user-images.githubusercontent.com/5369655/107838066-f9c63c00-6d58-11eb-9da2-b13a81b3a09f.png)

"SLATE"
![Screen Shot 2021-02-12 at 4 48 03 PM](https://user-images.githubusercontent.com/5369655/107838073-03e83a80-6d59-11eb-8fcf-9fd863c00598.png)

**Side note: With "Superhero" theme, the values are barely visible**
![Screen Shot 2021-02-12 at 4 51 41 PM](https://user-images.githubusercontent.com/5369655/107838078-0b0f4880-6d59-11eb-9690-fc3915c5af60.png)

**Comment by PythonCoderUnicorn** [comment]
Hello @MadhulikaTanuboddi ,

 I noticed you have a thematic_shiny app and your boxes are all white. Perhaps a solution is to have
`thematic::thematic_shiny(font="auto")`  above your shiny `ui = fluidPage()`

I theme my shiny and Rmarkdown files and always see the variables in my drop down menus, like so in the image below.

<img width="896" alt="Screen Shot 2022-05-02 at 2 23 57 PM" src="https://user-images.githubusercontent.com/55933131/166320415-2ddea299-9e2b-4490-89ab-05289c668ad3.png">

**Comment by prubin73** [comment]
I have the same problem. With the darkly and cyborg themes, the text on sliders is completely invisible (white on white). With superhero, the text is almost but not quite invisible. With the slate theme, the text on sliders is faint but (barely) legible.
