### ISSUE TITLE
New card constructors

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#297]
Probably a general `card()` as well as special cases of it

**Comment by jtrecenti** [comment]
Got here because of Greg Swinehart's presentation on rstudio conf 2022. In the last minutes he showed an amazing shiny app entirely made by blsib (afaik).

https://www.rstudio.com/conference/2022/schedule/

Really excited for this update. Am I looking at the right place? Thanks!

**Comment by cpsievert** [comment]
`card()` is now available in the development version https://rstudio.github.io/bslib/articles/cards.html
