### ISSUE TITLE
rmarkdown - New R Markdown - Not showing up in Templates

### ISSUE THREAD

**Issue by j450h1** [rstudio/bslib#309]
I recently installed bslib on a new windows machine (R version 4.0.5 and Rstudio Version 1.4.1106). How come the templates don't appear?

![image](https://user-images.githubusercontent.com/7351530/115835747-7a459080-a3cb-11eb-9e8d-b3f519dd119e.png)

**Comment by cpsievert** [comment]
You (currently) need the dev verion `remotes::install_github("rstudio/bslib")` (CRAN release coming soon)
