### ISSUE TITLE
Using bslib to create one light and one dark stylesheet

### ISSUE THREAD

**Issue by maelle** [rstudio/bslib#326]
This is an usage question, maybe a feature request, that I can take elsewhere if needed. I'd appreciate any tip/hint or examples to look at.

When working on pkgdown dark mode, I am calling bslib functions twice to create bundles: one for the light theme, one for the dark theme. From the dark theme I actually only want the CSS as theme switching only is stylesheet (de)activation. I have this workaround that doesn't completely work as I still end up with a JS file for the dark theme.

```r
  # only keep what's different
# dark_deps is the output of a call to bslib::bs_theme()
  dark_deps <- dark_deps[purrr::map_chr(dark_deps, "name") == "bootstrap"]
  dark_deps[[1]]$script <- NULL
```

Then I copy the light and dark dependencies in separate folders, to ensure their link will be different (ideally I'd like their filenames to be different, but didn't find how to):

```r
deps <- c(
    lapply(
      light_deps,
      htmltools::copyDependencyToDir,
      file.path(pkg$dst_path, "deps")
    ),
    lapply(
      dark_deps,
      htmltools::copyDependencyToDir,
      file.path(pkg$dst_path, "deps-dark")
    )
  )
```

followed by a call to `htmltools::renderDependencies()`.

Later, I tweak the HTML of head to add the attributes I need the stylesheets to have, using a function like below.

```r
tweak_css_link <- function(link) {
  if (grepl("dark", xml2::xml_attr(link, "href"))) {
    xml2::xml_attr(link, "media") <- "(prefers-color-scheme: dark)"
    xml2::xml_attr(link, "id") <- "css-dark"
  } else {
    xml2::xml_attr(link, "media") <- "(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
    xml2::xml_attr(link, "id") <- "css-light"
  }
}
```

This all works, but I'm wondering whether there is a better way? Sorry for the noise if asking here was a bad idea.

**Comment by cpsievert** [comment]
This seems like more of a `{htmltools}` issue than `{bslib}`? In particular, the last chunk could be avoided if https://github.com/rstudio/htmltools/issues/272 is addressed
