### ISSUE TITLE
bs5: No space between 2 side by side buttons when clicked

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/bslib#352]
1. Run the attached examples with action and bookmark buttons using bootstrap version 5
 
[106-plot-interaction-exclude.zip](https://github.com/rstudio/bslib/files/6833584/106-plot-interaction-exclude.zip)
[135-bookmark-uioutput.zip](https://github.com/rstudio/bslib/files/6833587/135-bookmark-uioutput.zip)

2. Open the app in any browser
3. 
3. Click the buttons and notice when a button is clicked, space is not maintained between itself and the second button.

<img width="1391" alt="106-plot-interaction-exclude-buttons" src="https://user-images.githubusercontent.com/5369655/126013288-b4716636-16ee-4256-9d20-1aaa14daa239.png">

<img width="1326" alt="135-BOOKMARK-UIOUTPUT-buttons" src="https://user-images.githubusercontent.com/5369655/126013296-b4d65f7c-6781-478a-b044-ac10b7a85a95.png">

**Comment by cpsievert** [comment]
This is an intentional design choice in BS4+
