### ISSUE TITLE
bs5: Windows: edge: themer-demo: Input and Well panel tab look selected at the same time

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/bslib#353]
1. Run the following themer-demo app using bootstrap version 5

```
library(shiny)
library(bslib)
library(ggplot2)
library(lattice)
library(thematic)
library(rlang)
library(curl)
library(DT)
library(knitr)
library(reactable)
theme <- bs_theme(
  version = 5,
  bg = "#202123",
  fg = "#B8BCC2",
  primary = "#EA80FC",
  secondary = "#00DAC6",
  success = "#4F9B29",
  info = "#28B3ED",
  warning = "#FD7424",
  danger = "#F7367E",
  base_font = font_google("Open Sans"),
  heading_font = font_google("Proza Libre"),
  code_font = font_google("Fira Code")
)
old_theme <- bs_global_get()
bs_global_set(theme)
onStop(function() bs_global_set(old_theme))
bslib:::as_themer_app(
  system.file("themer-demo", package = "bslib")
)
```

2. Open in Windows - edge browser (Note : I have version Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18363)

3. Go to "Inputs" or "Notifications"  tabs

4. Click on the Input panel tab, then click on well panel tab.

5. Notice that upon clicking the second tab, the accent color still stays on the first tab. Same applies to "Messages" and "Uploads & Downloads" tabs under "Notifications"
6. 
<img width="1473" alt="Windows_edge_browser_tabs_selection" src="https://user-images.githubusercontent.com/5369655/126016725-dccc0786-d7e2-4a72-bb21-90a01752c62f.png">

<img width="1479" alt="bs5_edge_browser_notifications_tabs_selection" src="https://user-images.githubusercontent.com/5369655/126016773-bfe74e45-e378-407d-8932-fb3ae6b781d8.png">

Note: I have microsoft edge on Mac and things work as expected

**Comment by cpsievert** [comment]
Bootstrap 5 isn't supporting pre-chromium versions of Edge, so let's not worry about this
