### ISSUE TITLE
support of quartz theme

### ISSUE THREAD

**Issue by markwsac** [rstudio/bslib#364]
Thanks for this useful package. It seems quartz theme of bootswatch is not supported. I am using latest version 0.2.5.1.

**Comment by cpsievert** [comment]
Quartz is a Bootswatch 5 theme. For now, you'll need the development version to use it `remotes::install_github("rstudio/bslib")`, but it'll be on CRAN soon: `bslib::bs_theme(version = 5, bootswatch = "quartz")`
