### ISSUE TITLE
`bs_page()` isn't found in docs

### ISSUE THREAD

**Issue by schloerke** [rstudio/bslib#404]
Related: https://github.com/rstudio/bslib/blob/0465860223c72706d225feed212d08514d189d4c/R/page.R#L53

**Comment by schloerke** [comment]
Also

```
Warning: Warning: Link to unknown topic in inherited text: bslib::bs_theme
```

**Comment by cpsievert** [comment]
Oh I think `@inheritParams bs_page` should actually be `@inheritParams page`

**Comment by cpsievert** [comment]
I think this has been fixed
