### ISSUE TITLE
How to add a local font with bslib

### ISSUE THREAD

**Issue by apalacio9502** [rstudio/bslib#410]
Hi there, 

I have a font in ".otf" format. Is it possible to add the font to the application?

Thanks !!!

**Comment by cpsievert** [comment]
Yes, you'll have to do something like this:

```r
library(bslib)
font = font_face(
    "Graphik", style = "normal", weight = "400",
    src = paste0("url('fonts/GraphikMedium.otf') format('otf')")
)
bs_theme(base_font = font)
``` 

and you'll also have to make the `fonts/` directory available (with Shiny, you can do that with `shiny::addResourcePath()`)
