### ISSUE TITLE
What version(s) of bootstrap are really needed

### ISSUE THREAD

**Issue by tillea** [rstudio/bslib#413]
Hi,
this issue is targeting into the same direction as the issue #412  about the fonts used in bslib.  Nilesh and I try hard to package bslib for Debian.  We did not stumbled only about the usage of binary font files with no easy to obtain source but also about the usage of three versions of bootstrap JS library ( _inst/lib/bs[345]_ ).  In Debian we always need to provide the sources of code and compressed JS is considered non-human readable binary.  For many JS libraries this is solved by linking to the Debian packaged version.  Currently we have version 3.4.1 and 4.6.0 available but as far as I can see we do not (yet) have version 5 inside the package pool and there is also a good chance that version 3 might vanish once all dependencies will be solved (no idea when and whether this will happen).  What I have never seen before that one source code is carrying three different version of the same JS project and I'm wondering whether you can explain for what purpose this is needed and how we should deal with this in a Debian package.
I see a similar situation for ( _inst/lib/bsw[345]_ ).
Any hint would be welcome.
Kind regards, Andreas.

**Comment by cpsievert** [comment]
> Currently we have version 3.4.1 and 4.6.0 available but as far as I can see we do not (yet) have version 5 inside the package pool and there is also a good chance that version 3 might vanish once all dependencies will be solved (no idea when and whether this will happen).

Shiny, R Markdown , and many of it's derivatives will likely continue to default to version 3 for the foreseeable future (for backwards compatibility reasons), so if version 3 happens to vanish, that will have wider unfortunate consequences for other packages as well.

> What I have never seen before that one source code is carrying three different version of the same JS project and I'm wondering whether you can explain for what purpose this is needed and how we should deal with this in a Debian package.

See https://github.com/rstudio/bslib/issues/412#issuecomment-1087983141 (to put it another way, different projects need different versions of Bootstrap, and it's convenient to have singular way to access and theme them). At this point, versions 3 and 4 likely won't see an update, so you'll only need to make sure you have a suitable version of version 5, and you can get that information by doing:

```r
library(bslib)
bs_theme_dependencies(bs_theme(version = 5))
```

**Comment by cpsievert** [comment]
Closing since we won't be removing any boostrap versions any time soon (and it seems you found a way to package bslib? https://ftp-master.debian.org//new/r-cran-bslib_0.3.1+dfsg-1.html)
