### ISSUE TITLE
Code folding and R Markdown source download not working

### ISSUE THREAD

**Issue by dschulz13** [rstudio/bslib#414]
## Describe the problem

When theming with bslib, there appears to be a problem with the code folding in HTML output. When setting ```code_folding: show``` in the YAML header, the "Hide" buttons are properly displayed, however, they do not work (see also the first example provided below). On the other hand, if setting ```code_folding: hide```, code is initially hidden and the "Code" buttons are displayed, but once again, they do not work (see the second example). In both cases, the global "Code" button in the top-right corner of the output document is shown, but it does not work either.

Maybe related to this is a similar problem: setting ```code_download: true``` seems to malfunction as well. Once again, the "Code" button in the top-right corner is included in the output document, but there is no reaction to clicking on it (see the third example).

In all three cases, if the lines with regard to theming (via bslib) are removed from the YAML headers, the functionalities of the buttons are restored.

## Example 1: ```code_folding: show```

````
---
title: "Bug Example 1"
date: "February 24, 2022"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    theme:
      fg: "black"
      bg: "ghostwhite"
      primary: "#7B26D1"
---

# Section 1

```{r, echo = TRUE, eval = TRUE, include = TRUE}
1 + 1
```

````

## Example 2: ```code_folding: hide```

````
---
title: "Bug Example 2"
date: "February 24, 2022"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme:
      fg: "black"
      bg: "ghostwhite"
      primary: "#7B26D1"
---

# Section 1

```{r, echo = TRUE, eval = TRUE, include = TRUE}
1 + 1
```

````

## Example 3: ```code_download: true```

````
---
title: "Bug Example 3"
date: "February 24, 2022"
output: 
  html_document:
    code_download: true
    toc: true
    toc_float: true
    theme:
      fg: "black"
      bg: "ghostwhite"
      primary: "#7B26D1"
---

# Section 1

```{r, echo = TRUE, eval = TRUE, include = TRUE}
1 + 1
```

````

### Session Info

<details>
<pre><code>
- Session info -------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       Windows 10 x64 (build 19042)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  German_Germany.1252
 ctype    German_Germany.1252
 tz       Europe/Berlin
 date     2022-02-24
 rstudio  2021.09.1+372 Ghost Orchid (desktop)
 pandoc   2.14.0.3 @ C:/Program Files/RStudio/bin/pandoc/ (via rmarkdown)

- Packages -----------------------------------------------------------------------------------------------------------
 package     * version    date (UTC) lib source
 bslib         0.3.1.9000 2022-02-13 [1] Github (rstudio/bslib@888fbe0)
 cachem        1.0.6      2021-08-19 [1] CRAN (R 4.1.2)
 callr         3.7.0      2021-04-20 [1] CRAN (R 4.1.2)
 cli           3.1.0      2021-10-27 [1] CRAN (R 4.1.2)
 crayon        1.4.2      2021-10-29 [1] CRAN (R 4.1.2)
 desc          1.4.0      2021-09-28 [1] CRAN (R 4.1.2)
 devtools      2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
 digest        0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
 ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.2)
 evaluate      0.15       2022-02-18 [1] CRAN (R 4.1.2)
 fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.1.2)
 fs            1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
 glue          1.6.0      2021-12-17 [1] CRAN (R 4.1.2)
 htmltools     0.5.2      2021-08-25 [1] CRAN (R 4.1.2)
 jquerylib     0.1.4      2021-04-26 [1] CRAN (R 4.1.2)
 jsonlite      1.7.2      2020-12-09 [1] CRAN (R 4.1.2)
 knitr         1.37       2021-12-16 [1] CRAN (R 4.1.2)
 lifecycle     1.0.1      2021-09-24 [1] CRAN (R 4.1.2)
 magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.1.2)
 memoise       2.0.1      2021-11-26 [1] CRAN (R 4.1.2)
 pkgbuild      1.3.0      2021-12-09 [1] CRAN (R 4.1.2)
 pkgload       1.2.4      2021-11-30 [1] CRAN (R 4.1.2)
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.1.2)
 processx      3.5.2      2021-04-30 [1] CRAN (R 4.1.2)
 ps            1.6.0      2021-02-28 [1] CRAN (R 4.1.2)
 purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.2)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.1.2)
 remotes       2.4.2      2021-11-30 [1] CRAN (R 4.1.2)
 rlang         0.4.12     2021-10-18 [1] CRAN (R 4.1.2)
 rmarkdown     2.11       2021-09-14 [1] CRAN (R 4.1.2)
 rprojroot     2.0.2      2020-11-15 [1] CRAN (R 4.1.2)
 rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.2)
 sass          0.4.0      2021-05-12 [1] CRAN (R 4.1.2)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
 testthat      3.1.1      2021-12-03 [1] CRAN (R 4.1.2)
 thematic      0.1.2.1    2021-06-09 [1] CRAN (R 4.1.2)
 usethis       2.1.5      2021-12-09 [1] CRAN (R 4.1.2)
 withr         2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
 xfun          0.29       2021-12-14 [1] CRAN (R 4.1.2)
 yaml          2.2.1      2020-02-01 [1] CRAN (R 4.1.1)

----------------------------------------------------------------------------------------------------------------------
</code></pre>
</details>

**Comment by cpsievert** [comment]
Thanks, just FYI, you can add `version: 4` in the meantime to get this working, but we'll eventually fix this (in `{rmarkdown}`)

**Comment by cpsievert** [comment]
Installing the development version of rmarkdown should fix this
