### ISSUE TITLE
{shinytest} recording does not work when `id` is defined in `page_navbar`

### ISSUE THREAD

**Issue by netique** [rstudio/bslib#418]
When I record a test with {shinytest} and my app uses `page_navbar` with navbar id defined, this entry is recorded in the test script:

```
app$setInputs(main_navbar = "data")
```

Subsequently, when I run the test an error appears:

```
Error in session_makeRequest(self, private, endpoint, data, params, headers) : 
  undefined is not a constructor (evaluating '(0,Pe.default)(this).tab("show")')
```
This is mitigated when I delete the `setinputs` line.

When I set `id = NULL` in `page_navbar`, there is no issue.

Maybe this issue is relevant: https://github.com/rstudio/shinytest/issues/209

### Session Info

<details>
<pre><code>
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.3 (2022-03-10)
 os       macOS Monterey 12.3
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  cs_CZ.UTF-8
 ctype    cs_CZ.UTF-8
 tz       Europe/Prague
 date     2022-04-03
 rstudio  2022.02.1+461 Prairie Trillium (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.1.0)
 base64enc     0.1-3      2015-07-28 [1] CRAN (R 4.1.0)
 brio          1.1.3      2021-11-30 [1] CRAN (R 4.1.1)
 bslib         0.3.1.9000 2022-04-03 [1] Github (rstudio/bslib@888fbe0)
 cachem        1.0.6      2021-08-19 [1] CRAN (R 4.1.1)
 callr         3.7.0      2021-04-20 [1] CRAN (R 4.1.0)
 cli           3.2.0      2022-02-14 [1] CRAN (R 4.1.1)
 crayon        1.5.1      2022-03-26 [1] CRAN (R 4.1.1)
 curl          4.3.2      2021-06-23 [1] CRAN (R 4.1.0)
 debugme       1.1.0      2017-10-22 [1] CRAN (R 4.1.0)
 desc          1.4.1      2022-03-06 [1] CRAN (R 4.1.1)
 devtools      2.4.3      2021-11-30 [1] CRAN (R 4.1.1)
 digest        0.6.29     2021-12-01 [1] CRAN (R 4.1.1)
 ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
 fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
 fs            1.5.2      2021-12-08 [1] CRAN (R 4.1.1)
 glue          1.6.2      2022-02-24 [1] CRAN (R 4.1.1)
 htmltools     0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
 httpuv        1.6.5      2022-01-05 [1] CRAN (R 4.1.1)
 httr          1.4.2      2020-07-20 [1] CRAN (R 4.1.0)
 jquerylib     0.1.4      2021-04-26 [1] CRAN (R 4.1.0)
 jsonlite      1.8.0      2022-02-22 [1] CRAN (R 4.1.1)
 later         1.3.0      2021-08-18 [1] CRAN (R 4.1.1)
 lifecycle     1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
 magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.1.1)
 memoise       2.0.1      2021-11-26 [1] CRAN (R 4.1.1)
 mime          0.12       2021-09-28 [1] CRAN (R 4.1.1)
 parsedate     1.3.0      2022-02-13 [1] CRAN (R 4.1.1)
 pingr         2.0.1      2020-06-22 [1] CRAN (R 4.1.0)
 pkgbuild      1.3.1      2021-12-20 [1] CRAN (R 4.1.1)
 pkgload       1.2.4      2021-11-30 [1] CRAN (R 4.1.1)
 png           0.1-7      2013-12-03 [1] CRAN (R 4.1.0)
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.1.0)
 processx      3.5.2      2021-04-30 [1] CRAN (R 4.1.0)
 promises      1.2.0.1    2021-02-11 [1] CRAN (R 4.1.0)
 ps            1.6.0      2021-02-28 [1] CRAN (R 4.1.0)
 purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.0)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
 Rcpp          1.0.8.3    2022-03-17 [1] CRAN (R 4.1.3)
 rematch       1.0.1      2016-04-21 [1] CRAN (R 4.1.0)
 remotes       2.4.2      2021-11-30 [1] CRAN (R 4.1.1)
 rlang         1.0.2      2022-03-04 [1] CRAN (R 4.1.1)
 rprojroot     2.0.2      2020-11-15 [1] CRAN (R 4.1.0)
 sass          0.4.1      2022-03-23 [1] CRAN (R 4.1.3)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.1)
 shiny         1.7.1      2021-10-02 [1] CRAN (R 4.1.1)
 shinytest     1.5.1      2021-09-13 [1] CRAN (R 4.1.1)
 showimage     1.0.0      2018-01-24 [1] CRAN (R 4.1.0)
 testthat      3.1.2      2022-01-20 [1] CRAN (R 4.1.1)
 usethis     * 2.1.5      2021-12-09 [1] CRAN (R 4.1.1)
 webdriver     1.0.6      2021-01-12 [1] CRAN (R 4.1.0)
 withr         2.5.0      2022-03-03 [1] CRAN (R 4.1.1)
 xtable        1.8-4      2019-04-21 [1] CRAN (R 4.1.0)

 [1] /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
</code></pre>
</details>

**Comment by cpsievert** [comment]
It's likely this is happening because your app is using Bootstrap 5 ( the development version of `bs_theme()` defaults to `version=5`), which doesn't work with shinytest, so you'll have to migrate to https://github.com/rstudio/shinytest2
