### ISSUE TITLE
Using `bslib` with `flexdashboard` disabled lazy loading of tabs

### ISSUE THREAD

**Issue by jarodmeng** [rstudio/bslib#421]
I have a shiny app with 3 tabs built using flexdashboard. When not themed, when the app starts, it only loads the first tab (which is the landing tab). The remaining two tabs are only loaded when they are navigated to. This is consistent with the general shiny pattern.

However, when I add `bs_theme()` to the flexdashboard, the loading behavior changes. Now when the app starts, all 3 tabs' code chunks are run. I noticed this because the two remaining tabs have some heavy-lifting code chunks that take a much longer time to run than the first tab. So now if I want to use `bs_theme()` on my app, I'm having a much longer start-up time.

Is this a known behavior/side-effect of using `bslib` with `flexdashboard`? If the description is not enough, I can try to create a simple reprex, but want to get the question out there first to see if others have already bumped into this.

**Comment by cpsievert** [comment]
Please do provide a minimal reprex

**Comment by cpsievert** [comment]
Closing due to lack of example
