### ISSUE TITLE
Using flexdashboard is not loading the theme settings.

### ISSUE THREAD

**Issue by apalacio9502** [rstudio/bslib#425]
Hello,

Using flexdashboard is not loading the theme settings. However if I use real-time theming and after the report is initialized I modify some parameter the theme is read.  This error started with the new version of r.

Report before modifying any parameter of the theme:

![image](https://user-images.githubusercontent.com/64808307/165999564-ee42217d-69e8-49de-aee2-61769dc46d4b.png)

Report after modifying any parameter of the theme

![image](https://user-images.githubusercontent.com/64808307/165999841-48a28874-3ee3-4867-bc80-e34bf6a533a8.png)

I see the following warning I do not know if it is related

Warning in file(con, "r") :
  file("") permite solamente open = "w+" y open = "w+b": se usó la primera opción

I am currently using r on windows:

R4.2.0
Rmarkdown 2.14
bslib 0.3.1
Flexdashboard 0.5.2

This is the sample code I used

![image](https://user-images.githubusercontent.com/64808307/166000785-08a17731-67b4-493b-abde-6fc281d751f5.png)

Regards

**Comment by cpsievert** [comment]
You currently need the dev version of flexdashboard `remotes::instal_github("rstudio/flexdashboard")`
