### ISSUE TITLE
Version 0.4 broke shinyWidgets::pickerInput()

### ISSUE THREAD

**Issue by dejan94it** [rstudio/bslib#434]
## Describe the problem

Dropdown list doesn't appear on click

**Comment by cpsievert** [comment]
Hi @dejan94it, version 0.4 of bslib intentionally changed the default Bootstrap version from 4 to 5, so it's likely that is the cause of the issue, which will have to be addressed by https://github.com/dreamRs/shinyWidgets (please open an issue there with a reproducible example and mention me)

BTW, in the meantime, you can revert to Bootstrap 4 by setting `version = 4` in `bs_theme()`
