### ISSUE TITLE
dev branch "Plot size adjustment error on full screen function"

### ISSUE THREAD

**Issue by apalacio9502** [rstudio/bslib#439]
Hello @cpsievert , when I open the plot in full screen, the plot size does not adjust to the window unless I change the window size.

![image](https://user-images.githubusercontent.com/64808307/182742357-eba7a805-7a1d-436d-b790-2551087d0d54.png)

And when I exit the full screen option the plot takes about 6 seconds to adjust to the size.

![image](https://user-images.githubusercontent.com/64808307/182742442-9ac77f3a-5bf2-4812-b348-167ada3b030d.png)

Thank you.

**Comment by cpsievert** [comment]
You currently need a special branch of shiny for the resizing to work `remotes::install_github("rstudio/shiny@resize-observer")`
