### ISSUE TITLE
Fill-based layouts not displaying properly in RStudio IDE viewer

### ISSUE THREAD

**Issue by apalacio9502** [rstudio/bslib#440]
Hello @cpsievert,

Layout is not displayed correctly in the rstudio viewer. However in the browser like chrome it is displayed correctly.

![image](https://user-images.githubusercontent.com/64808307/183121999-15b1fc00-5355-4ca2-9e6a-65f71164f731.png)

![image](https://user-images.githubusercontent.com/64808307/183122236-d88209a9-4a13-4f41-9499-b0d1d5a2ded8.png)

Regards

**Comment by cpsievert** [comment]
Thanks, would you mind sharing the information you see when going to `RStudio -> About RStudio`

**Comment by apalacio9502** [comment]
Hello @cpsievert,

This is the version information of the RStudio:

```
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

Regards

**Comment by apalacio9502** [comment]
The same problem occurs when testing on a mac computer

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

**Comment by cpsievert** [comment]
FWIW, things seem to work OK with the [daily build of RStudio](https://dailies.rstudio.com/). I'm not 100% sure why this is the case, but it seems like it's related to the IDE switching from QtWebEngine to Electron for the browsing engine (and QtWebEngine not supporting CSS Grid). If that's indeed the case, I don't think there's anything actionable here (other than to use the development of the IDE until a new stable release comes out)
