### ISSUE TITLE
dev branch "unexpected white border on nav"

### ISSUE THREAD

**Issue by apalacio9502** [rstudio/bslib#441]
Hey @cpsievert , 

When adding a new tab to a navbar via the nav_insert function with the `select` atribute in TRUE,  the nav appears to have a white border. This is not happening with the Shiny and Bslib master branch with the appendTab function.

```
ui <- page_navbar(
  id = "test",
  title = "test",
  nav(title = "nav_1")
)

server <- function(input, output) {
  nav_insert(id = "test", nav = nav(title = "nav_2"), select = TRUE)
}

shinyApp(ui = ui, server = server)

```

![image](https://user-images.githubusercontent.com/64808307/183124314-54811656-684b-4520-b5e8-dba8b05f66ac.png)

Regards

**Comment by cpsievert** [comment]
Can confirm the outline doesn't appear with Bootstrap 4, but does with Bootstrap 5 (but this isn't specific to the `dev` branch, I replicate this on `main`). That said, I think you could argue the new behavior is better/more accessible (if you bring keyboard focus the navbar you get the same `:focus-visible` styling, which improves accessibility)

```r
ui <- page_navbar(
    id = "test",
    title = "test", 
    theme = bslib::bs_theme(version = 4),
    nav(title = "nav_1")
)

server <- function(input, output) {
    nav_insert(id = "test", nav = nav(title = "nav_2"), select = TRUE)
}

shinyApp(ui = ui, server = server)
```
