### ISSUE TITLE
dev branch "Plot height adjustment error in full screen function"

### ISSUE THREAD

**Issue by apalacio9502** [rstudio/bslib#442]
Hello @cpsievert,

Testing the new functionality of the cards in full screen I found the following two problems:

1. The minimum height of the plot in full screen is given by the height parameter of the card function. I think there should not be a minimum height.
2. The minimum height of the plot is updated every time the size of the window becomes higher. That generates that if later the height of the window is reduced the plot is not adjusted to the new size. 

- Full screen is activated and the plot height is adjusted correctly.
![image](https://user-images.githubusercontent.com/64808307/183275378-bb439b2d-0eb8-406c-8b3c-b705ba31986c.png)

- The window height is increased and the plot height is adjusted correctly.
![image](https://user-images.githubusercontent.com/64808307/183275430-dd075de7-7ea8-4f47-b5ee-d805bf30cbc2.png)

- The window height is reduced and plot height does not adjust correctly
![image](https://user-images.githubusercontent.com/64808307/183275437-6295bde4-ff02-4993-9fe9-b1d35c099f92.png)

Regards

**Comment by apalacio9502** [comment]
Hi @cpsievert,

With the last modifications of [shiny](https://github.com/rstudio/shiny/commit/f9c0d4691009049cf8f24735ee1618369c9e8ee8) and [bslib](https://github.com/rstudio/bslib/commit/6f0ed4d3911f99b5dff8401e93143725709e0823) this problem was solved. However I see the following.
 

- When using the card_body() in fullscreen with a plotly plot the minimum height of the plot is bounded by the height defined in the function card().  In my opinion it should not be bounded in full screen. If navs_tab_card() is used the above problem does not occur.
- When using the card_body_output() in fullscreen instead of card_body() this problem does not happen. If the solution is to use the card_body_output() it should be clarified in the library documentation when it is released to production.
- When using card_body() and navs_tab_card() in fullscreen and the screen height is changed sometimes it does not update the plotly plot height correctly. However using the card_body_output() function always updates it correctly and the adjustment is faster. However there is no equivalent function for the navs_tab_card().

Regards

**Comment by cpsievert** [comment]
@apalacio9502 I just pushed some changes to `dev` that remove the dependence on resize-observer. It'd be awesome if you could update/re-test the issues you've filed thus far using the CRAN version of shiny and close any that don't appear to be an issue anymore

**Comment by apalacio9502** [comment]
@cpsievert Thank youI close this issue in favor of   https://github.com/rstudio/bslib/issues/450
