### ISSUE TITLE
dev branch "Error adjusting the width of the plots when exiting the full screen function"

### ISSUE THREAD

**Issue by apalacio9502** [rstudio/bslib#443]
Hi @cpsievert,

With the latest modifications to rstudio/shiny@resize-observer (https://github.com/rstudio/shiny/commit/fbe9d247d493c3dd33de82e6c7320c0030415aa2) and rstudio/bslib@dev (https://github.com/rstudio/bslib/commit/65b2b51f6effdbb2d49a0ee53dc2ee7dd413a5cd). Two problems started to happen that didn't happen before:

- When a card is put into fullscreen and then exited from fullscreen, the plot width of that card stops fitting the width of the screen. For example if I enlarge or reduce the screen width the plot width is the same as before going full screen.
![Imagen1](https://user-images.githubusercontent.com/64808307/183533199-c4d8a916-30bb-4bc1-8623-c94889bdedc5.png)

- When a card is put in full screen it takes from 1 to 3 seconds to recalculate the plot size when the stretch parameter = TRUE, the same happens when leaving full screen.

https://user-images.githubusercontent.com/64808307/183533231-8755fb36-2670-4ba0-85a7-b9f279b31a2e.mp4

Regards

**Comment by robayo** [comment]
Hello everyone, 
I've tried a different Shiny application using the dev branch and I've experience this same behaviour. When a tab is selected too quickly in a tab panel and I go back to another tab with a graph on it, the graph is not rendered in all the space available but in like half of it. 
I would appreciate if someone looked into this. 
:)

**Comment by robayo** [comment]
Hello everyone,
I've tried a different Shiny application using the dev branch and I've experience this same behaviour. When a window is taken to full screen and then resized down and then scaled up the graphs do not render in all the space available but in like half of it.
I would appreciate if someone looked into this.
:)

**Comment by apalacio9502** [comment]
Hi @cpsievert,

With the latest update of rstudio rstudio/bslib@dev (https://github.com/rstudio/bslib/commit/612fb44d685f5b116a40fc75ed23c75cbe68ded2) the original problem appears to be solved. The plots now use all the space reserved to them. Nevertheless, I noted that when the plot is displayed fullscreen and then resized back the speed of resizing improved compared to before the plot was displayed on fullscreen. It would be good to understand this change in behaviour to force it from the beggining of the rendering of the plot.

https://user-images.githubusercontent.com/64808307/183755834-07ccaff8-000f-44d8-a334-253fa8e507b9.MOV

Now, besides that, the plot when exiting fullscreen takes too much time to being resized on the original space. That still hasn't been solved.

Regards.

**Comment by cpsievert** [comment]
Thanks, I think this should be fixed now?

**Comment by apalacio9502** [comment]
Testing I see that this problem was already fixed with the last modifications. However since this commit (612fb44d685f5b116a40fc75ed23c75cbe68ded2) this problem started to happend https://github.com/rstudio/bslib/issues/444
