### ISSUE TITLE
dev branch "Error in the scroll of the page when leaving the full screen of the card function"

### ISSUE THREAD

**Issue by apalacio9502** [rstudio/bslib#444]
Hi @cpsievert,

I have identified the following error when leaving the full screen.

If the layout has two rows, the first row has two or more cards and the second row has one card. When leaving the full screen of the card of the second row the scroll of the page stops working (it remains stuck at the top of the screen). The behavior is the same if I change the order of the rows. 

https://user-images.githubusercontent.com/64808307/183818183-113f6c86-190c-4209-b293-62f01ade2c78.mp4

But if you add a third row with only one card, no error occurs. Or if you add only one card per row, it doesn't happen either. 

https://user-images.githubusercontent.com/64808307/183818040-8e936d68-84b8-4fa6-ad88-3ad63614101c.mp4

Regards

```
library(shiny)
library(bslib)
library(plotly)

ui <- page_navbar(
  title = "Test", theme = bs_theme(),fluid = TRUE,
  nav("Test",
      fluidRow(
        column(4,
               card(card_header("Plot 1"),
                    full_screen = TRUE,
                    card_body(plotlyOutput("plot_1", height = "100%"), stretch = TRUE)
               )),
        column(4,
               card(card_header("Plot 2"),
                    full_screen = TRUE,
                    card_body(plotlyOutput("plot_2", height = "100%"), stretch = TRUE)
               )),
        column(4,
               card(card_header("Plot 3"),
                    full_screen = TRUE,
                    card_body(plotlyOutput("plot_3", height = "100%"), stretch = TRUE)
               )),
        column(12,
               card(card_header("Plot 4"),
                    full_screen = TRUE,
                    card_body(plotlyOutput("plot_4", height = "100%"), stretch = TRUE)
               ))
        
      )
      
  )
)


server <- function(input, output) {
  
  output$plot_1 <- renderPlotly({
    fig <- plot_ly(
      x = c("giraffes", "orangutans", "monkeys"),
      y = c(20, 14, 23),
      name = "SF Zoo",
      type = "bar"
    )
  })
  
  output$plot_2 <- renderPlotly({
    fig <- plot_ly(
      x = c("giraffes", "orangutans", "monkeys"),
      y = c(20, 14, 23),
      name = "SF Zoo",
      type = "bar"
    )
  })
  
  output$plot_3 <- renderPlotly({
    fig <- plot_ly(
      x = c("giraffes", "orangutans", "monkeys"),
      y = c(20, 14, 23),
      name = "SF Zoo",
      type = "bar"
    )
  })
  
  output$plot_4 <- renderPlotly({
    fig <- plot_ly(
      x = c("giraffes", "orangutans", "monkeys"),
      y = c(20, 14, 23),
      name = "SF Zoo",
      type = "bar"
    )
  })
  
}

shinyApp(ui = ui, server = server)

**Comment by apalacio9502** [comment]
I was doing more tests and I found that the error only happens if the size of the window (if the height and width are greater than 695px).

https://user-images.githubusercontent.com/64808307/183994523-3c14ac98-f482-4d7a-bbfc-9ed676571e2f.mp4

**Comment by apalacio9502** [comment]
I think the cause is a loop. After exiting the full screen the next function of card-full-screen.js is still running even though the screen size has not been changed.

```
  b.onResize = function() {
      let size = { w: el.offsetWidth, h: el.offsetHeight };

      if (!elCard.hasClass("bslib-full-screen")) {
        size = inferSize(el, elCard);
      }

      if (size.w === 0 && size.h === 0) return;
      if (size.w === lastSize.w && size.h === lastSize.h) return;

      lastSize = size;
      b.binding.resize(el, size.w, size.h);
    };

**Comment by apalacio9502** [comment]
Hi @cpsievert,

With the last modifications of [shiny](https://github.com/rstudio/shiny/commit/f9c0d4691009049cf8f24735ee1618369c9e8ee8) and [bslib](https://github.com/rstudio/bslib/commit/6f0ed4d3911f99b5dff8401e93143725709e0823) this problem is partially solved. 

I see the following behavior:

- It happens without having executed the full screen function.
- It happens regardless of the number of cards per row. 
- It only happens if the height of the window is less than 700px and if the height is not defined in the card() function.

Looking at the last modifications I see that now for plotly outputs the function card_body_output() works. However when using this function the same problem happens unless the height is defined in the card() function.

https://user-images.githubusercontent.com/64808307/184467127-7738e5bd-2f3e-4d13-8608-e1db76a4d331.mp4

Regards

**Comment by robayo** [comment]
Hello Everyone,
The weird behavour when trying to get to the bottom of the page is maybe related to the assumed width that each panel has. If the width is 100% then maybe the panel assumes the width is 0 and tries to bounce as if the page had ended. The error dissapears when adding an explicit width size to the panel.
@cpsievert

**Comment by apalacio9502** [comment]
Hello,

With the last modifications made in the resize-observer branch of Shiny, the problem was solved. 

Regards
