### ISSUE TITLE
value_box has stray scrollbar on my Linux box

### ISSUE THREAD

**Issue by jcheng5** [rstudio/bslib#457]
This is a screenshot of https://rstudio.github.io/bslib/articles/value-boxes.html:

![image](https://user-images.githubusercontent.com/129551/198207532-520d44aa-5924-4bd3-8e51-450894986d2d.png)

I'm on Chrome on Ubuntu, on a 4K screen.

It seems to be the `overflow: auto` rules we added to `.html-fill-container` and `.html-fill-container > .html-fill-item` that's causing this. Adding an inline style with `overflow: hidden` to the `.value-box-showcase` element fixes it (I didn't try it with a legit CSS rule).

**Comment by cpsievert** [comment]
Do you see similar scrollbars on https://testing-apps.shinyapps.io/card/ ?

**Comment by jcheng5** [comment]
I haven't checked that URL on Linux yet but I see a bunch of scrollbars on Mac after growing/shrinking the window:

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/129551/198339673-ae1a3c6f-d605-44c9-a085-cdcd8bf29bb8.png">

**Comment by cpsievert** [comment]
Whoops, I think it's because that deployment doesn't have the dev version of shiny/htmlwidgets. https://github.com/rstudio/bslib/commit/0fc418a7a4022a89dc6cecae7a350bfa4948317f should fix that

**Comment by cpsievert** [comment]
This is still happening (need to set "Always" show scrolls bars on MacOS) to repro
