### ISSUE TITLE
`bslib::bs_theme_dependencies` bootstrap version 4 conflicts with shiny navbar id

### ISSUE THREAD

**Issue by zac-garland-mc** [rstudio/bslib#462]
I'm unable to install the latest dev version as I'm running off of a rstudio workbench deployment, but wanted to share a bug that I saw. 

```
fun_ui <- function() {
  shiny::tagList(
    shiny::tagList(
      bslib::bs_theme_dependencies(theme = NULL),
    ),
    shiny::navbarPage(
      title = "hello",
      id = "navbar",
      tabPanel("test")

    ))
}

fun_server <- function(input,output,session){
  observe({
    req(input$navbar)
    message(input$navbar)
  })
}

shinyApp(fun_ui(),fun_server)
```

There seems to be a conflict with `bslib::bs_theme_dependencies(theme=NULL)[[2]]` and shiny's navbarpage id. 

Given that our package repositories update quarterly, any advice on short term solves would be appreciated as the majority of our UI has transitioned over to bslib. Appreciate the help in advance!

shiny_1.7.1 bslib_0.3.1

**Comment by zac-garland-mc** [comment]
Looking a bit more into this, I believe I'm able to resolve this by transitioning over to bslib fully for this. 

Are there permanent plans to use bslib components in replacement of shiny components? Or is there a conversion occuring for utilizing bslib components within shiny naming conventions?

``` 
fun_ui <- function() {
  shiny::tagList(
    shiny::tagList(
      bslib::bs_theme_dependencies(theme = NULL),
    ),
    bslib::page_navbar(
      title = "hello",
      id = "navbar",
      bslib::nav("test"),
      bslib::nav("test2")

    ))
}

fun_server <- function(input,output,session){
  observe({
    req(input$navbar)
    message(input$navbar)
  })
}

shinyApp(fun_ui(),fun_server)
```

**Comment by cpsievert** [comment]
The "correct" way to use `{bslib}` with `shiny::navbarPage()` is like this:

```r
shiny::navbarPage(theme = bslib::bs_theme(), ...)
```

which is equivalent to

```r
bslib::page_navbar(...)
```

(BTW, you shouldn't ever need to explicitly call `bslib::bs_theme_dependencies()` in a Shiny app. It only exists for non-Shiny/RMarkdown usage)


> Are there permanent plans to use bslib components in replacement of shiny components? Or is there a conversion occuring for utilizing bslib components within shiny naming conventions?

In the places in makes sense to, we'll likely be replacing (or improving upon) existing Shiny UI functions in `{bslib}` going forward.

**Comment by zac-garland-mc** [comment]
thank you @cpsievert! there were a few small css overrides that we had in place which led to the dependencies usage vs. theme but I do see that this usage resolves the above. Appreciate the quick response!
