### ISSUE TITLE
`accordion()` + `accordion_item()` missing from bslib

### ISSUE THREAD

**Issue by mrworthington** [rstudio/bslib#464]
Hi Carson,

Have been using the versions demo'd at RStudio Conference for the past few months and noticed after updating that the `accordion()` and `accordion_item()` functions are now gone. Those two, along with everything else in [the demo](https://github.com/rstudio/bslib/blob/df1ccbc08d6f356daba947499df3b1c8127e2568/inst/examples/demo/app.R), were working really well  until I just updated today. They were really great! Have they been removed from the new version of bslib?

Thanks!

**Comment by cpsievert** [comment]
Accordions have only ever been made available through the (highly experimental) dev branch, but I'm hoping to get them on the main branch soon

**Comment by mrworthington** [comment]
Totally understand. After the demo at RStudio::conf, I guess I assumed they were part of the rollout plan (even if still in Dev). That said, I'd been trying them out in different apps and they were great for organizing inputs. [Here's an example](http://mattworthington.shinyapps.io/dvisd_test).
