### ISSUE TITLE
Initial view of showcase plot not preserved after closing full screen mode

### ISSUE THREAD

**Issue by rpodcast** [rstudio/bslib#465]
I'm really enjoying the full-screen functionality of the new `value_box` function! One small quirk I noticed is that when the app initializes, the plot that's supplied in the `showcase` parameter has a nice layout that gives an accurate view. If I expand to full screen and then exit back to the normal view, the plot view looks zoomed in at odd places. I verified this behavior occurs for both `{plotly}` and `{ggplot2}` produced visualizations.

Example screenshots below

App initialization:

![image](https://user-images.githubusercontent.com/1043111/202859846-a699a42a-cf12-4908-beb9-4cd160b9c5ab.png)

After closing full screen mode

![image](https://user-images.githubusercontent.com/1043111/202859888-b222a9d1-bdc5-492b-b618-ad95ab5e4c57.png)

I am using the latest version of `bslib` from the GH repo. Code is the same as the example app for value boxes in this repo with an additional row that contains a `ggplot` showcase plot.

```r
library(shiny)
library(bslib)
library(bsicons)
library(plotly)
library(ggplot2)

ui <- page_fluid(
  theme = bslib::bs_theme(
    base_font = font_google("Atkinson Hyperlegible")
  ),
  br(),
  layout_column_wrap(
    width = "200px",
    class = "mt-3",
    value_box(
      title = "Unemployment Rate",
      value = "2.7%",
      p("Started at 1.5%"),
      p("Averaging 3%"),
      p("Peaked at 5.2% in Dec 1982"),
      showcase = plotlyOutput("unemploy"),
      full_screen = TRUE
    ),
    value_box(
      title = "Personal Savings Rate",
      value = "7.6%",
      p("Started at 12.6%"),
      p("Averaging 8.6%"),
      p("Peaked at 17.3% in May 1975"),
      showcase = plotlyOutput("psavert"),
      showcase_layout = showcase_top_right(),
      full_screen = TRUE,
      theme_color = "success"
    ),
    value_box(
      title = "Personal Consumption",
      value = "$3.8B",
      p("Started at $0.25B"),
      p("Averaging $1.7B"),
      showcase = bsicons::bs_icon("piggy-bank", size = "100%"),
      full_screen = TRUE,
      theme_color = "danger"
    )
  ),
  br(),
  layout_column_wrap(
    width = "200px",
    class = "mt-3",
    value_box(
      title = "Unemployment Rate",
      value = "2.7%",
      p("Started at 1.5%"),
      p("Averaging 3%"),
      p("Peaked at 5.2% in Dec 1982"),
      showcase = plotOutput("unemploy_ggplot"),
      full_screen = TRUE
    ),
    value_box(
      title = "Personal Consumption",
      value = "$3.8B",
      p("Started at $0.25B"),
      p("Averaging $1.7B"),
      showcase = bsicons::bs_icon("piggy-bank", size = "100%"),
      full_screen = TRUE,
      theme_color = "danger"
    ),
    value_box(
      title = "Personal Consumption",
      value = "$3.8B",
      p("Started at $0.25B"),
      p("Averaging $1.7B"),
      showcase = bsicons::bs_icon("piggy-bank", size = "100%"),
      full_screen = TRUE,
      theme_color = "danger"
    )
  )
)

server <- function(input, output) {

  output$unemploy <- renderPlotly({
    plotly_time_series(
      economics, x = ~date, y = ~100 * unemploy / pop
    )
  })
  
  output$unemploy_ggplot <- renderPlot({
    ggplot(data = economics, aes(x = date, y = (100 * unemploy / pop))) +
      geom_line()
  })

  output$psavert <- renderPlotly({
    plotly_time_series(
      economics, x = ~date, y = ~psavert
    )
  })

  output$pce <- renderPlotly({
    plotly_time_series(
      economics, x = ~date, y = ~ 100 * pce / pop
    )
  })

  plotly_time_series <- function(d, x, y) {
    info <- getCurrentOutputInfo()
    large <- isTRUE(info$height() > 200)

    plot_ly(d, x = x, y = y) %>%
      add_lines(
        color = I(info$fg()),
        span = I(1),
        #hoverinfo = if (!large) "none",
        fill = 'tozeroy',
        alpha = 0.2
      ) %>%
      layout(
        hovermode = "x",
        margin = list(t = 0, r = 0, l = 0, b = 0),
        font = list(color = info$fg()),
        paper_bgcolor = "transparent",
        plot_bgcolor = "transparent",
        xaxis = list(
          title = "",
          visible = large,
          showgrid = FALSE
        ),
        yaxis = list(
          title = "",
          visible = large,
          showgrid = FALSE
        )
      ) %>%
      config(displayModeBar = FALSE)
  }
}

shinyApp(ui, server)

```

### Session Info

<details>
<pre><code>
─ Session info ─────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22)
 os       Ubuntu 20.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2022-11-19
 rstudio  2022.02.1+461 Prairie Trillium (server)
 pandoc   2.17.1.1 @ /usr/local/bin/pandoc

─ Packages ─────────────────────────────────────────────────────────────────────────────────────
 ! package     * version    date (UTC) lib source
 P cachem        1.0.6      2021-08-19 [?] RSPM (R 4.2.0)
 P callr         3.7.0      2021-04-20 [?] RSPM (R 4.2.0)
 P cli           3.4.1      2022-09-23 [?] RSPM (R 4.2.0)
 P crayon        1.5.1      2022-03-26 [?] RSPM (R 4.2.0)
 P devtools      2.4.5      2022-10-11 [?] RSPM (R 4.2.0)
 P digest        0.6.29     2021-12-01 [?] RSPM (R 4.2.0)
 P ellipsis      0.3.2      2021-04-29 [?] RSPM (R 4.2.0)
 P fastmap       1.1.0      2021-01-25 [?] RSPM (R 4.2.0)
 P fs            1.5.2      2021-12-08 [?] RSPM (R 4.2.0)
 P glue          1.6.2      2022-02-24 [?] RSPM (R 4.2.0)
 P htmltools     0.5.3.9002 2022-11-18 [?] Github (rstudio/htmltools@39b3f1f)
 P htmlwidgets   1.5.4      2021-09-08 [?] RSPM (R 4.2.0)
 P httpuv        1.6.5      2022-01-05 [?] RSPM (R 4.2.0)
 P later         1.3.0      2021-08-18 [?] RSPM (R 4.2.0)
 P lifecycle     1.0.1      2021-09-24 [?] RSPM (R 4.2.0)
 P magrittr      2.0.3      2022-03-30 [?] RSPM (R 4.2.0)
 P memoise       2.0.1      2021-11-26 [?] RSPM (R 4.2.0)
 P mime          0.12       2021-09-28 [?] RSPM (R 4.2.0)
 P miniUI        0.1.1.1    2018-05-18 [?] RSPM (R 4.2.0)
 P pkgbuild      1.3.1      2021-12-20 [?] RSPM (R 4.2.0)
 P pkgload       1.3.2      2022-11-16 [?] RSPM (R 4.2.0)
 P prettyunits   1.1.1      2020-01-24 [?] RSPM (R 4.2.0)
 P processx      3.5.3      2022-03-25 [?] RSPM (R 4.2.0)
 P profvis       0.3.7      2020-11-02 [?] RSPM (R 4.2.0)
 P promises      1.2.0.1    2021-02-11 [?] RSPM (R 4.2.0)
 P ps            1.7.0      2022-04-23 [?] RSPM (R 4.2.0)
 P purrr         0.3.4      2020-04-17 [?] RSPM (R 4.2.0)
 P R6            2.5.1      2021-08-19 [?] RSPM (R 4.2.0)
 P Rcpp          1.0.8.3    2022-03-17 [?] RSPM (R 4.2.0)
 P remotes       2.4.2      2021-11-30 [?] RSPM (R 4.2.0)
   renv          0.15.4     2022-03-03 [1] RSPM (R 4.2.0)
 P rlang         1.0.6      2022-09-24 [?] RSPM (R 4.2.0)
 P rstudioapi    0.13       2020-11-12 [?] RSPM (R 4.2.0)
 P sessioninfo   1.2.2      2021-12-06 [?] RSPM (R 4.2.0)
 P shiny         1.7.1      2021-10-02 [?] RSPM (R 4.2.0)
 P stringi       1.7.6      2021-11-29 [?] RSPM (R 4.2.0)
 P stringr       1.4.0      2019-02-10 [?] RSPM (R 4.2.0)
 P urlchecker    1.0.1      2021-11-30 [?] RSPM (R 4.2.0)
 P usethis       2.1.6      2022-05-25 [?] RSPM (R 4.2.0)
 P xtable        1.8-4      2019-04-21 [?] RSPM (R 4.2.0)

 [1] /home/eric/shinydevseries_projects/shiny-prod-apps/renv/library/R-4.2/x86_64-pc-linux-gnu
 [2] /usr/local/lib/R/library

 P ── Loaded and on-disk path mismatch.
</code></pre>
</details>

**Comment by cpsievert** [comment]
You also need the development version of htmlwidgets.

**Comment by rpodcast** [comment]
Awesome, the `{plotly}` versions of the showcase plots now get their default views back. The issue still persists with `{ggplot}` produced showcase plots. However I would most likely put an htmlwidget (plotly, echarts4r, etc)  in those showcase views, so it's not a big concern to me. 

I'd recommend adding a note in the [value boxes vignette](https://rstudio.github.io/bslib/articles/value-boxes.html) about having the dev version of `{htmlwidgets}` installed.

**Comment by cpsievert** [comment]
You also need the dev version of shiny :)

I think that `remotes::install_github('rstudio/bslib')` should at least prompt you to install these and you should be getting a warning message about updating?
