### ISSUE TITLE
Add `nav_panel()` alias for `nav()` and `navset_*()` aliases for `navs_*()`

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#476]
And promote use of `nav_panel()` over `nav()`. The former is more consistent with `tabPanel()` and the upcoming `accordion_panel()`.

**Comment by cpsievert** [comment]
At the same time, let's consider renaming `page_navbar()`'s  `fillable` to `fillable_panel`.

**Comment by gadenbuie** [comment]
Linked PR: https://github.com/rstudio/bslib/pull/546

**Comment by cpsievert** [comment]
Closed by #546
