### ISSUE TITLE
Update card() article to use page_fluid()

### ISSUE THREAD

**Issue by ismirsehregal** [rstudio/bslib#486]
I am trying to combine the examples given [here](https://rstudio.github.io/bslib/articles/cards.html#responsive-sizing) and [here](https://rstudio.github.io/bslib/articles/cards.html#dynamic-rendering-shiny).

Not sure if I'm doing something wrong but the following results in a broken layout of the `card()` - new "close" buttons appear for each "expand" click:

```r
library(shiny)
library(bslib)
library(plotly)

plotly_widget <- plot_ly(x = diamonds$cut) %>%
  config(displayModeBar = FALSE) %>%
  layout(margin = list(t = 0, b = 0, l = 0, r = 0))

ui <- fluidPage(
  card(
    height = 250, full_screen = TRUE,
    card_header("Responsive sizing"),
    card_body_fill(plotlyOutput("plot_id")),
    card_footer(
      class = "fs-6",
      "card footer"
    )
  )
)

server <- function(input, output, session) {
  output$plot_id <- renderPlotly({plotly_widget})
}

shinyApp(ui, server)
```
![image](https://user-images.githubusercontent.com/36849480/220572935-647a830d-b486-4890-bb2f-f026b381b7f8.png)

---

Outside of shiny everything works as expected:

```r
card(
  height = 250, full_screen = TRUE,
  card_header("Responsive sizing"),
  card_body_fill(plotly_widget),
  card_footer(
    class = "fs-6",
    "card footer"
  )
)
```
![image](https://user-images.githubusercontent.com/36849480/220572026-96359458-861f-4312-b998-075154e08afd.png)

### Session Info

<details>
<pre><code>
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  German_Germany.utf8
 ctype    German_Germany.utf8
 tz       Europe/Berlin
 date     2023-02-22
 rstudio  2022.12.0+353 Elsbeth Geranium (desktop)
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 bslib       * 0.4.2.9000 2023-02-22 [1] Github (rstudio/bslib@fe41d6d)
 cachem        1.0.6      2021-08-19 [1] CRAN (R 4.2.2)
 callr         3.7.3      2022-11-02 [1] CRAN (R 4.2.2)
 cli           3.6.0      2023-01-09 [1] CRAN (R 4.2.2)
 colorspace    2.1-0      2023-01-23 [1] CRAN (R 4.2.2)
 crayon        1.5.2      2022-09-29 [1] CRAN (R 4.2.2)
 crosstalk     1.2.0      2021-11-04 [1] CRAN (R 4.2.2)
 data.table    1.14.6     2022-11-16 [1] CRAN (R 4.2.2)
 devtools      2.4.5      2022-10-11 [1] CRAN (R 4.2.2)
 digest        0.6.31     2022-12-11 [1] CRAN (R 4.2.2)
 dplyr         1.1.0      2023-01-29 [1] CRAN (R 4.2.2)
 ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.2.2)
 fansi         1.0.4      2023-01-22 [1] CRAN (R 4.2.2)
 fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.2.2)
 fs            1.6.1      2023-02-06 [1] CRAN (R 4.2.2)
 generics      0.1.3      2022-07-05 [1] CRAN (R 4.2.2)
 ggplot2     * 3.4.1      2023-02-10 [1] CRAN (R 4.2.2)
 glue          1.6.2      2022-02-24 [1] CRAN (R 4.2.2)
 gtable        0.3.1      2022-09-01 [1] CRAN (R 4.2.2)
 htmltools     0.5.4      2022-12-07 [1] CRAN (R 4.2.2)
 htmlwidgets   1.6.1      2023-01-07 [1] CRAN (R 4.2.2)
 httpuv        1.6.9      2023-02-14 [1] CRAN (R 4.2.2)
 httr          1.4.4      2022-08-17 [1] CRAN (R 4.2.2)
 jquerylib     0.1.4      2021-04-26 [1] CRAN (R 4.2.2)
 jsonlite      1.8.4      2022-12-06 [1] CRAN (R 4.2.2)
 later         1.3.0      2021-08-18 [1] CRAN (R 4.2.2)
 lazyeval      0.2.2      2019-03-15 [1] CRAN (R 4.2.2)
 lifecycle     1.0.3      2022-10-07 [1] CRAN (R 4.2.2)
 magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.2.2)
 memoise       2.0.1      2021-11-26 [1] CRAN (R 4.2.2)
 mime          0.12       2021-09-28 [1] CRAN (R 4.2.0)
 miniUI        0.1.1.1    2018-05-18 [1] CRAN (R 4.2.2)
 munsell       0.5.0      2018-06-12 [1] CRAN (R 4.2.2)
 pillar        1.8.1      2022-08-19 [1] CRAN (R 4.2.2)
 pkgbuild      1.4.0      2022-11-27 [1] CRAN (R 4.2.2)
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.2.2)
 pkgload       1.3.2      2022-11-16 [1] CRAN (R 4.2.2)
 plotly      * 4.10.1     2022-11-07 [1] CRAN (R 4.2.2)
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.2.2)
 processx      3.8.0      2022-10-26 [1] CRAN (R 4.2.2)
 profvis       0.3.7      2020-11-02 [1] CRAN (R 4.2.2)
 promises      1.2.0.1    2021-02-11 [1] CRAN (R 4.2.2)
 ps            1.7.2      2022-10-26 [1] CRAN (R 4.2.2)
 purrr         1.0.1      2023-01-10 [1] CRAN (R 4.2.2)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.2.2)
 Rcpp          1.0.10     2023-01-22 [1] CRAN (R 4.2.2)
 remotes       2.4.2      2021-11-30 [1] CRAN (R 4.2.2)
 rlang         1.0.6      2022-09-24 [1] CRAN (R 4.2.2)
 rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.2.2)
 sass          0.4.5      2023-01-24 [1] CRAN (R 4.2.2)
 scales        1.2.1      2022-08-20 [1] CRAN (R 4.2.2)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.2.2)
 shiny       * 1.7.4      2022-12-15 [1] CRAN (R 4.2.2)
 stringi       1.7.12     2023-01-11 [1] CRAN (R 4.2.2)
 stringr       1.5.0      2022-12-02 [1] CRAN (R 4.2.2)
 tibble        3.1.8      2022-07-22 [1] CRAN (R 4.2.2)
 tidyr         1.3.0      2023-01-24 [1] CRAN (R 4.2.2)
 tidyselect    1.2.0      2022-10-10 [1] CRAN (R 4.2.2)
 urlchecker    1.0.1      2021-11-30 [1] CRAN (R 4.2.2)
 usethis       2.1.6      2022-05-25 [1] CRAN (R 4.2.2)
 utf8          1.2.3      2023-01-31 [1] CRAN (R 4.2.2)
 vctrs         0.5.2      2023-01-23 [1] CRAN (R 4.2.2)
 viridisLite   0.4.1      2022-08-22 [1] CRAN (R 4.2.2)
 withr         2.5.0      2022-03-03 [1] CRAN (R 4.2.2)
 xtable        1.8-4      2019-04-21 [1] CRAN (R 4.2.2)
 yaml          2.3.7      2023-01-23 [1] CRAN (R 4.2.2)
</code></pre>
</details>

**Comment by cpsievert** [comment]
Change `fluidPage` to `page_fluid` (`card()` requires Bootstrap 5)

**Comment by ismirsehregal** [comment]
Thanks! It might be helpful for future readers to update the [example](https://rstudio.github.io/bslib/articles/cards.html#dynamic-rendering-shiny) accordingly (fully working shiny app). Cheers

**Comment by cpsievert** [comment]
Oh, good point, I'll re-open so we remember to update that example

**Comment by cpsievert** [comment]
Done in #487
