### ISSUE TITLE
Stationary column names in scrollable `card_body_fill(tableOutput("table"))`

### ISSUE THREAD

**Issue by asadow** [rstudio/bslib#499]
I'm having a blast using cards and one feature that would add firepower is allowing static column names in a scrollable `card_body_fill(tableOutput("table"))`.  

This would allow the user to scroll through a table and still see the column names. This could likewise be implemented for row-names (static row names when scrolling sideways).

**Comment by cpsievert** [comment]
I recommend using `{DT}` for this sort of thing, but at least currently, you need to know to also set `fillContainer = TRUE` in `DT::datatable()` for it to fill properly

```r
library(shiny)

ui <- page_fluid(
  card(
    full_screen = TRUE,
    card_header("A table"),
    card_body_fill(
      DT::dataTableOutput("table")
    )
  )
)

server <- function(input, output, session) {
  output$table <- DT::renderDataTable({
    DT::datatable(mtcars, fillContainer = TRUE)
  })
}

shinyApp(ui, server)
```

**Comment by cpsievert** [comment]
Oh, and also, when using something like `shiny::tableOutput()` or `{gt}` (i.e., you want a table with a fixed height) you probably just want `card_body()` (not `card_body_fill()`) to guarantee that the table will be scrollable.

That said, I'm sure there are ways, especially with `{gt}`, to make just the rows (not column names) scrollable (with some CSS hackery), but that's not really `{bslib}`'s responsibility, so I'll be closing this issue
