### ISSUE TITLE
sidebar() improvements

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#500]
- [x] `sidebar()` should gain a `max_height_mobile` that defaults to something like `200px` or `50%`.
- [x] Maybe `sidebar()` should default to a collapsed state on mobile?
- [ ] Maybe export a `sidebar_toggle(open = c(NA, T, F))` instead of `sidebar_open()`/`sidebar_close()` that would "do the right thing" by default.
- [x] Maybe `layout_sidebar()`'s `border`/`border_radius` should default to `NULL` instead of `TRUE`.
- [x] Maybe `sidebar()` should gain a `title`, which when it's a string, would do something like `tagList(span(title, class = "fs-3 lead"), hr(class = "mb-3"))`

**Comment by gadenbuie** [comment]
The `open` argument of `sidebar()` currently supports:

* `TRUE` – start open, and sidebar is collapsible.
* `FALSE` – start closed and sidebar is expandable.
* `NA` - sidebar is always open

If we're adding a new option (collapse by default on mobile), which would be signaled by `auto`, maybe we need more options for `open = `:

* `"auto"` (new default) - opens on desktop, collapses on desktop
* `"open"` (or `TRUE`) - starts open and can collapse
* `"closed"` (or `FALSE`) - start closed and can expand
* `"always"` (or `NA`) – never collapse

@cpsievert Does this reasonable?

**Comment by cpsievert** [comment]
👍, although, maybe a better word for `"auto"` would be `"desktop"` ?

**Comment by gadenbuie** [comment]
Here's another idea for `"auto"` mode: we could give the breakpoint above which the sidebar is open. The default would be `"md"`, but we'd also accept `"sm"`, `"md"`, `"xl"` or `"xxl"`.
