### ISSUE TITLE
`card(full_screen=TRUE)` triggers window resize on initialization

### ISSUE THREAD

**Issue by mauromiguelm** [rstudio/bslib#515]
## Describe the problem

Thanks for the great work on cards, its beautiful!

We run a large shiny BS5 app (bigomics/omicsplayground) and app-wide reactivity breaks when `full_screen=TRUE`. It goes back to normal when we set it back to FALSE.

I tried to provide a minimal example below, but since our app is quite big with lots os javsacript, I could not reproduce the problem. I hope the code below works as a starting point.

[Omics playground Repo with cards introduced](https://github.com/bigomics/omicsplayground/tree/a3fc69f48825addd82f8ff57afbe15aa3b061cf2)

Code example trying to approach the problem:
<details>
<pre><code>
library(shiny)
library(bslib)
library(bsicons)
library(plotly)

module_ui <- function(id){
    ns <- NS(id)
    fluidRow(
        sliderInput(ns("slider1"), label = h3("Slider"), min = 0, 
        max = 100, value = 50),
        bslib::layout_column_wrap(
            width = "250px",
            card(full_screen = TRUE,
                card_body_fill(plotlyOutput(ns("p1"))),
            ),
            value_box(
                title = "2nd value",
                value = "456",
                showcase = bs_icon("graph-up"),
                p("The 3rd detail")
                ),
            card(full_screen = TRUE,
                card_body_fill(plotlyOutput(ns("p2")))
                ),
                value_box(
                title = "2nd value",
                value = "456",
                showcase = bs_icon("graph-up"),
                p("The 3rd detail")
                ),
                value_box(
                title = "2nd value",
                value = "456",
                showcase = bs_icon("graph-up"),
                p("The 3rd detail")
                )
        )
    )
}

module_server <- function(id){
    moduleServer(id, function(input, output, session){
        plot <- reactive({
            data <- data.frame(
                a = rnorm(100, input$slider1, 10),
                b = rnorm(100, input$slider1, 10)
                )
            return(plotly::plot_ly(data = data, x = ~a, y = ~b))

        })
        output$p1 <- renderPlotly(plot())
        output$p2 <- renderPlotly(plot())

    })
}

ui <- function(){
    navbarPage(
        theme = bs_theme(version = 5),
        title = "title",
        module_ui("myCards")
        )
}

server <- function(input, output, session){
    module_server("myCards")
}

shinyApp(ui, server)
</code></pre>
</details>

### Session Info
<details>
<pre><code>
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> devtools::session_info()
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       Ubuntu 22.04.1 LTS
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  C.UTF-8
 ctype    C.UTF-8
 tz       Europe/Zurich
 date     2023-03-20
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  
 package     * version date (UTC) lib source
 cachem        1.0.7   2023-02-24 [1] CRAN (R 4.1.2)
 callr         3.7.3   2022-11-02 [1] RSPM (R 4.1.0)
 cli           3.6.0   2023-01-09 [1] CRAN (R 4.1.2)
 crayon        1.5.2   2022-09-29 [1] CRAN (R 4.1.2)
 devtools      2.4.5   2022-10-11 [1] CRAN (R 4.1.2)
 digest        0.6.31  2022-12-11 [1] CRAN (R 4.1.2)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.2)
 fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.1.2)
 fs            1.6.1   2023-02-06 [1] CRAN (R 4.1.2)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.1.2)
 htmltools     0.5.4   2022-12-07 [1] CRAN (R 4.1.2)
 htmlwidgets   1.6.1   2023-01-07 [1] CRAN (R 4.1.2)
 httpuv        1.6.9   2023-02-14 [1] CRAN (R 4.1.2)
 later         1.3.0   2021-08-18 [1] CRAN (R 4.1.2)
 lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.1.2)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.1.2)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.1.2)
 mime          0.12    2021-09-28 [1] CRAN (R 4.1.2)
 miniUI        0.1.1.1 2018-05-18 [1] RSPM (R 4.1.0)
 pkgbuild      1.4.0   2022-11-27 [1] RSPM (R 4.1.0)
 pkgload       1.3.2   2022-11-16 [1] RSPM (R 4.1.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.1.2)
 processx      3.8.0   2022-10-26 [1] CRAN (R 4.1.2)
 profvis       0.3.7   2020-11-02 [1] CRAN (R 4.1.2)
 promises      1.2.0.1 2021-02-11 [1] CRAN (R 4.1.2)
 ps            1.7.2   2022-10-26 [1] CRAN (R 4.1.2)
 purrr         1.0.1   2023-01-10 [1] CRAN (R 4.1.2)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.2)
 Rcpp          1.0.10  2023-01-22 [1] CRAN (R 4.1.2)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.1.2)
 rlang         1.1.0   2023-03-14 [1] CRAN (R 4.1.2)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.2)
 shiny         1.7.4   2022-12-15 [1] CRAN (R 4.1.2)
 stringi       1.7.12  2023-01-11 [1] CRAN (R 4.1.2)
 stringr       1.5.0   2022-12-02 [1] CRAN (R 4.1.2)
 urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.1.2)
 usethis       2.1.6   2022-05-25 [1] CRAN (R 4.1.2)
 vctrs         0.5.2   2023-01-23 [1] CRAN (R 4.1.2)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.1.2)

 [1] /usr/local/lib/R/library

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  
Warning message:
In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
</code></pre>
</details>

**Comment by gadenbuie** [comment]
As expected, I can't reproduce the problem from your example app. But I also don't have much to go on to try to introduce the issue into the app. Are there any JavaScript errors reported in the browser console? Do you have a running instance of the app we could open where the problem occurs?

**Comment by mauromiguelm** [comment]
Dear Garrick,

yes, many. @cpsievert saw it first hand. Its likely related to page refresh trigger when card is maximized that is disrupting js. Let's wait for Carson's take on this. In the meantime I will try to reproduce the issue in the example above, so we have good testing ground.

I can also test any patch in our app.

Best,
Mauro

**Comment by cpsievert** [comment]
The reason for the breakage is likely due to the fact that `card(full_screen = TRUE)` currently triggers a window resize when it gets initialized, which I don't think is needed (so we should probably stop doing that).

That being said, your app should also probably be more robust to this situation (i.e., don't be surprised if other 3rd components cause a similar failure, for similar reasons).  IIRC, you can probably fix things on your end by changing JS calls like `Shiny.setInputValue()` to `if (Shiny) Shiny.setInputValue()`

**Comment by cpsievert** [comment]
I'm pretty sure this has been addressed (but feel free to re-open if you still have issues after updating to the latest bslib)
