### ISSUE TITLE
accordion_panel_remove and _insert do not reset (output) bindings inside the panel body

### ISSUE THREAD

**Issue by michaelhogersnplm** [rstudio/bslib#530]
Using the latest bslib and shiny version there is an issue with resetting output bindings inside an accordion panel that is dynamically removed/inserted it seems.

It should be replicable via the following snippet by starting the Shiny app and clicking:
- "Remove panel 2"
- "Add panel 2"

After this `shiny::uiOutput(outputId = "card2")` will not reload and the browser console will report a duplicated id error for "card2".

An existing work around is also present in the snippet below by first clicking on "Remove panel 2 UI" before clicking on "Remove panel 2", as the app then first calls `shiny::removeUI`. Also, it seems that `accordion_panel_remove(target = id, ...)` can be entirely replaced by `shiny::removeUI(selector = paste0("[data-value=", id, "]", ...)` with (no?) side effects.

Could `bslib::accordion_panel_remove` use `shiny::removeUI`, where the `selector` argument is set to `[data-value=<value_of_the_panel>]`?

```r
ui <- function() {
    bslib::page_fluid(
        bslib::accordion(
            id = "accordion",
            bslib::accordion_panel(
                title = "Title 1",
                (
                    bslib::card(
                        bslib::card_body(
                            shiny::uiOutput(
                                outputId = "card1"
                            )
                        )
                    )
                ),
                value = "panel1"
            ),
            panel2()
        ),
        shiny::actionButton(
            inputId = "removePanel2UI",
            label = "Remove panel 2 UI"
        ),
        shiny::actionButton(
            inputId = "removePanel2",
            label = "Remove panel 2"
        ),
        shiny::actionButton(
            inputId = "addPanel2",
            label = "Add panel 2"
        )
    )
}

server <- function(input, output, session) {
    output$card1 <- shiny::renderUI({
        "card1-ui-output-1"
    })
    output$card2 <- shiny::renderUI({
        "card2-ui-output-1"
    })

    shiny::observeEvent(input$removePanel2UI, {
        shiny::removeUI(
            selector = "#card2",
            session = session,
            immediate = TRUE
        )
    })

    shiny::observeEvent(input$removePanel2, {
        bslib::accordion_panel_remove(
            session = session,
            id = "accordion",
            target = "panel2"
        )
    })

    shiny::observeEvent(input$addPanel2, {
        bslib::accordion_panel_insert(
            session = session,
            id = "accordion",
            panel = panel2()
        )
    })
}

panel2 <- function() {
    bslib::accordion_panel(
        title = "Title 2",
        (
            bslib::card(
                bslib::card_body(
                    shiny::uiOutput(
                        outputId = "card2"
                    )
                )
            )
        ),
        value = "panel2"
    )
}

shiny::shinyApp(ui, server)
```

<img width="839" alt="image" src="https://user-images.githubusercontent.com/54809578/229431922-f34a7bbf-6680-4e40-b48e-769a6c1e7cbb.png">

Best regards,
Michael

### Session Info
<details>
<pre><code>
Some of the dependencies:
─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────
 package            * version    date (UTC) lib source
 bslib                0.4.2.9000 2023-03-08 [1] Github (rstudio/bslib@85d07a6)
 htmltools            0.5.4      2022-12-07 [1] CRAN (R 4.1.2)
 htmlwidgets          1.6.1      2023-01-07 [1] CRAN (R 4.1.2)
 httpuv               1.6.9      2023-02-14 [1] CRAN (R 4.1.2)
 shiny              * 1.7.4      2022-12-15 [1] CRAN (R 4.1.3)
</code></pre>
</details>

**Comment by cpsievert** [comment]
Thank you! Here's a more minimal reprex:

```r
panel2 <- function() {
  accordion_panel(
    title = "Title 2",
    card(uiOutput("card2")),
    value = "panel2"
  )
}

ui <- page_fluid(
  accordion(
    id = "accordion", 
    open = TRUE,
    accordion_panel(
      title = "Title 1",
      card(uiOutput("card1")),
      value = "panel1"
    ),
    panel2()
  ),
  actionButton(
    "removePanel2","Remove panel 2"
  ),
  actionButton(
    "addPanel2", "Add panel 2"
  )
)

server <- function(input, output, session) {
  output$card1 <- renderUI({
    "card1"
  })
  output$card2 <- renderUI({
    "card2"
  })
  
  observeEvent(input$removePanel2, {
    accordion_panel_remove(
      session = session,
      id = "accordion",
      target = "panel2"
    )
  })
  
  observeEvent(input$addPanel2, {
    accordion_panel_insert(
      session = session,
      id = "accordion",
      panel = panel2()
    )
    accordion_panel_open("accordion", "panel2")
  })
}

shinyApp(ui, server)
```
