### ISSUE TITLE
sidebar() title border isn't present with `border = FALSE`

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#544]
I just realized the border goes away in this case. I think it's probably better to keep it (especially for the `page_fillable()` case)

```r
layout_sidebar(
    border = FALSE,
    sidebar = sidebar(
        title = "Title",
        "foo"
    ),
    "bar"
)
```

**Comment by gadenbuie** [comment]
After merging #526 I can no longer reproduce this.
