### ISSUE TITLE
Alllow `as_fill*()` to be spliced into tags

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#570]
Currently we have to do 

```r
div() |>
  as_fill_carrier()
```

but we should probably also support

```r
div(
  !!!as_fill_carrier()
)
```

**Comment by gadenbuie** [comment]
I proposed an approach in #571 that would allow users to call `as_fill_carrier()` directly inside an htmltools tag without having to use the `!!!` operator, which would make the second option

```r
div(
  as_fill_carrier(),
  p("other content...")
)
```
