### ISSUE TITLE
Improve `value_box()` behavior with dynamic values

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#573]
I've been thinking that we'd promote this sort of pattern for dynamically updating value box value(s)/content(s):

```r
# ui
value_box("A title", uiOutput("value"))

# server
output$val <- renderUI(...)
```

I had overlooked though, to get the sizing the way you might expect, you currently need something like `value_box("A title", uiOutput("value", container = h2))`. I think though, we can get the above usage to behave "nicely" (i.e., give the right sizing to `.shiny-html-output`)?

Another avenue we could explore, of course, would be something like `value_box_update()`...

Regardless of the approach, we should be mindful to try and avoid layout shift (i.e., provide some sort of min-height for the value's containing element)

**Comment by DavZim** [comment]
I use something very similar to this (I create the value box with handcrafted HTML in the UI and leave only the value field as uiOutput, which is updated/filled in the server).

In my experience this makes the app a lot faster and more *reactive*, from taking a noticeable amount of time for a page with a  couple of value boxes to instant updates.
