### ISSUE TITLE
Error trying to preview a theme

### ISSUE THREAD

**Issue by nteetor** [rstudio/bslib#592]
Using the development version of bslib, when trying to use `bs_theme_preview()` I get the following error,

```
Error in tipsUI("tips") : could not find function "tipsUI"
```

**Comment by cpsievert** [comment]
What version of shiny do you have? Have you set `options(shiny.autoload.r=FALSE)`?

**Comment by nteetor** [comment]
Looks like I'm using shiny 1.7.4 and `shiny.autoload.r` is `FALSE`, although I haven't intentionally modified that value.

**Comment by cpsievert** [comment]
Hmm, ok. Something must be setting that option (it's not Shiny or bslib doing that).

`options(shiny.autoload.r=NULL); bs_theme_preview()` should fix

**Comment by nteetor** [comment]
Yes, `bs_theme_preview()` is working now, thank you. I'll see if I can track down what's changing `shiny.autoload.r`.
