### ISSUE TITLE
libuv assertion error

### ISSUE THREAD

**Issue by dariomavec** [rstudio/bslib#593]
## Describe the problem

When running a simple `navbarPage()` UI on an R Server instance, I will occasionally have the whole process die when launching the app with error:

`R: src/unix/core.c:299: uv__finish_close: Assertion '0' failed.`

Hard to get a reliable repro of the issue as it happens inconsistently.  Is there a require version of `libuv` for this package? The server is currently running 1.43.0.

### Session Info

<details>
<pre><code>
─ Session info ──────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.0 (2021-05-18)
 os       Red Hat
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Australia/Sydney
 date     2023-05-25
 rstudio  2022.02.2+485.pro2 Prairie Trillium (server)
 pandoc   2.17.1.1 @ /usr/lib/rstudio-server/bin/quarto/bin/ (via rmarkdown)

─ Packages ──────────────────────────────────────────────────────────────────────────────────
 ! package           * version date (UTC) lib source
 P askpass             1.1     2019-01-13 [?] RSPM (R 4.1.0)
 P assertthat        * 0.2.1   2019-03-21 [?] RSPM (R 4.1.0)
 P base64enc           0.1-3   2015-07-28 [?] RSPM (R 4.1.0)
 P bit                 4.0.5   2022-11-15 [?] RSPM (R 4.1.0)
 P bit64               4.0.5   2020-08-30 [?] RSPM (R 4.1.0)
 P bslib             * 0.4.2   2022-12-16 [?] RSPM (R 4.1.0)
 P cachem              1.0.8   2023-05-01 [?] RSPM (R 4.1.0)
 P callr               3.7.3   2022-11-02 [?] RSPM (R 4.1.0)
 P cellranger          1.1.0   2016-07-27 [?] RSPM (R 4.1.0)
 P cli                 3.6.1   2023-03-23 [?] RSPM (R 4.1.0)
 P coda                0.19-4  2020-09-30 [?] RSPM (R 4.1.0)
 P codetools           0.2-18  2020-11-04 [?] CRAN (R 4.1.0)
 P colorspace          2.1-0   2023-01-23 [?] RSPM (R 4.1.0)
 P crayon            * 1.5.2   2022-09-29 [?] RSPM (R 4.1.0)
 P crosstalk           1.2.0   2021-11-04 [?] RSPM (R 4.1.0)
 P crul                1.3     2022-09-03 [?] RSPM (R 4.1.0)
 P curl                5.0.0   2023-01-12 [?] RSPM (R 4.1.0)
 P cyphr               1.1.4   2022-06-20 [?] RSPM (R 4.1.0)
 P data.table        * 1.14.8  2023-02-17 [?] RSPM (R 4.1.0)
 P DBI                 1.1.3   2022-06-18 [?] RSPM (R 4.1.0)
 P devtools            2.4.5   2022-10-11 [?] RSPM (R 4.1.0)
 P digest              0.6.31  2022-12-11 [?] RSPM (R 4.1.0)
 P dplyr             * 1.1.2   2023-04-20 [?] RSPM (R 4.1.0)
 P DT                * 0.27    2023-01-17 [?] RSPM (R 4.1.0)
 P ellipsis            0.3.2   2021-04-29 [?] RSPM (R 4.1.0)
 P evaluate            0.21    2023-05-05 [?] RSPM (R 4.1.0)
 P extrafont           0.19    2023-01-18 [?] RSPM (R 4.1.0)
 P extrafontdb         1.0     2012-06-11 [?] RSPM (R 4.1.0)
 P fansi               1.0.4   2023-01-22 [?] RSPM (R 4.1.0)
 P fastmap             1.1.1   2023-02-24 [?] RSPM (R 4.1.0)
 P filesstrings        3.2.4   2023-01-25 [?] RSPM (R 4.1.0)
 P flextable         * 0.9.1   2023-04-02 [?] RSPM (R 4.1.0)
 P fontBitstreamVera   0.1.1   2017-02-01 [?] RSPM (R 4.1.0)
 P fontLiberation      0.1.0   2016-10-15 [?] RSPM (R 4.1.0)
 P fontquiver          0.2.1   2017-02-01 [?] RSPM (R 4.1.0)
 P forcats           * 1.0.0   2023-01-29 [?] RSPM (R 4.1.0)
 P formattable         0.2.1   2021-01-07 [?] RSPM (R 4.1.0)
 P fs                  1.6.2   2023-04-25 [?] RSPM (R 4.1.0)
 P gdtools             0.3.3   2023-03-27 [?] RSPM (R 4.1.0)
 P generics            0.1.3   2022-07-05 [?] RSPM (R 4.1.0)
 P geosphere           1.5-18  2022-11-15 [?] RSPM (R 4.1.0)
 P gfonts              0.2.0   2023-01-08 [?] RSPM (R 4.1.0)
 P ggplot2           * 3.4.2   2023-04-03 [?] RSPM (R 4.1.0)
 P glue              * 1.6.2   2022-02-24 [?] RSPM (R 4.1.0)
 P gridExtra         * 2.3     2017-09-09 [?] RSPM (R 4.1.0)
 P gtable              0.3.3   2023-03-21 [?] RSPM (R 4.1.0)
 P hms                 1.1.3   2023-03-21 [?] RSPM (R 4.1.0)
 P hrbrthemes          0.8.0   2020-03-06 [?] RSPM (R 4.1.0)
 P htmltools         * 0.5.5   2023-03-23 [?] RSPM (R 4.1.0)
 P htmlwidgets       * 1.6.2   2023-03-17 [?] RSPM (R 4.1.0)
 P httpcode            0.3.0   2020-04-10 [?] RSPM (R 4.1.0)
 P httpuv              1.6.10  2023-05-08 [?] RSPM (R 4.1.0)
 P httr                1.4.6   2023-05-08 [?] RSPM (R 4.1.0)
 P janitor           * 2.2.0   2023-02-02 [?] RSPM (R 4.1.0)
 P jquerylib           0.1.4   2021-04-26 [?] RSPM (R 4.1.0)
 P jsonlite          * 1.8.4   2022-12-06 [?] RSPM (R 4.1.0)
 P kableExtra        * 1.3.4   2021-02-20 [?] RSPM (R 4.1.0)
 P knitr               1.42    2023-01-25 [?] RSPM (R 4.1.0)
 P later               1.3.1   2023-05-02 [?] RSPM (R 4.1.0)
 P lattice             0.21-8  2023-04-05 [?] RSPM (R 4.1.0)
 P lazyeval            0.2.2   2019-03-15 [?] RSPM (R 4.1.0)
 P leaflet           * 2.1.2   2023-03-10 [?] RSPM (R 4.1.0)
 P leaflet.extras    * 1.0.0   2018-04-21 [?] RSPM (R 4.1.0)
 P leaflet.providers * 1.9.0   2019-11-09 [?] RSPM (R 4.1.0)
 P lifecycle           1.0.3   2022-10-07 [?] RSPM (R 4.1.0)
 P logger            * 0.2.2   2021-10-19 [?] RSPM (R 4.1.0)
 P lubridate         * 1.9.2   2023-02-10 [?] RSPM (R 4.1.0)
 P magrittr          * 2.0.3   2022-03-30 [?] RSPM (R 4.1.0)
 P MASS                7.3-60  2023-05-04 [?] RSPM (R 4.1.0)
 P Matrix              1.5-4   2023-04-04 [?] RSPM (R 4.1.0)
 P MatrixModels        0.5-1   2022-09-11 [?] RSPM (R 4.1.0)
 P mcmc                0.9-7   2020-03-21 [?] RSPM (R 4.1.0)
 P MCMCpack            1.6-3   2022-04-13 [?] RSPM (R 4.1.0)
 P memoise             2.0.1   2021-11-26 [?] RSPM (R 4.1.0)
 P mime                0.12    2021-09-28 [?] RSPM (R 4.1.0)
 P miniUI              0.1.1.1 2018-05-18 [?] RSPM (R 4.1.0)
 P munsell             0.5.0   2018-06-12 [?] RSPM (R 4.1.0)
 P officer           * 0.6.2   2023-03-28 [?] RSPM (R 4.1.0)
 P openssl             2.0.6   2023-03-09 [?] RSPM (R 4.1.0)
 P openxlsx          * 4.2.5.2 2023-02-06 [?] RSPM (R 4.1.0)
 P pillar              1.9.0   2023-03-22 [?] RSPM (R 4.1.0)
 P pkgbuild            1.4.0   2022-11-27 [?] RSPM (R 4.1.0)
 P pkgconfig           2.0.3   2019-09-22 [?] RSPM (R 4.1.0)
 P pkgload             1.3.2   2022-11-16 [?] RSPM (R 4.1.0)
 P PKI                 0.1-12  2022-11-28 [?] RSPM (R 4.1.0)
 P plotly            * 4.10.1  2022-11-07 [?] RSPM (R 4.1.0)
 P prettyunits         1.1.1   2020-01-24 [?] RSPM (R 4.1.0)
 P processx            3.8.1   2023-04-18 [?] RSPM (R 4.1.0)
 P profvis             0.3.8   2023-05-02 [?] RSPM (R 4.1.0)
 P promises            1.2.0.1 2021-02-11 [?] RSPM (R 4.1.0)
 P ps                  1.7.5   2023-04-18 [?] RSPM (R 4.1.0)
 P purrr             * 1.0.1   2023-01-10 [?] RSPM (R 4.1.0)
 P qHelpers          * 0.7.3   2022-03-08 [?] local
 P qs                  0.25.5  2023-02-22 [?] RSPM (R 4.1.0)
 P quantreg            5.95    2023-04-08 [?] RSPM (R 4.1.0)
 P R6                  2.5.1   2021-08-19 [?] RSPM (R 4.1.0)
 P ragg                1.2.5   2023-01-12 [?] RSPM (R 4.1.0)
 P RApiSerialize       0.1.2   2022-08-25 [?] RSPM (R 4.1.0)
 P raster            * 3.6-20  2023-03-06 [?] RSPM (R 4.1.0)
 P RColorBrewer      * 1.1-3   2022-04-03 [?] RSPM (R 4.1.0)
 P Rcpp                1.0.10  2023-01-22 [?] RSPM (R 4.1.0)
 P RcppParallel        5.1.7   2023-02-27 [?] RSPM (R 4.1.0)
 P reactable         * 0.4.4   2023-03-12 [?] RSPM (R 4.1.0)
 P readr             * 2.1.4   2023-02-10 [?] RSPM (R 4.1.0)
 P readxl            * 1.4.2   2023-02-09 [?] RSPM (R 4.1.0)
 P remotes             2.4.2   2021-11-30 [?] RSPM (R 4.1.0)
   renv                0.17.3  2023-04-06 [1] RSPM (R 4.1.0)
 P rlang               1.1.1   2023-04-28 [?] RSPM (R 4.1.0)
 P rmarkdown         * 2.21    2023-03-26 [?] RSPM (R 4.1.0)
 P rsconnect           0.8.29  2023-01-09 [?] RSPM (R 4.1.0)
 P rstudioapi          0.14    2022-08-22 [?] RSPM (R 4.1.0)
 P Rttf2pt1            1.3.12  2023-01-22 [?] RSPM (R 4.1.0)
 P rvest               1.0.3   2022-08-19 [?] RSPM (R 4.1.0)
 P sass                0.4.6   2023-05-03 [?] RSPM (R 4.1.0)
 P scales            * 1.2.1   2022-08-20 [?] RSPM (R 4.1.0)
 P sessioninfo         1.2.2   2021-12-06 [?] RSPM (R 4.1.0)
 P shiny             * 1.7.4   2022-12-15 [?] RSPM (R 4.1.0)
 P shinyalert        * 3.0.0   2021-12-20 [?] RSPM (R 4.1.0)
 P shinycssloaders   * 1.0.0   2020-07-28 [?] RSPM (R 4.1.0)
 P shinydashboard    * 0.7.2   2021-09-30 [?] RSPM (R 4.1.0)
 P shinyjs           * 2.1.0   2021-12-23 [?] RSPM (R 4.1.0)
 P shinyWidgets      * 0.7.6   2023-01-08 [?] RSPM (R 4.1.0)
 P snakecase           0.11.0  2019-05-25 [?] RSPM (R 4.1.0)
 P sodium              1.2.1   2022-06-11 [?] RSPM (R 4.1.0)
 P sp                * 1.6-0   2023-01-19 [?] RSPM (R 4.1.0)
 P SparseM             1.81    2021-02-18 [?] RSPM (R 4.1.0)
 P strex               1.6.0   2023-01-21 [?] RSPM (R 4.1.0)
 P stringdist          0.9.10  2022-11-07 [?] RSPM (R 4.1.0)
 P stringfish          0.15.7  2022-04-13 [?] RSPM (R 4.1.0)
 P stringi           * 1.7.12  2023-01-11 [?] RSPM (R 4.1.0)
 P stringr           * 1.5.0   2022-12-02 [?] RSPM (R 4.1.0)
 P survival            3.5-5   2023-03-12 [?] RSPM (R 4.1.0)
 P svglite             2.1.1   2023-01-10 [?] RSPM (R 4.1.0)
 P systemfonts         1.0.4   2022-02-11 [?] RSPM (R 4.1.0)
 P terra               1.7-29  2023-04-22 [?] RSPM (R 4.1.0)
 P textshaping         0.3.6   2021-10-13 [?] RSPM (R 4.1.0)
 P tibble            * 3.2.1   2023-03-20 [?] RSPM (R 4.1.0)
 P tidyr             * 1.3.0   2023-01-24 [?] RSPM (R 4.1.0)
 P tidyselect          1.2.0   2022-10-10 [?] RSPM (R 4.1.0)
 P timechange          0.2.0   2023-01-11 [?] RSPM (R 4.1.0)
 P tzdb                0.3.0   2022-03-28 [?] RSPM (R 4.1.0)
 P urlchecker          1.0.1   2021-11-30 [?] RSPM (R 4.1.0)
 P usethis             2.1.6   2022-05-25 [?] RSPM (R 4.1.0)
 P utf8                1.2.3   2023-01-31 [?] RSPM (R 4.1.0)
 P uuid                1.1-0   2022-04-19 [?] RSPM (R 4.1.0)
 P vaccineRollout    * 0.5.24  2023-05-18 [?] local
 P vctrs               0.6.2   2023-04-19 [?] RSPM (R 4.1.0)
 P viridisLite         0.4.2   2023-05-02 [?] RSPM (R 4.1.0)
 P webshot             0.5.4   2022-09-26 [?] RSPM (R 4.1.0)
 P withr               2.5.0   2022-03-03 [?] RSPM (R 4.1.0)
 P xfun                0.39    2023-04-20 [?] RSPM (R 4.1.0)
 P xml2                1.3.4   2023-04-27 [?] RSPM (R 4.1.0)
 P xtable              1.8-4   2019-04-21 [?] RSPM (R 4.1.0)
 P yaml                2.3.7   2023-01-23 [?] RSPM (R 4.1.0)
 P zip                 2.3.0   2023-04-17 [?] RSPM (R 4.1.0)
 P zoo               * 1.8-12  2023-04-13 [?] RSPM (R 4.1.0)
</code></pre>
</details>

**Comment by gadenbuie** [comment]
Hi @dariomavec and thanks for including your session info! We had an [unfortunate bug sneak into httpuv](https://github.com/rstudio/shiny/issues/3822) version 1.6.10 and we published a fix as quickly as we could. I can see from your session info that you're currently using this version, which explains the error. Can you please try updating to the latest httpuv, version 1.6.11?

**Comment by dariomavec** [comment]
Thanks @gadenbuie! This (appears) to have fixed the issue.

While I've got you, is there any target date for the next stable release of `bslib`?  I'm excited about a lot of the components you're already showcasing in 0.4.2.9000!

**Comment by gadenbuie** [comment]
Soon! 😉 We're working on finishing up some final pieces we want to have in place before the next release.
