### ISSUE TITLE
Improvements to `value_box()` styling

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#602]
- [ ] Avoid fixed sizing of icons (`.bi` is currently sized with `width:1rem; height:1rem; font-size: 5rem`? Seems like it should be more like `width:100%`?) 
- [ ] Make sure the value/title shares a common baseline, even when the additional content is of varied length (see [value boxes](https://rstudio.github.io/bslib/articles/value-boxes.html) for an example)
- [ ] Make it easier/possible to use lighter/transparent colors. I think we had avoided that in the past to avoid color contrast issues, but maybe we just expose a `fg` to deal with that.

**Comment by gadenbuie** [comment]
I just noticed the font colors aren't quite right on the value box examples you linked above

```r
value_box(
  title = "I got", 
  value = "99 problems",
  showcase = bs_icon("music-note-beamed"),
  p("bslib ain't one", bs_icon("emoji-smile")),
  p("hit me", bs_icon("suit-spade"))
)
```

![image](https://github.com/rstudio/bslib/assets/5420529/832e5e75-aa31-4468-83d5-facd6c1e4690)

This might be the result of CSS changes in #605 and #616? Maybe that the text color styles of h6/h2 styles are missing now.

**Comment by cpsievert** [comment]
Superceded by https://github.com/rstudio/bslib/issues/704
