### ISSUE TITLE
updateTabsetPanel for page_navbar dont close  dropdown

### ISSUE THREAD

**Issue by riskcede** [rstudio/bslib#621]
Hi Everyone

Im using bslib version 0.4.2.9

## Describe the problem

I have a shiny app with a navbar menu. When updating the tabsetpanel it does move to the correct tab, but it keeps the dropdown menu in the navbar open.

If i switch to nabarPage (from page_navbar) it does close the menu when running updateTabsetPanel

```r

library(shiny)
library(bslib)

# ui <- navbarPage(
ui <- page_navbar(

  title = 'App',
  id = 'nav_page',
  collapsible = TRUE,

  tabPanel("Start_tab",
           actionButton("do", "Click Me")
  ),
  navbarMenu("End_tabs",
             
             tabPanel("tab1",
                      'tab1'
                      ),
             
             tabPanel("tab2",
                      'tab2'
                      )
             )
  )


server <- function(session, input, output) {
  
  observeEvent(input$do, {
    updateTabsetPanel(session, "nav_page", "tab1")
  })
  
  }


shinyApp(ui = ui, server = server)

```

### Session Info

<details>
<pre><code>
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.0 (2021-05-18)
 os       Ubuntu 18.04.5 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  C.UTF-8
 ctype    C.UTF-8
 tz       Africa/Johannesburg
 date     2023-06-07
 rstudio  2023.03.1+446 Cherry Blossom (server)
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 bslib       * 0.4.2.9000 2023-06-06 [1] Github (rstudio/bslib@048502a)
 cachem        1.0.6      2021-08-19 [2] CRAN (R 4.1.0)
 callr         3.7.0      2021-04-20 [1] CRAN (R 4.1.0)
 cli           3.4.1      2022-09-23 [1] CRAN (R 4.1.0)
 crayon        1.5.2      2022-09-29 [1] CRAN (R 4.1.0)
 desc          1.4.0      2021-09-28 [1] CRAN (R 4.1.0)
 devtools      2.4.3      2021-11-30 [1] CRAN (R 4.1.0)
 digest        0.6.30     2022-10-18 [1] CRAN (R 4.1.0)
 ellipsis      0.3.2      2021-04-29 [2] CRAN (R 4.1.0)
 fastmap       1.1.0      2021-01-25 [2] CRAN (R 4.1.0)
 fs            1.5.2      2021-12-08 [1] CRAN (R 4.1.0)
 glue          1.6.2      2022-02-24 [1] CRAN (R 4.1.0)
 htmltools     0.5.4      2022-12-07 [1] CRAN (R 4.1.0)
 httpuv        1.6.6      2022-09-08 [1] CRAN (R 4.1.0)
 jquerylib     0.1.4      2021-04-26 [2] CRAN (R 4.1.0)
 jsonlite      1.8.3      2022-10-21 [1] CRAN (R 4.1.0)
 later         1.3.0      2021-08-18 [2] CRAN (R 4.1.0)
 lifecycle     1.0.3      2022-10-07 [1] CRAN (R 4.1.0)
 magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.1.0)
 memoise       2.0.1      2021-11-26 [1] CRAN (R 4.1.0)
 mime          0.12       2021-09-28 [1] CRAN (R 4.1.0)
 pkgbuild      1.3.1      2021-12-20 [1] CRAN (R 4.1.0)
 pkgload       1.2.4      2021-11-30 [1] CRAN (R 4.1.0)
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.1.0)
 processx      3.5.2      2021-04-30 [1] CRAN (R 4.1.0)
 promises      1.2.0.1    2021-02-11 [2] CRAN (R 4.1.0)
 ps            1.6.0      2021-02-28 [1] CRAN (R 4.1.0)
 purrr         0.3.5      2022-10-06 [1] CRAN (R 4.1.0)
 R6            2.5.1      2021-08-19 [2] CRAN (R 4.1.0)
 Rcpp          1.0.9      2022-07-08 [1] CRAN (R 4.1.0)
 remotes       2.4.2      2021-11-30 [1] CRAN (R 4.1.0)
 rlang         1.0.6      2022-09-24 [1] CRAN (R 4.1.0)
 rprojroot     2.0.2      2020-11-15 [1] CRAN (R 4.1.0)
 rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.1.0)
 sass          0.4.4      2022-11-24 [1] CRAN (R 4.1.0)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.0)
 shiny       * 1.7.4      2022-12-15 [1] CRAN (R 4.1.0)
 testthat      3.1.1      2021-12-03 [1] CRAN (R 4.1.0)
 usethis       2.1.5      2021-12-09 [1] CRAN (R 4.1.0)
 withr         2.5.0      2022-03-03 [1] CRAN (R 4.1.0)
 xtable        1.8-4      2019-04-21 [2] CRAN (R 4.1.0)

 [1] /home/jan/R/x86_64-pc-linux-gnu-library/4.1
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
</code></pre>
</details>

**Comment by li081766** [comment]
@riskcede Do you solve it? I have the same problem when I use version 5 of bs_theme

**Comment by teofiln** [comment]
FWIW. Seeing the same problem with 'bslib::nav*` family of functions and `nav_select`.

```
library(shiny)
library(bslib)
library(rlang)

nav_items <- function(prefix) {
  list(
    nav("a", tagList(
      paste(prefix, ": tab a content"),
      actionButton(inputId = "go_to_tab_c", label = "Go to tab C")
    )),
    nav("b", paste(prefix, ": tab b content")),
    nav_item(
      tags$a(icon("github"), "Shiny", href = "https://github.com/rstudio/shiny", target = "_blank")
    ),
    nav_spacer(),
    nav_menu(
      value = "ya",
      title = "Other links",
      align = "right",
      nav("c", paste(prefix, ": tab c content")),
      nav_item(
        tags$a(
          icon("r-project"),
          "RStudio",
          href = "https://rstudio.com",
          target = "_blank"
        )
      )
    )
  )
}

ui <- page_fluid(
  page_navbar(
    id = "main_nav",
    title = "Page",
    bg = "#0062cc",
    !!!nav_items(prefix = "page_navbar")
  )
)

server <- function(input, output, session) {
  observeEvent(input$go_to_tab_c, {
    nav_select(id = "main_nav", selected = "c")
  })
  
}

shinyApp(ui, server)
```

```
> packageVersion("shiny")
[1] ‘1.7.4’
> packageVersion("bslib")
[1] ‘0.4.2’
```

**Comment by gadenbuie** [comment]
Thanks for the report everyone. I can reproduce the issue from the examples you've provided.

For some background context: in Bootstrap v5, Bootstrap reduced their level of support for dropdown menus in tabsets. In particular, (IIUC) Bootstrap 5 now leaves the dropdown menu open when a tab item is activated via a dropdown menu. In [their documentation](https://getbootstrap.com/docs/5.3/components/navs-tabs/#accessibility) they explain their reasoning for this behavior

> The tab JavaScript plugin does not support tabbed interfaces that contain dropdown menus, as these cause both usability and accessibility issues. From a usability perspective, the fact that the currently displayed tab’s trigger element is not immediately visible (as it’s inside the closed dropdown menu) can cause confusion. From an accessibility point of view, there is currently no sensible way to map this sort of construct to a standard WAI ARIA pattern, meaning that it cannot be easily made understandable to users of assistive technologies.

My understanding from the above is that it is now the expected behavior in Bootstrap 5 that programmatically activating a tab whose target element is contained in a dropdown menu will not close the dropdown menu. This is primarily so that users have the opportunity to know which tab is activated (otherwise the current context is hidden from users).

We may explore changing this behavior for Shiny apps, but I personally agree with Bootstrap's position.

**Comment by riskcede** [comment]
Hi Garrick, thanks for the reply and the explanation. I agree that it does help orientating the user on where they are in the app.Is there any way to close the menu from the server?I tried some JS that identifies the state of the dropdown, but wasnt able to close it..RegardsJanOn 09 Jun 2023, at 16:36, Garrick Aden-Buie ***@***.***> wrote:﻿
Thanks for the report everyone. I can reproduce the issue from the examples you've provided.
For some background context: in Bootstrap v5, Bootstrap reduced their level of support for dropdown menus in tabsets. In particular, (IIUC) Bootstrap 5 now leaves the dropdown menu open when a tab item is activated via a dropdown menu. In their documentation they explain their reasoning for this behavior

The tab JavaScript plugin does not support tabbed interfaces that contain dropdown menus, as these cause both usability and accessibility issues. From a usability perspective, the fact that the currently displayed tab’s trigger element is not immediately visible (as it’s inside the closed dropdown menu) can cause confusion. From an accessibility point of view, there is currently no sensible way to map this sort of construct to a standard WAI ARIA pattern, meaning that it cannot be easily made understandable to users of assistive technologies.

My understanding from the above is that it is now the expected behavior in Bootstrap 5 that programmatically activating a tab whose target element is contained in a dropdown menu will not close the dropdown menu. This is primarily so that users have the opportunity to know which tab is activated (otherwise the current context is hidden from users).
We may explore changing this behavior for Shiny apps, but I personally agree with Bootstrap's position.

**Comment by gadenbuie** [comment]
> Is there any way to close the menu from the server?

It's certainly possible and would require writing some JavaScript. But I agree, in principle, with the Bootstrap developers: programmatically changing the selected tab or page should include a visual indication for the user. We may be able to find a reasonable compromise, like closing the dropdown after users have interacted with other elements on the newly opened page, or closing the dropdown after a delay. 

For now though, I'm inclined to closely follow Bootstrap's implementation. If you have a strong argument as to how the open dropdown menu might interfere with the usability of your app or with the user's experience, I'd love to hear about it. That would help us when re-evaluating this issue.

**Comment by riskcede** [comment]
HI GarrickThat sounds like a good solution. Once the user is interacting on the new page you can assume they are comfortable with where he is and closing the dropdown menu in the background shouldnt disorientate him.Thanks for your feedback. Please feel free to close the issue now.RegardsJanOn 12 Jun 2023, at 15:43, Garrick Aden-Buie ***@***.***> wrote:﻿

Is there any way to close the menu from the server?

It's certainly possible and would require writing some JavaScript. But I agree, in principle, with the Bootstrap developers: programmatically changing the selected tab or page should include a visual indication for the user. We may be able to find a reasonable compromise, like closing the dropdown after users have interacted with other elements on the newly opened page, or closing the dropdown after a delay.
For now though, I'm inclined to closely follow Bootstrap's implementation. If you have a strong argument as to how the open dropdown menu might interfere with the usability of your app or with the user's experience, I'd love to hear about it. That would help us when re-evaluating this issue.

**Comment by riskcede** [comment]
Hi TeofilIve received an email earlier with a suggestion of closing the menu when the user interacts on the new page.But now your solution seems even better. It creates the feeling of fading into the new page.I got it to work on my app with your js and that observe in shiny.Thanks for helping!!!RegardsJanOn 12 Jun 2023, at 18:42, Teofil Nakov ***@***.***> wrote:﻿
Hi @riskcede, here is a 'solution' that would close the dropdown after 3 seconds. It's not particularly clean or safe, as it targets the .dropdown-menu class, so the observer might close other menus that you don't want to close. Probably better to target the correct dropdown by id. Also, there is some R logic to check if the user is on one of the tabs 'within' the dropdown menu, which might not be needed if you can check the state of the dropdown from JS.
But maybe will give you an idea how to best implement in your app.
library(shiny)
library(bslib)
library(rlang)

nav_items <- function(prefix) {
  list(
    nav("a", tagList(
      paste(prefix, ": tab a content"),
      actionButton(inputId = "go_to_tab_c", label = "Go to tab C")
    )),
    nav("b", paste(prefix, ": tab b content")),
    nav_item(
      tags$a(icon("github"), "Shiny", href = "https://github.com/rstudio/shiny", target = "_blank")
    ),
    nav_spacer(),
    nav_menu(
      title = "Other links",
      align = "right",
      nav("c", paste(prefix, ": tab c content")),
      nav_item(
        tags$a(
          icon("r-project"),
          "RStudio",
          href = "https://rstudio.com",
          target = "_blank"
        )
      )
    )
  )
}

ui <- page_fluid(
  page_navbar(
    id = "main_nav",
    title = "Page",
    bg = "#0062cc",
    tags$script("
        Shiny.addCustomMessageHandler(
          'toggleDropdown',
          function toggleDropdown(msg) {
            $('.dropdown-menu').removeClass('show')
          });
        "
        ),
    !!!nav_items(prefix = "page_navbar")
  )
)

server <- function(input, output, session) {

  observeEvent(input$go_to_tab_c, {
    nav_select(id = "main_nav", selected = "c")
  })

  observe({
    if (input$main_nav %in% "c") {
      Sys.sleep(3)
      session$sendCustomMessage(
        type = "toggleDropdown",
        message = list(msg = "hide dropdown"))
    }
  })

}

shinyApp(ui, server)
