### ISSUE TITLE
Uncompressed sources of JS missing

### ISSUE THREAD

**Issue by tillea** [rstudio/bslib#628]
## Debian packaging requires uncompressed  JS

Debian packaging requires sources for all non-human readable files.  Compressed JS is considered binary without source and thus we need to provide the sources (and a way to build the compressed version from source) to ship software in an official Debian package.  Version 0.5.0 has three new compressed JS files

    inst/components/accordion.min.js
    inst/components/card.min.js
    inst/components/sidebar.min.js

It would be great if you could either include the uncompressed source into your source tarball or at least link to the origin of these files inside the docs (including the version that is used).

Thanks a lot
   Andreas (from Debian R packaging team)

**Comment by gadenbuie** [comment]
Hi @tillea, those files are stored in our source repo here in [srcts/src/components](https://github.com/rstudio/bslib/tree/main/srcts/src/components) and they're first-party code files that are part of bslib's code base (i.e. bslib's version is their version).

We'll look into including the uncompressed javascript files in the CRAN package bundle in future releases of bslib.

**Comment by tillea** [comment]
Am Mon, Jun 12, 2023 at 06:30:01AM -0700 schrieb Garrick Aden-Buie:
> Hi @tillea, those files are stored in our source repo here in [srcts/src/components](https://github.com/rstudio/bslib/tree/main/srcts/src/components) and they're first-party code files that are part of bslib's code base (i.e. bslib's version is their version).

Thanks a lot for the quick clarification.
 
> We'll look into including the uncompressed javascript files in the CRAN package bundle in future releases of bslib.

This would be really helpful.  Do you plan to do a new release in say the next month or so?  If not I might temporarily drain the source code from the source repo as long as it is not included inside the published tarball.

Kind regards, Andreas.

**Comment by gadenbuie** [comment]
> This would be really helpful. Do you plan to do a new release in say the next month or so?

Great! It's hard to say when we'll release to CRAN again, so if it's not too much work I'd recommend copying the source files. That said, I do think it'd be relatively easy for us to ensure these files make it into the package bundle, so we'll be sure it's included in the next official release.

**Comment by tillea** [comment]
Am Mon, Jun 12, 2023 at 07:13:07AM -0700 schrieb Garrick Aden-Buie:
> Great! It's hard to say when we'll release to CRAN again, so if it's not too much work I'd recommend copying the source files. That said, I do think it'd be relatively easy for us to ensure these files make it into the package bundle, so we'll be sure it's included in the next official release.

Thanks a lot for your cooperation, Andreas.

**Comment by tillea** [comment]
> Hi @tillea, those files are stored in our source repo here in [srcts/src/components](https://github.com/rstudio/bslib/tree/main/srcts/src/components) and they're first-party code files that are part of bslib's code base (i.e. bslib's version is their version).
> 
> We'll look into including the uncompressed javascript files in the CRAN package bundle in future releases of bslib.

I've found the `*.ts` files as pointed out.  Could you point me to a script which transfers `*.ts` to `*.js` / `*.min.js`.  Sorry, I'm not a JS expert and its the first time I'm facing `*.ts` and I guess its somewhere hidden in your repository as a build script.
Thanks a lot, Andreas.

**Comment by gadenbuie** [comment]
Sure! We use `esbuild` to compile the `.ts` files, which is controlled using the build script in https://github.com/rstudio/bslib/blob/main/srcts/build/index.ts. We'll likely update our build settings to include the compiled but unminified `.js` files; it's a small change but I'm not ready to do that quite yet because it will likely lead us to do some reorganizing of our component assets.
