### ISSUE TITLE
Accordion headers, adjust `accordion-header` class instead of adding `h2`

### ISSUE THREAD

**Issue by nteetor** [rstudio/bslib#631]
I apologize, this isn't quite a bug report and not quite a feature request. 

I was a little surprised today when I noticed the `h2` class is added to accordion headers. The accordion header element already includes the `accordion-header` class. In my case, the `h2` styles are undesirable. I've created a simpler wrapper around `accordion_panel` and I'm removing `h2` class with the query tools from {htmltools}. I'm wondering if the styles from `h2` could get worked into the `accordion-header` class. In this case, one would be able to adjust the accordion styling with a custom theme via the accordion-related sass variables.

**Comment by gadenbuie** [comment]
Thanks Nate, I think you bring up a good point. I made the suggested adjustment in #632, can you check and see if that works well for you?

**Comment by nteetor** [comment]
Hey Garrick, thank you for the quick response. I completely forgot about Sass's extend feature. Everything looks good to me.
