### ISSUE TITLE
Reactives in sidebar never trigger if sidebar starts closed

### ISSUE THREAD

**Issue by michael-dewar** [rstudio/bslib#636]
## Describe the problem

If a sidebar starts closed and contains reactive elements, then they do not appear when the sidebar is opened.  Opening the sidebar should trigger their rendering.

```r
library(shiny)
library(bslib)

ui <- page_fillable(
  layout_sidebar(
  	sidebar = sidebar(open = "closed",
  					  textOutput("text"))
  )
)

server <- function(input, output, session) {
  output$text <- renderText('Hello')
}

shinyApp(ui, server)
```
When you open the sidebar in the app, you do not see any text.  If you change to `open = "open"` then you will see text in the sidebar.

### Session Info

<details>
<pre><code>
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       macOS Ventura 13.4
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Asia/Taipei
 date     2023-06-15
 rstudio  2023.06.0+421 Mountain Hydrangea (desktop)
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 brio          1.1.3      2021-11-30 [1] CRAN (R 4.2.0)
 bsicons       0.1        2022-11-22 [1] CRAN (R 4.2.0)
 bslib       * 0.5.0.9000 2023-06-15 [1] Github (rstudio/bslib@f1efd83)
 cachem        1.0.8      2023-05-01 [1] CRAN (R 4.2.0)
 callr         3.7.3      2022-11-02 [1] CRAN (R 4.2.0)
 cli           3.6.1      2023-03-23 [1] CRAN (R 4.2.0)
 crayon        1.5.2      2022-09-29 [1] CRAN (R 4.2.0)
 devtools    * 2.4.5      2022-10-11 [1] CRAN (R 4.2.0)
 digest        0.6.31     2022-12-11 [1] CRAN (R 4.2.0)
 ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.2.0)
 fastmap       1.1.1      2023-02-24 [1] CRAN (R 4.2.0)
 fs            1.6.2      2023-04-25 [1] CRAN (R 4.2.0)
 gitcreds      0.1.2      2022-09-08 [1] CRAN (R 4.2.0)
 glue          1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
 htmltools     0.5.5      2023-03-23 [1] CRAN (R 4.2.0)
 htmlwidgets   1.6.2      2023-03-17 [1] CRAN (R 4.2.0)
 httpuv        1.6.11     2023-05-11 [1] CRAN (R 4.2.0)
 jquerylib     0.1.4      2021-04-26 [1] CRAN (R 4.2.0)
 jsonlite      1.8.5      2023-06-05 [1] CRAN (R 4.2.0)
 later         1.3.1      2023-05-02 [1] CRAN (R 4.2.0)
 lifecycle     1.0.3      2022-10-07 [1] CRAN (R 4.2.0)
 magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
 memoise       2.0.1      2021-11-26 [1] CRAN (R 4.2.0)
 mime          0.12       2021-09-28 [1] CRAN (R 4.2.0)
 miniUI        0.1.1.1    2018-05-18 [1] CRAN (R 4.2.0)
 pkgbuild      1.4.1      2023-06-14 [1] CRAN (R 4.2.2)
 pkgload       1.3.2      2022-11-16 [1] CRAN (R 4.2.0)
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.2.0)
 processx      3.8.1      2023-04-18 [1] CRAN (R 4.2.0)
 profvis       0.3.8      2023-05-02 [1] CRAN (R 4.2.0)
 promises      1.2.0.1    2021-02-11 [1] CRAN (R 4.2.0)
 ps            1.7.5      2023-04-18 [1] CRAN (R 4.2.0)
 purrr         1.0.1      2023-01-10 [1] CRAN (R 4.2.0)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.2.0)
 Rcpp          1.0.10     2023-01-22 [1] CRAN (R 4.2.0)
 remotes       2.4.2      2021-11-30 [1] CRAN (R 4.2.0)
 rlang         1.1.1      2023-04-28 [1] CRAN (R 4.2.0)
 rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.2.0)
 sass          0.4.6      2023-05-03 [1] CRAN (R 4.2.2)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
 shiny       * 1.7.4      2022-12-15 [1] CRAN (R 4.2.0)
 stringi       1.7.12     2023-01-11 [1] CRAN (R 4.2.0)
 stringr       1.5.0      2022-12-02 [1] CRAN (R 4.2.0)
 testthat    * 3.1.8      2023-05-04 [1] CRAN (R 4.2.0)
 urlchecker    1.0.1      2021-11-30 [1] CRAN (R 4.2.0)
 usethis     * 2.2.0      2023-06-06 [1] CRAN (R 4.2.0)
 vctrs         0.6.3      2023-06-14 [1] CRAN (R 4.2.2)
 xtable        1.8-4      2019-04-21 [1] CRAN (R 4.2.0)

 [1] /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
</code></pre>
</details>

**Comment by gadenbuie** [comment]
Hi @michael-dewar, thanks for opening the issue.

The very quick fix for your problem is to disable `suspendWhenHidden` for the `text` output.

```r
server <- function(input, output, session) {
  output$text <- renderText("Hello")
  outputOptions(output, "text", suspendWhenHidden = FALSE)
}
```

I agree, though, that we should handle this in the sidebar logic. I'll look into this to see what we can do.

**Comment by michael-dewar** [comment]
Works great, thanks a lot for this!
