### ISSUE TITLE
Put htmldependencies into individual folders

### ISSUE THREAD

**Issue by schloerke** [rstudio/bslib#642]
When bundling, we should either remove the sourcemap hint or put the grouped files into individual folders. 

When making an htmldependency, we can not include extra files directly, only through "allFiles = TRUE". So by having them in individual folders, we can expose the source map without copying all other js/map files for each dependency

- [ ] Nest folders
- [ ] Update dependency folder values

**Comment by gadenbuie** [comment]
Agreed, I've had this as a mental note for a while. Also related to #628
