### ISSUE TITLE
page_navbar collaspible=TRUE unexpected behaviour

### ISSUE THREAD

**Issue by ideusoes** [rstudio/bslib#663]
The collapsible parameter of the page_navbar function states :

TRUE to automatically collapse the navigation elements into a menu when the width of the browser is less than 940 pixels (useful for viewing on smaller touchscreen device)

However I am running an modularized app using page_navbar and a collection of nav_panel and the collapse breakpoint occurs between 575 and 576 pixels.

Example :
```r
library(bslib)

ui <- fluidPage(
  page_navbar(
    title = "Test",
    nav_spacer(),
    # Onglets
    nav_panel("Test nav 1", h1("home")),
    nav_panel("Test nav 2", h1("test")),
    nav_spacer(),
    collapsible = TRUE,
    fluid = TRUE,
    window_title = "Test"
  )
)
server <- function(input, output, session) {
}

shinyApp(ui = ui, server = server)

```
Only solution I could think of is using shinyjs to manually add navbar-expand-lg to the nav selector but that's a bit hacky...

**Comment by gadenbuie** [comment]
Hi @ideusoes and thanks for flagging this for us! `page_navbar()` and `navset_bar()` in bslib both inherit the documentation for `collapsible` from `shiny::navbarPage()`. Unfortunately, I think that documentation was overly specific. The breakpoint where the expanded navbar becomes collapsed has changed between Bootstrap versions: it's 940px in BS3 and 576px in BS4+.

You can see this by running the code in your example but changing the Bootstrap `version` from `3` to `4` or `5`. (And note that I removed the extra `fluidPage()` wrapper around your `ui`.)

```r
library(shiny)
library(bslib)

ui <- page_navbar(
  theme = bs_theme(4),
  title = "Test",
  nav_spacer(),
  # Onglets
  nav_panel("Test nav 1", h1("home")),
  nav_panel("Test nav 2", h1("test")),
  nav_spacer(),
  collapsible = TRUE,
  fluid = TRUE,
  window_title = "Test"
)

server <- function(input, output, session) {
}

shinyApp(ui = ui, server = server)
```

Our navset code generically attempts to cover all three major Bootstrap versions. So you're welcome to add the `navbar-expand-lg` if that solves your problem, but note that it may not work perfectly.

If you want to do this on the server-side, you can use `htmltools::tagAppendAttributes()` like this:

```r
ui <- htmltools::tagAppendAttributes(
  ui,
  class = "navbar-expand-lg",
  .cssSelector = ".navbar-static-top"
)
```

**Comment by ideusoes** [comment]
Hi @gadenbuie, thank you for the answer, I did not catch the breakpoint change between the versions.
I am using golem for my app but the htmltools fix still worked like a charm on the module call.
Cheers!
