### ISSUE TITLE
Sidebar's `aria-expanded` attribute does not change in Firefox

### ISSUE THREAD

**Issue by schloerke** [rstudio/bslib#696]
(low priority)

## Describe the problem

When collapsing a sidebar, the `aria-expanded` attribute does not change its value in Firefox.

![firefox does not change aria-expanded attribute](https://github.com/rstudio/bslib/assets/93231/ce864928-38db-4607-8c16-7383e4808258)

Reprex python app: https://github.com/rstudio/py-shiny/blob/4d0e5ee25606fa40b033022c85659a3767e5f0e2/shiny/experimental/api-examples/sidebar/app.py

### Session Info

Found in rstudio/py-shiny@4d0e5ee25606fa40b033022c85659a3767e5f0e2 which includes rstudio/bslib@175ad4624b9a1ede4130ebb92042f8da12eb7d70

cc @karangattu

**Comment by gadenbuie** [comment]
TIL [Firefox doesn't support `.ariaExpanded`](https://caniuse.com/mdn-api_element_ariaexpanded) in the Element API. This is an easy fix.
