### ISSUE TITLE
Upgrade Bootstrap from 5.2 to 5.3

### ISSUE THREAD

**Issue by ctrlxctrlc** [rstudio/bslib#743]
[Bootstrap 5.3](https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/) has been stable since May 30, 2023. Color modes functionality will simplify theming for those trying to develop in a Bootstrap (as opposed to `bslib`) centric manner.

**Comment by gadenbuie** [comment]
Thanks @ctrlxctrlc. Despite not having an open issue (we do now, thanks!), this is very much on our radar and is currently planned for the next release of bslib (the release after the one we're working on sending to CRAN right now).
