### ISSUE TITLE
Image in title bar removes formatting

### ISSUE THREAD

**Issue by awcm0n** [rstudio/bslib#759]
Placing an image in the title removes all formatting of the title bar.

```r
title =
  div(
    img(
      src = "my_logo.png",
      height = 60,
      width = 60,
      style = "margin:10px 10px"
    ),
    PAGE_TITLE
  )
```

**Comment by gadenbuie** [comment]
Are you referring to `title` in `page_sidebar()` or `layout_sidebar()` (or somewhere else I'm forgetting at the moment)?

**Comment by awcm0n** [comment]
I'm referring to `page_sidebar()`:

```r
page_sidebar(
  
  theme = bs_theme(
    version = 5,
    preset = "cosmo",
    primary = "#686a7e",
    `enable-rounded` = TRUE
  ),
  
  # title = "CTSI Evaluation",
  
  # REMOVES FORMATTING OF TITLE BAR
  title =  div(img(
    src = "logo_ctsi.png",
    height = 60,
    width = 60,
    style = "margin:5px 5px"
  ), "CTSI Evaluation"),
...
)
```
<img width="357" alt="title = 'CTSI Evaluation'" src="https://github.com/rstudio/bslib/assets/29875025/1c747546-91d9-4369-8940-c0e9ada1f719">

<img width="376" alt="With logo" src="https://github.com/rstudio/bslib/assets/29875025/db95eb43-a39f-4fbd-8f80-a983b3ef4f16">
