### ISSUE TITLE
Revisit/update page reference docs

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#808]
It feels like page references should gain more explanation and be reorganized as:

### Dashboards

* `page_sidebar()`
* `page_navbar()`

### Filled page

* `page_fillable()`

### Basic pages

* `page_fixed()`
* `page_fluid()`
* `page()`

**Comment by gadenbuie** [comment]
Need to pull out `page_fillable()` and `page_navar()` from the `page()` docs.
