### ISSUE TITLE
How to do vertical multi-page navigation?

### ISSUE THREAD

**Issue by daattali** [rstudio/bslib#835]
When wanting to create an app with multiple pages/tabs, the two most common options are to either have the tabs along the top horizontally, or along the left side vertically.

In original shiny, horizontal tabs could be achieved with `navbarPage()`, and vertical tabs could be done with `navlistPanel()`. You could also use {shinydashboard} for a vertical navbar.

In bs4, there was {bs4Dash}.

With {bslib} I haven't found an easy way to replicate that structure.

**Comment by gadenbuie** [comment]
We do intend to support sidebar navigation and plan to tackle the feature in the next release (after we finish up the release for the current cycle of work). You can track progress in https://github.com/rstudio/bslib/issues/585

**Comment by cpsievert** [comment]
> vertical tabs could be done with navlistPanel().

Just as a side note, there is already a "modern equivalent" of this provided by `bslib::navset_pill_list()`, but as @gadenbuie mentioned, we'd like to also have an answer for sidebar navigation
