### ISSUE TITLE
Using sidebar blocks custom JS scroll eventListeners

### ISSUE THREAD

**Issue by DavZim** [rstudio/bslib#836]
## Describe the problem

I have custom javascript code which adds scroll and click eventListeners to add/remove classes to the navbar (the idea behind them is to change the navbar color when the user scrolls down and is not at the top anymore to have a similar navbar/header effect to [Titan](https://themewagon.github.io/titan/index_portfolio.html)).

When I have a `page_navbar()` without a sidebar, the code below works as expected, when I include the sidebar, I would expect to still have the same effects, but the scroll events do not work anymore.

In the code below, I would expect the navbar to toggle a red background on every click (works with and without sidebar) and when I scroll the navbar should have a blue background color when the user is not on top, which only works when I don't use a sidebar.

Note that I see the console-logs that both JS snippets were found, but I never see "Event Scroll" in the logs when I use a sidebar.

```r
library(shiny)
library(bslib)
sapply(c("shiny", "bslib"), packageVersion)
#> $shiny
#> [1] 1 7 5
#>
#> $bslib
#> [1]    0    5    1 9000

css <- "body { padding-top: 55px !important; }
navbar.navbar-red { background-color: red !important; }
.navbar.navbar-blue { background-color: blue !important; }"

js_scroll <- '
console.log("Found JS Scroll");
document.addEventListener("scroll", function() {
  console.log("Event Scroll");
  var navbar = document.querySelector(".navbar");
  navbar.classList.toggle("navbar-blue", window.scrollY != 0);
});
'

js_click <- '
console.log("Found JS Click");
document.addEventListener("click", function() {
  console.log("Event Click");
  let navbar = document.querySelector(".navbar");
  navbar.classList.toggle("navbar-red");
});
'

filler <- div(style = "height: 200vh; background-color: lightgray;", "Filler")

ui <- page_navbar(
  position = "fixed-top",
  sidebar = sidebar("Sidebar"),  # commenting this line out and it works like expected: blue navbar when scrolled down!
  nav_panel("Page 1", "Page 1 content", filler),
  nav_panel("Page 2", "Page 2 content", filler),
  
  header = tags$head(tags$style(css),
                     tags$script(HTML(js_click)),
                     tags$script(HTML(js_scroll)))
)

shinyApp(ui, server = function(input, output, session) {})
```

### Session Info

<details>
<pre><code>
> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16)
 os       Ubuntu 22.04.3 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2023-10-16
 rstudio  2023.06.2+561.pro5 Mountain Hydrangea (server)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 bsicons       0.1.1      2023-08-11 [1] RSPM (R 4.3.0)
 bslib       * 0.5.1.9000 2023-10-16 [1] Github (rstudio/bslib@f4a36e8)
 cachem        1.0.8      2023-05-01 [2] RSPM (R 4.3.0)
 callr         3.7.3      2022-11-02 [2] RSPM (R 4.3.0)
 cli           3.6.1      2023-03-23 [2] RSPM (R 4.3.0)
 crayon        1.5.2      2022-09-29 [2] RSPM (R 4.3.0)
 devtools      2.4.5      2022-10-11 [1] RSPM (R 4.3.0)
 digest        0.6.33     2023-07-07 [2] RSPM (R 4.3.0)
 ellipsis      0.3.2      2021-04-29 [2] RSPM (R 4.3.0)
 fansi         1.0.4      2023-01-22 [2] RSPM (R 4.3.0)
 fastmap       1.1.1      2023-02-24 [2] RSPM (R 4.3.0)
 fs            1.6.3      2023-07-20 [2] RSPM (R 4.3.0)
 glue          1.6.2      2022-02-24 [2] RSPM (R 4.3.0)
 htmltools     0.5.6.9001 2023-10-12 [1] Github (rstudio/htmltools@9436031)
 htmlwidgets   1.6.2      2023-03-17 [2] RSPM (R 4.3.0)
 httpuv        1.6.11     2023-05-11 [2] RSPM (R 4.3.0)
 jquerylib     0.1.4      2021-04-26 [2] RSPM (R 4.3.0)
 jsonlite      1.8.7      2023-06-29 [2] RSPM (R 4.3.0)
 later         1.3.1      2023-05-02 [2] RSPM (R 4.3.0)
 lifecycle     1.0.3      2022-10-07 [2] RSPM (R 4.3.0)
 magrittr      2.0.3      2022-03-30 [2] RSPM (R 4.3.0)
 memoise       2.0.1      2021-11-26 [2] RSPM (R 4.3.0)
 mime          0.12       2021-09-28 [2] RSPM (R 4.3.0)
 miniUI        0.1.1.1    2018-05-18 [1] RSPM (R 4.3.0)
 pillar        1.9.0      2023-03-22 [2] RSPM (R 4.3.0)
 pkgbuild      1.4.2      2023-06-26 [2] RSPM (R 4.3.0)
 pkgconfig     2.0.3      2019-09-22 [2] RSPM (R 4.3.0)
 pkgload       1.3.2.1    2023-07-08 [2] RSPM (R 4.3.0)
 prettyunits   1.1.1      2020-01-24 [2] RSPM (R 4.3.0)
 processx      3.8.2      2023-06-30 [2] RSPM (R 4.3.0)
 profvis       0.3.8      2023-05-02 [2] RSPM (R 4.3.0)
 promises      1.2.1      2023-08-10 [2] RSPM (R 4.3.0)
 ps            1.7.5      2023-04-18 [2] RSPM (R 4.3.0)
 purrr         1.0.2      2023-08-10 [2] RSPM (R 4.3.0)
 R6            2.5.1      2021-08-19 [2] RSPM (R 4.3.0)
 Rcpp          1.0.11     2023-07-06 [2] RSPM (R 4.3.0)
 remotes       2.4.2.1    2023-07-18 [1] RSPM (R 4.3.0)
 rlang         1.1.1      2023-04-28 [2] RSPM (R 4.3.0)
 rsconnect     1.0.2      2023-08-17 [2] RSPM (R 4.3.0)
 rstudioapi    0.15.0     2023-07-07 [2] RSPM (R 4.3.0)
 sass          0.4.7      2023-07-15 [2] RSPM (R 4.3.0)
 sessioninfo   1.2.2      2021-12-06 [1] RSPM (R 4.3.0)
 shiny       * 1.7.5      2023-08-12 [2] RSPM (R 4.3.0)
 stringi       1.7.12     2023-01-11 [2] RSPM (R 4.3.0)
 stringr       1.5.0      2022-12-02 [2] RSPM (R 4.3.0)
 tibble        3.2.1      2023-03-20 [2] RSPM (R 4.3.0)
 urlchecker    1.0.1      2021-11-30 [1] RSPM (R 4.3.0)
 usethis       2.2.2      2023-07-06 [1] RSPM (R 4.3.0)
 utf8          1.2.3      2023-01-31 [2] RSPM (R 4.3.0)
 vctrs         0.6.3      2023-06-14 [2] RSPM (R 4.3.0)
 xtable        1.8-4      2019-04-21 [2] RSPM (R 4.3.0)

 [1] /home/dazimme/R/x86_64-pc-linux-gnu-library/4.3
 [2] /usr/r-library/admin-library/4.3
 [3] /opt/R/4.3.1/lib/R/library

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
</code></pre>
</details>

**Comment by gadenbuie** [comment]
Hi @DavZim, thanks for the issue and the reprex! The problem is that when `page_navbar()` has a global sidebar, we add a sidebar layout and move the panel content into the main area of the sidebar layout. A consequence of this is that it's not longer the page that's scrolling, but rather the `.main` content area of that sidebar layout. The selector for that is `.bslib-page-navbar > div > .bslib-sidebar-layout > .main`.

This mean a few things:

1. When the global sidebar is used, you should watch for scrolling on its `.main` element.
2. Instead of looking at `window.scrollY`, you should compare `main.scrollTop` to its parent element's `scrollTop`.
3. You need to add the event listener after the DOM is ready, or at least after the main layout has been rendered. If your JavaScript is loaded in `<head>`, you can wait for `DOMContentLoaded`.

Here's a bit of JS that accounts for all of the above:

```js
console.log("Found JS Scroll");
$(document).ready(function() {
  const main = document.querySelector(
    ".bslib-page-navbar > div > .bslib-sidebar-layout > .main"
  );
  const watchElement = main ? main : document;
  watchElement.addEventListener("scroll", function() {
    console.log("Event Scroll: " + window.scrollY + "px");
    const navbar = document.querySelector(".navbar");
    const toggleNavClass = main
      ? main.scrollTop != main.parentElement.scrollTop
      : window.scrollY != 0;
    navbar.classList.toggle("navbar-blue", toggleNavClass);
  });
});
```

I added `window.scrollY` to the console log message so that you can see that it's constant with the sidebar layout.

**Comment by DavZim** [comment]
That looks wonderful. Thank you for the fast response and the good solution!
