### ISSUE TITLE
[docs] Update screenshots of sidebar in dashboard pages

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#838]
As pointed out in https://github.com/rstudio/bslib/pull/798#issuecomment-1766611172 the left gutter is not quite right. We need to create new screenshots before release.

https://rstudio.github.io/bslib/articles/dashboards/index.html

**Comment by cpsievert** [comment]
Generation of these screenshots (should be) automated, and I'm sure #814 will fix this?
