### ISSUE TITLE
On desktop, a scrolling `sidebar()`'s toggle icon can overlap with contents

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bslib#850]
```r
x <- sliderInput("foo", "bar", 0, 1, 0.5)

page_sidebar(
  sidebar = sidebar(!!!replicate(20, x, simplify = F))
) |> shinyApp(\(...) {})
```

<img width="702" alt="Screenshot 2023-10-18 at 5 26 09 PM" src="https://github.com/rstudio/bslib/assets/1365941/7e6e29c9-bf30-464e-90e9-40ccb796e939">

**Comment by gadenbuie** [comment]
Oddly, I'm not able to reproduce this. For me, with latest `main` and in all three major browsers it looks like this:

![image](https://github.com/rstudio/bslib/assets/5420529/3906ea7b-263b-4ca5-898d-937ae306fab7)

I agree it's not _the greatest_ but I don't see the overlap shown in your screenshot unless I set `sidebar(padding = 0)`.

**Comment by cpsievert** [comment]
Yea, I can't seem to replicate either anymore -- must have been a caching thing 🤷
