### ISSUE TITLE
cannot create dynamic `nav_menu` 

### ISSUE THREAD

**Issue by oude-gao** [rstudio/bslib#858]
Hi, I am trying to dynamically create multiple `nav_menu`s with a dataframe that I want to use to name the menus and provide some other values for arguments for `nav_menu()`. I got to the point where I have a list that contains these individual `nav_menu`s, but when I tried to `tagList()` it or just execute the list as part of the UI code, it throws an error message:

```
Error: Navigation containers expect a collection of `bslib::nav_panel()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
```

My code is below:

```r
nav_menu_items <- 
  tibble::tribble(
    ~title,    
    "title1",       
    "title2",     
    "title3", 
  )

l <- purrr::pmap(
  nav_menu_items,
  nav_menu
)

ui <- page_navbar(
  ...,
  tagList(l), ## this doesnt work
  l[[1]],
  l[[2]], 
  l[[3]] ## these will work
)
```

### Session Info

<details>
<pre><code>
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       Ubuntu 20.04.6 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  C.UTF-8
 ctype    C.UTF-8
 tz       America/New_York
 date     2023-10-23
 rstudio  2023.06.0+421.pro1 Mountain Hydrangea (server)
 pandoc   2.16.1 @ /usr/bin/pandoc

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 askpass       1.1     2019-01-13 [2] RSPM (R 4.2.0)
 bsicons       0.1.1   2023-08-11 [1] CRAN (R 4.2.2)
 bslib       * 0.5.1   2023-08-11 [1] CRAN (R 4.2.2)
 cachem        1.0.6   2021-08-19 [2] RSPM (R 4.2.0)
 callr         3.7.2   2022-08-22 [2] RSPM (R 4.2.0)
 cli           3.6.0   2023-01-09 [2] RSPM (R 4.2.0)
 colorspace    2.0-3   2022-02-21 [2] RSPM (R 4.2.0)
 crayon        1.5.2   2022-09-29 [2] RSPM (R 4.2.0)
 credentials   1.3.2   2021-11-29 [2] RSPM (R 4.2.0)
 devtools      2.4.5   2022-10-11 [2] RSPM (R 4.2.0)
 digest        0.6.31  2022-12-11 [2] RSPM (R 4.2.0)
 ellipsis      0.3.2   2021-04-29 [2] RSPM (R 4.2.0)
 fansi         1.0.3   2022-03-24 [2] RSPM (R 4.2.0)
 farver        2.1.1   2022-07-06 [2] RSPM (R 4.2.0)
 fastmap       1.1.0   2021-01-25 [2] RSPM (R 4.2.0)
 fs            1.6.1   2023-02-06 [2] RSPM (R 4.2.0)
 gert          1.9.1   2022-10-05 [2] RSPM (R 4.2.0)
 glue          1.6.2   2022-02-24 [2] RSPM (R 4.2.0)
 htmltools     0.5.4   2022-12-07 [2] RSPM (R 4.2.0)
 htmlwidgets   1.5.4   2021-09-08 [2] RSPM (R 4.2.0)
 httpuv        1.6.9   2023-02-14 [2] RSPM (R 4.2.0)
 jquerylib     0.1.4   2021-04-26 [2] RSPM (R 4.2.0)
 jsonlite      1.8.4   2022-12-06 [2] RSPM (R 4.2.0)
 later         1.3.0   2021-08-18 [2] RSPM (R 4.2.0)
 lifecycle     1.0.3   2022-10-07 [2] RSPM (R 4.2.0)
 magrittr      2.0.3   2022-03-30 [2] RSPM (R 4.2.0)
 memoise       2.0.1   2021-11-26 [2] RSPM (R 4.2.0)
 mime          0.12    2021-09-28 [2] RSPM (R 4.2.0)
 miniUI        0.1.1.1 2018-05-18 [2] RSPM (R 4.2.0)
 munsell       0.5.0   2018-06-12 [2] RSPM (R 4.2.0)
 openssl       2.0.5   2022-12-06 [2] RSPM (R 4.2.0)
 pillar        1.9.0   2023-03-22 [1] RSPM (R 4.2.0)
 pkgbuild      1.3.1   2021-12-20 [2] RSPM (R 4.2.0)
 pkgconfig     2.0.3   2019-09-22 [2] RSPM (R 4.2.0)
 pkgload       1.3.1   2022-10-28 [2] RSPM (R 4.2.0)
 prettyunits   1.1.1   2020-01-24 [2] RSPM (R 4.2.0)
 processx      3.8.0   2022-10-26 [2] RSPM (R 4.2.0)
 profvis       0.3.7   2020-11-02 [2] RSPM (R 4.2.0)
 promises      1.2.0.1 2021-02-11 [2] RSPM (R 4.2.0)
 ps            1.7.2   2022-10-26 [2] RSPM (R 4.2.0)
 purrr       * 0.3.5   2022-10-06 [2] RSPM (R 4.2.0)
 R6            2.5.1   2021-08-19 [2] RSPM (R 4.2.0)
 Rcpp          1.0.10  2023-01-22 [2] RSPM (R 4.2.0)
 remotes       2.4.2   2021-11-30 [2] RSPM (R 4.2.0)
 rlang         1.1.1   2023-04-28 [1] RSPM (R 4.2.0)
 rprojroot     2.0.3   2022-04-02 [2] RSPM (R 4.2.0)
 rsconnect     0.8.29  2023-01-09 [1] RSPM (R 4.2.0)
 rstudioapi    0.14    2022-08-22 [2] RSPM (R 4.2.0)
 sass          0.4.5   2023-01-24 [2] RSPM (R 4.2.0)
 scales        1.2.1   2022-08-20 [2] RSPM (R 4.2.0)
 sessioninfo   1.2.2   2021-12-06 [2] RSPM (R 4.2.0)
 shiny       * 1.7.4   2022-12-15 [2] RSPM (R 4.2.0)
 sourcetools   0.1.7-1 2023-02-01 [2] RSPM (R 4.2.0)
 stringi       1.7.12  2023-01-11 [2] RSPM (R 4.2.0)
 stringr       1.5.0   2022-12-02 [2] RSPM (R 4.2.0)
 sys           3.4.1   2022-10-18 [2] RSPM (R 4.2.0)
 tibble        3.2.1   2023-03-20 [1] RSPM (R 4.2.0)
 urlchecker    1.0.1   2021-11-30 [2] RSPM (R 4.2.0)
 usethis       2.1.6   2022-05-25 [2] RSPM (R 4.2.0)
 utf8          1.2.2   2021-07-24 [2] RSPM (R 4.2.0)
 vctrs         0.6.3   2023-06-14 [1] RSPM (R 4.2.0)
 withr         2.5.0   2022-03-03 [2] RSPM (R 4.2.0)
 xtable        1.8-4   2019-04-21 [2] RSPM (R 4.2.0)
</code></pre>
</details>

**Comment by gadenbuie** [comment]
Try using the [`!!!` splice operator](https://rlang.r-lib.org/reference/dyn-dots.html) from rlang:

```r
nav_menu_items <- 
  tibble::tribble(
    ~title,    
    "title1",       
    "title2",     
    "title3", 
  )

items <- purrr::pmap(
  nav_menu_items,
  nav_menu
)

ui <- page_navbar(!!!items)
```

**Comment by oude-gao** [comment]
Oh nice, thanks for the quick reply, worked like a charm!
