### ISSUE TITLE
When repeatedly refreshing the page with `sidebar(open = "desktop")` on mobile,  sidebar can sometimes be open

### ISSUE THREAD

**Issue by wch** [rstudio/bslib#878]
When a `page_sidebar()` is displayed on mobile, it seems to randomly settle on displaying the sidebar or main content. When I say random, though, I don't mean it's 50-50. I would say it lands on the sidebar about 5-10% of the time. 

This video shows me hitting the reload button repeatedly:

https://github.com/rstudio/bslib/assets/86978/762f3d1f-038a-42f8-a026-81d7dbea3dfb

**Comment by wch** [comment]
The first time I saw it happen wasn't on a refresh -- it was when I was just opening the app normally.

One thing that's a bit odd about my app is that the entire UI is dynamic -- the `<body>` tag itself is a special UI output. I wasn't able to reproduce the problem with normal static UI, in R or in Python. But I do believe this does point to a real issue in how the sidebar works.

In my test app, when the app is loaded or reloaded in the active, foreground tab, the starting with the sidebar open happens on a small proportion of cases. But when I open the page in a background tab, it starts with the sidebar open 100% of the time. Here is a video that demonstrates. First I hit the reload button 3 times, and then I go to the URL bar and press Cmd-Enter (which opens the page in a background tab) three times.

https://github.com/rstudio/bslib/assets/86978/4a0664ca-a9ec-4c94-8834-d3a3de796190

We don't have to solve this right now, but I do want to keep this issue open for future reference.

**Comment by cpsievert** [comment]
#908 should probably fix this (we still need to get it over to Python, though)
