### ISSUE TITLE
could not find function "value_box_theme"

### ISSUE THREAD

**Issue by antoine4ucsd** [rstudio/bslib#882]
sorry. must be straightforward but cannot find function value_box_theme
I have installed bslib 0.5.1

thank you for your help and this great package!

**Comment by gadenbuie** [comment]
Hi @antoine4ucsd, `value_box_theme()` was recently added and currently is in the dev version of bslib. I know it can be confusing because the bslib website shows the in-development documentation (I'm hoping to fix that soon). You can install the latest version of bslib with

```r
# install.packages("pak")
pak::pak("rstudio/bslib")
```

**Comment by antoine4ucsd** [comment]
thank you for being so responsive and congrats with the package.
