### ISSUE TITLE
`accordion_panel_insert` not working in modules

### ISSUE THREAD

**Issue by barnesparker** [rstudio/bslib#895]
## Describe the problem

`accordion_panel_insert` not working in modules. Not sure if I'm missing something

```r
library(shiny)
library(bslib)


accordionUI <- function(id) {
  ns <- NS(id)
  accordion(
    id = ns("accordion"),
    accordion_panel(
      "Control Panel",
      actionButton("add_panel_button", "Add Panel")
    )
  )
}

accordionServer <- function(id) {
  moduleServer(id, function(input, output, session) {

    observe({
      accordion_panel_insert(
        id = session$ns("accordion"),
        accordion_panel(
          "New Panel"
        ),
        session = session
      )
    }) |>
      bindEvent(input$add_panel_button)


  })
}


AccordionApp <- function() {
  ui <- page_navbar(
    sidebar = sidebar(
      accordionUI("mod_accordion")
    )
  )
  server <- function(input, output, session) {
    accordionServer("mod_accordion")
  }
  shinyApp(ui, server)
}

AccordionApp()


```

### Session Info

<details>
<pre><code>
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16)
 os       macOS Sonoma 14.0
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Denver
 date     2023-11-03
 rstudio  2023.09.1+494 Desert Sunflower (desktop)
 pandoc   NA

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────
 ! package     * version    date (UTC) lib source
 P bsicons       0.1.1      2023-08-11 [?] CRAN (R 4.3.0)
   bslib       * 0.5.1.9000 2023-11-04 [1] Github (rstudio/bslib@f574b9f)
 P cachem        1.0.8      2023-05-01 [?] RSPM (R 4.3.0)
 P callr         3.7.3      2022-11-02 [?] RSPM (R 4.3.0)
   cli           3.6.1      2023-03-23 [1] CRAN (R 4.3.0)
   crayon        1.5.2      2022-09-29 [1] CRAN (R 4.3.0)
 P devtools      2.4.5      2022-10-11 [?] CRAN (R 4.3.0)
 P digest        0.6.33     2023-07-07 [?] RSPM (R 4.3.0)
 P ellipsis      0.3.2      2021-04-29 [?] RSPM (R 4.3.0)
   fansi         1.0.5      2023-10-08 [1] CRAN (R 4.3.1)
 P fastmap       1.1.1      2023-02-24 [?] RSPM (R 4.3.0)
 P fs            1.6.3      2023-07-20 [?] RSPM (R 4.3.0)
   glue          1.6.2      2022-02-24 [1] CRAN (R 4.3.0)
   htmltools     0.5.7.9000 2023-11-04 [1] Github (rstudio/htmltools@7efa2d8)
 P htmlwidgets   1.6.2      2023-03-17 [?] CRAN (R 4.3.0)
 P httpuv        1.6.12     2023-10-23 [?] CRAN (R 4.3.1)
 P jquerylib     0.1.4      2021-04-26 [?] RSPM (R 4.3.0)
 P jsonlite      1.8.7      2023-06-29 [?] RSPM (R 4.3.0)
 P later         1.3.1      2023-05-02 [?] CRAN (R 4.3.0)
   lifecycle     1.0.3      2022-10-07 [1] CRAN (R 4.3.0)
   magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.3.0)
 P memoise       2.0.1      2021-11-26 [?] RSPM (R 4.3.0)
 P mime          0.12       2021-09-28 [?] RSPM (R 4.3.0)
 P miniUI        0.1.1.1    2018-05-18 [?] CRAN (R 4.3.0)
   pillar        1.9.0      2023-03-22 [1] CRAN (R 4.3.0)
 P pkgbuild      1.4.2      2023-06-26 [?] CRAN (R 4.3.0)
   pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.3.0)
 P pkgload       1.3.3      2023-09-22 [?] CRAN (R 4.3.1)
 P prettyunits   1.2.0      2023-09-24 [?] RSPM (R 4.3.0)
 P processx      3.8.2      2023-06-30 [?] RSPM (R 4.3.0)
 P profvis       0.3.8      2023-05-02 [?] CRAN (R 4.3.0)
 P promises      1.2.1      2023-08-10 [?] CRAN (R 4.3.0)
 P ps            1.7.5      2023-04-18 [?] RSPM (R 4.3.0)
   purrr         1.0.2      2023-08-10 [1] CRAN (R 4.3.0)
   R6            2.5.1      2021-08-19 [1] CRAN (R 4.3.0)
   Rcpp          1.0.11     2023-07-06 [1] CRAN (R 4.3.0)
 P remotes       2.4.2.1    2023-07-18 [?] RSPM (R 4.3.0)
   renv          1.0.3      2023-09-19 [1] CRAN (R 4.3.1)
   rlang         1.1.1      2023-04-28 [1] CRAN (R 4.3.0)
 P rstudioapi    0.15.0     2023-07-07 [?] RSPM (R 4.3.0)
 P sass          0.4.7      2023-07-15 [?] RSPM (R 4.3.0)
 P sessioninfo   1.2.2      2021-12-06 [?] CRAN (R 4.3.0)
 P shiny       * 1.7.5.1    2023-10-14 [?] CRAN (R 4.3.1)
   stringi       1.7.12     2023-01-11 [1] CRAN (R 4.3.0)
   stringr       1.5.0      2022-12-02 [1] CRAN (R 4.3.0)
   tibble        3.2.1      2023-03-20 [1] CRAN (R 4.3.0)
 P urlchecker    1.0.1      2021-11-30 [?] CRAN (R 4.3.0)
 P usethis       2.2.2      2023-07-06 [?] RSPM (R 4.3.0)
   utf8          1.2.4      2023-10-22 [1] CRAN (R 4.3.1)
   vctrs         0.6.4      2023-10-12 [1] CRAN (R 4.3.1)
   withr         2.5.1      2023-09-26 [1] CRAN (R 4.3.1)
 P xtable        1.8-4      2019-04-21 [?] RSPM (R 4.3.0)

 [1] /Users/parkerbarnesplinth/Documents/Plinth Projects/komodo_heor/apps/heor_dashboard/renv/library/R-4.3/aarch64-apple-darwin20
 [2] /Users/parkerbarnesplinth/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/aarch64-apple-darwin20/ac5c2659

 P ── Loaded and on-disk path mismatch.

─────────────────────────────────────────────────────────────────────────────────────────────────────────
</code></pre>
</details>

**Comment by gadenbuie** [comment]
Hi @barnesparker and thanks for the reprex! There are two small bugs in your example that boil down to applying `ns()` in the right place.

First, you need to use `ns()` around the `inputId` of the action button so that it's associated with your `accordionUI()` module:

```patch
  accordion(
    id = ns("accordion"),
    accordion_panel(
      "Control Panel",
-     actionButton("add_panel_button", "Add Panel")
+     actionButton(ns("add_panel_button"), "Add Panel")
    )
  )
```

Second, and conversely, inside the server function, you don't need to use `session$ns()` to identify the accordion id in `accordion_panel()`, since shiny will take care of this for you:

```patch
      accordion_panel_insert(
-       id = session$ns("accordion"),
+       id = "accordion",
        accordion_panel(
          "New Panel"
        ),
        session = session
      )
```

After that, clicking the button should add a new panel!

One more small note, you also don't need to set `session = session` in `accordion_panel_insert()`. In all bslib functions that take `session`, we have a default argument that will find the appropriate `session` object for you (but we've kept the argument for advanced/edge cases).

**Comment by barnesparker** [comment]
Ahh it was the mismatch of the `accordion` ids that was ultimately my issue. The missing `ns` in the `actionButton` was just a mistake I made when creating the reprex. Thank you!!

**Comment by barnesparker** [comment]
Ahh it was the mismatch of the `accordion` ids that was ultimately my issue. The missing `ns` in the `actionButton` was just a mistake I made when creating the reprex. Thank you!!
