### ISSUE TITLE
page_navbar() causes problems in widgets unlike navbarPage()

### ISSUE THREAD

**Issue by benubah** [rstudio/bslib#934]
`bslib` is very flexible and feature-rich and so:

I started moving my project from standard `shiny`, `shinydashboard` to `bslib` and I've found out that several things break in `bslib` that would normally work in standard `shiny` and `shinydashboard`.

Just one example of these issues shown in the reprex below. Using `navbarPage()` from `shiny` gives expected results in the select input values.

![image](https://github.com/rstudio/bslib/assets/11357251/df428fb4-0edd-4e04-a17c-e195e9cc6ee5)

But changing to `page_navbar()` (or any `page_*` wrappers) from `bslib` causes the select inputs to display their values up to 10 times as in the screenshot below:
![image](https://github.com/rstudio/bslib/assets/11357251/4824133c-c107-419a-9b3b-5194626b78f1)

```r
library(shiny)
library(bslib)
library(shinyWidgets)

data("mpg", package = "ggplot2")
ui <- navbarPage(
  fluidRow(
    column(
      width = 4,
      tags$h3("Filter data with picker group"),
      pickerGroupUI(
        id = "my-filters",
        inline = FALSE,
        params = list(
          manufacturer = list(inputId = "manufacturer", label = "Manufacturer:"),
          model = list(inputId = "model", label = "Model:"),
          trans = list(inputId = "trans", label = "Trans:"),
          class = list(inputId = "class", label = "Class:")
        )
      )
    ),
    column(
      width = 8,
      DT::dataTableOutput(outputId = "table")
    )
  )
)
server <- function(input, output, session) {
  res_mod <- callModule(
    module = pickerGroupServer,
    id = "my-filters",
    data = mpg[1:100, ],
    vars = c("manufacturer", "model", "trans", "class")
  )
  output$table <- DT::renderDataTable(res_mod())
}
shinyApp(ui, server)
```

```r
library(shiny)
library(bslib)
library(shinyWidgets)

data("mpg", package = "ggplot2")
ui <- page_navbar(
  fluidRow(
    column(
      width = 4,
      tags$h3("Filter data with picker group"),
      pickerGroupUI(
        id = "my-filters",
        inline = FALSE,
        params = list(
          manufacturer = list(inputId = "manufacturer", label = "Manufacturer:"),
          model = list(inputId = "model", label = "Model:"),
          trans = list(inputId = "trans", label = "Trans:"),
          class = list(inputId = "class", label = "Class:")
        )
      )
    ),
    column(
      width = 8,
      DT::dataTableOutput(outputId = "table")
    )
  )
)

server <- function(input, output, session) {
  res_mod <- callModule(
    module = pickerGroupServer,
    id = "my-filters",
    data = mpg[1:100, ],
    vars = c("manufacturer", "model", "trans", "class")
  )
  output$table <- DT::renderDataTable(res_mod())
}
shinyApp(ui, server)
```

### Session Info

<details>
<pre><code>
─ Session info ────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 date     2023-12-06
 rstudio  2023.06.2+561 Mountain Hydrangea (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cachem        1.0.8   2023-05-01 [1] CRAN (R 4.3.1)
 callr         3.7.3   2022-11-02 [1] CRAN (R 4.3.1)
 cli           3.6.1   2023-03-23 [1] CRAN (R 4.3.1)
 crayon        1.5.2   2022-09-29 [1] CRAN (R 4.3.1)
 devtools      2.4.5   2022-10-11 [1] CRAN (R 4.3.2)
 digest        0.6.33  2023-07-07 [1] CRAN (R 4.3.1)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.3.1)
 fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.3.1)
 fs            1.6.3   2023-07-20 [1] CRAN (R 4.3.1)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.3.1)
 htmltools     0.5.7   2023-11-03 [1] CRAN (R 4.3.2)
 htmlwidgets   1.6.2   2023-03-17 [1] CRAN (R 4.3.1)
 httpuv        1.6.11  2023-05-11 [1] CRAN (R 4.3.1)
 later         1.3.1   2023-05-02 [1] CRAN (R 4.3.1)
 lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.3.2)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.3.1)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.3.1)
 mime          0.12    2021-09-28 [1] CRAN (R 4.3.0)
 miniUI        0.1.1.1 2018-05-18 [1] CRAN (R 4.3.2)
 pkgbuild      1.4.2   2023-06-26 [1] CRAN (R 4.3.1)
 pkgload       1.3.3   2023-09-22 [1] CRAN (R 4.3.1)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.3.1)
 processx      3.8.2   2023-06-30 [1] CRAN (R 4.3.1)
 profvis       0.3.8   2023-05-02 [1] CRAN (R 4.3.2)
 promises      1.2.1   2023-08-10 [1] CRAN (R 4.3.1)
 ps            1.7.5   2023-04-18 [1] CRAN (R 4.3.1)
 purrr         1.0.2   2023-08-10 [1] CRAN (R 4.3.1)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.3.1)
 Rcpp          1.0.11  2023-07-06 [1] CRAN (R 4.3.1)
 remotes       2.4.2.1 2023-07-18 [1] CRAN (R 4.3.1)
 rlang         1.1.2   2023-11-04 [1] CRAN (R 4.3.2)
 rstudioapi    0.15.0  2023-07-07 [1] CRAN (R 4.3.1)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.3.2)
 shiny         1.7.5   2023-08-12 [1] CRAN (R 4.3.1)
 stringi       1.7.12  2023-01-11 [1] CRAN (R 4.3.0)
 stringr       1.5.0   2022-12-02 [1] CRAN (R 4.3.1)
 urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.3.2)
 usethis       2.2.2   2023-07-06 [1] CRAN (R 4.3.2)
 vctrs         0.6.3   2023-06-14 [1] CRAN (R 4.3.1)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.3.1)

</code></pre>
</details>

**Comment by cpsievert** [comment]
`page_navbar()` defaults to Bootstrap 5 whereas `navbarPage()` defaults to Bootstrap 5. It's highly likely that the the widgets you're using aren't compatible with Bootstrap 5, and a fix should come from `{shinyWidgets}`, not `{bslib}` , so I'll be closing this issue. 

Please consider creating a minimal reproducible example for each problem/widget, similar to this issue https://github.com/dreamRs/shinyWidgets/issues/630
