### ISSUE TITLE
`layout_column_wrap` Outputs Cards in One-Column Format when Cards are Passed as a List

### ISSUE THREAD

**Issue by wish1832** [rstudio/bslib#948]
## Describe the problem

 I am attempting to define a set of cards iteratively via lapply, and display the results in a two-column format using `layout_column_wrap`. When I pass the set of cards as a list, the cards always display in one column, regardless of what I set for `width`. 

```r
library(bslib)

cards <- 
  lapply(
    1:4,
    function(i){
      card(paste0("Card ", i))
      }
  )

# Should output cards in two columns, but displays a single column
layout_column_wrap(width = 1/2, height = 300, cards)
```

The reprex below demonstrates that passing the cards as a list causes the layout issue. The column layout issue also occurs when using `htmltools::tagList`.

```r 
x <- card(
  "A simple card"
  )

# Correct number of columns
layout_column_wrap(width = 1/2, height = 300, x, x, x)

# Appears on one column
layout_column_wrap(width = 1/2, height = 300, list(x, x, x))

layout_column_wrap(width = 1/2, height = 300, htmltools::tagList(x, x, x))
```

### Session Info

<details>
<pre><code>
─ Session info ──────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.2 (2023-10-31)
 os       macOS Sonoma 14.1.2
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Denver
 date     2023-12-18
 rstudio  2023.09.1+494 Desert Sunflower (desktop)
 pandoc   NA

─ Packages ──────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 bslib       * 0.6.1.9000 2023-12-18 [1] Github (rstudio/bslib@866e9ec)
 cachem        1.0.8      2023-05-01 [1] CRAN (R 4.3.0)
 cli           3.6.2      2023-12-11 [1] CRAN (R 4.3.1)
 devtools      2.4.5      2022-10-11 [1] CRAN (R 4.3.0)
 digest        0.6.33     2023-07-07 [1] CRAN (R 4.3.0)
 ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.3.0)
 fansi         1.0.6      2023-12-08 [1] CRAN (R 4.3.1)
 fastmap       1.1.1      2023-02-24 [1] CRAN (R 4.3.0)
 fs            1.6.3      2023-07-20 [1] CRAN (R 4.3.0)
 glue          1.6.2      2022-02-24 [1] CRAN (R 4.3.0)
 htmltools     0.5.7      2023-11-03 [1] CRAN (R 4.3.1)
 htmlwidgets   1.6.4      2023-12-06 [1] CRAN (R 4.3.1)
 httpuv        1.6.13     2023-12-06 [1] CRAN (R 4.3.1)
 jquerylib     0.1.4      2021-04-26 [1] CRAN (R 4.3.0)
 jsonlite      1.8.8      2023-12-04 [1] CRAN (R 4.3.1)
 knitr         1.45       2023-10-30 [1] CRAN (R 4.3.1)
 later         1.3.2      2023-12-06 [1] CRAN (R 4.3.1)
 lifecycle     1.0.4      2023-11-07 [1] CRAN (R 4.3.1)
 magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.3.0)
 memoise       2.0.1      2021-11-26 [1] CRAN (R 4.3.0)
 mime          0.12       2021-09-28 [1] CRAN (R 4.3.0)
 miniUI        0.1.1.1    2018-05-18 [1] CRAN (R 4.3.0)
 pillar        1.9.0      2023-03-22 [1] CRAN (R 4.3.0)
 pkgbuild      1.4.3      2023-12-10 [1] CRAN (R 4.3.1)
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.3.0)
 pkgload       1.3.3      2023-09-22 [1] CRAN (R 4.3.1)
 profvis       0.3.8      2023-05-02 [1] CRAN (R 4.3.0)
 promises      1.2.1      2023-08-10 [1] CRAN (R 4.3.0)
 purrr         1.0.2      2023-08-10 [1] CRAN (R 4.3.0)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.3.0)
 Rcpp          1.0.11     2023-07-06 [1] CRAN (R 4.3.0)
 remotes       2.4.2.1    2023-07-18 [1] CRAN (R 4.3.0)
 rlang         1.1.2      2023-11-04 [1] CRAN (R 4.3.1)
 rstudioapi    0.15.0     2023-07-07 [1] CRAN (R 4.3.0)
 sass          0.4.8      2023-12-06 [1] CRAN (R 4.3.1)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.3.0)
 shiny         1.8.0      2023-11-17 [1] CRAN (R 4.3.1)
 stringi       1.8.3      2023-12-11 [1] CRAN (R 4.3.1)
 stringr       1.5.1      2023-11-14 [1] CRAN (R 4.3.1)
 tibble        3.2.1      2023-03-20 [1] CRAN (R 4.3.0)
 urlchecker    1.0.1      2021-11-30 [1] CRAN (R 4.3.0)
 usethis       2.2.2      2023-07-06 [1] CRAN (R 4.3.0)
 utf8          1.2.4      2023-10-22 [1] CRAN (R 4.3.1)
 vctrs         0.6.5      2023-12-01 [1] CRAN (R 4.3.1)
 xfun          0.41       2023-11-01 [1] CRAN (R 4.3.1)
 xtable        1.8-4      2019-04-21 [1] CRAN (R 4.3.0)

 [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library

─────────────────────────────────────────────────────────────────────────────
</code></pre>
</details>

**Comment by cpsievert** [comment]
You can "splice" in the cards this way

```r
layout_column_wrap(width = 1/2, !!!cards)
```

which is equivalent to 

```r
layout_column_wrap(width = 1/2, cards[[1]], cards[[2]], ..., cards[[n]])
```

**Comment by wish1832** [comment]
That worked, thank you!
