### ISSUE TITLE
Cannot bookmark current active nav panel in `page_navbar()`

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#949]
> 2. I cannot restore the state of the app to the `nav_panel` of my choice (which is `Two` in the reprex below). The app always restores to the first `nav_panel`, `One`.

I have used a `navset_bar` in combination with `page_fluid` instead of `page_navbar` to solve this since `page_navbar` does not have an `id` argument.

_Originally posted by @benubah in https://github.com/rstudio/bslib/issues/945#issuecomment-1864496033_

**Comment by gadenbuie** [comment]
Hi @benubah, it turns out that `page_navbar()` [_does have_ an `id` argument](https://rstudio.github.io/bslib/reference/page_navbar.html)! 😄  When you provide an `id` for the page-level navbar, bookmarking works as expected.

Here's a small example app:

```r
library(shiny)
library(bslib)

ui <- function(request) {
 page_navbar(
  title = "My App",
  id = "my-app",
  sidebar = sidebar(
    open = "always",
    bookmarkButton()
  ),
  nav_panel(
    "One",
    "First page. Pick a page, get the bookmark, reload the app.",
    "Does the app open to the expected page?"
  ),
  nav_panel("Two", "Second page."),
  nav_panel("Three", "Third page."),
  nav_panel("Four", "Fourth page.")
 )
}

server <- function(input, output, session) {

}

shinyApp(ui, server, enableBookmarking = "url")
```

**Comment by benubah** [comment]
Sorry, I mixed up the `navbar`s and thanks for pointing it out.

Your work on `bslib` is one of a kind - very very robust!!! Thanks!!!
