### ISSUE TITLE
Provide full-screen expansion for cards in mobile layout

### ISSUE THREAD

**Issue by Damonsoul** [rstudio/bslib#960]
Hi, I would like to make a suggestion for optimizing `card()`. Currently, when the screen width is narrow (for example, when viewing on a mobile phone), it will automatically switch to the mobile layout view. In this case, the button to expand the card to full screen will be unavailable. I believe that the full-screen expansion button of card should be retained in the mobile layout.

**Comment by gadenbuie** [comment]
Thanks for the suggestion! Could to elaborate a little more? What use case(s) do you have in mind and how would full screen cards on mobile devices be helpful to you?
