### ISSUE TITLE
Additional Sidebar function to minify the sidebar

### ISSUE THREAD

**Issue by WickM** [rstudio/bslib#976]
I'm writing to express my deep appreciation for the outstanding work you've done on bslib! It's a fantastic library that significantly simplifies the theming process for Shiny and R Markdown applications.

I'd like to request the addition of a highly valuable feature: the ability to minify the sidebar, similar to the functionality showcased in the Bootstrap 5 documentation (https://getbootstrap.com/docs/5.0/examples/sidebars/) and the bs4Dash package (https://rinterface.github.io/bs4Dash/reference/dashboardSidebar.html).

I would like to have the abbility to not just hide my Sidebar. I want to show only the Icons, minify the sidebar, like it is possible in bs4dash. 

Thank you very much

**Comment by gadenbuie** [comment]
Thanks for the suggestion and your comments! We are planning on implementing this and are tracking that work in #585. I'll copy your helpful links into that thread. Thanks again!
