### ISSUE TITLE
How to add back dropshadow to card when choosing a theme?

### ISSUE THREAD

**Issue by ocstringham** [rstudio/bslib#979]
I'm using bootswatch theme "lumen" but now my `card()` and `nav_panel()` do not have a dropshadow. Is there a way to add the dropshadow back in?

**Comment by ocstringham** [comment]
Thank you, @gadenbuie. This worked for cards. At the same time, it did not work to give the nav_panel 'card' a shadow. Is there a special way to give nav_panel it's own shadow?

**Comment by cpsievert** [comment]
You currently have to do that via `htmltools::tagAppendAttributes()`

```r
page_fixed(
    theme = bs_theme(bootswatch = "lumen"), 
    navset_card_underline(nav_panel("A", "a"), nav_panel("B", "b")) |>
        htmltools::tagAppendAttributes(class = "shadow")
)
```

**Comment by ocstringham** [comment]
Worked like a charm. Good to know about `htmltools::tagAppendAttributes()`, that is useful. Thanks!
